import { describe, expect, it } from "vitest";

import {
  shouldDisallowMockEventFallbackInBrowser,
  shouldDisallowMockFallbackInBrowser,
  shouldPreferMockInBrowser,
} from "./mockPriorityCommands";

describe("mockPriorityCommands", () => {
  it("产品路径命令不再允许浏览器模式优先走 mock", () => {
    const commands = [
      "execution_run_get_general_workbench_state",
      "get_hint_routes",
      "memory_cleanup_memdir",
      "close_webview_panel",
      "check_for_updates",
      "download_update",
      "open_update_window",
      "companion_get_pet_status",
      "workspace_list",
      "aster_agent_init",
      "agent_runtime_get_tool_inventory",
      "agent_app_list_installed",
      "agent_app_start_ui_runtime",
      "get_model_registry",
      "knowledge_list_packs",
      "project_memory_get",
      "session_files_save_file",
    ];

    for (const command of commands) {
      expect(shouldPreferMockInBrowser(command)).toBe(false);
    }
  });

  it("图层设计工程目录命令在浏览器模式必须走真实桥接", () => {
    expect(
      shouldPreferMockInBrowser("save_layered_design_project_export"),
    ).toBe(false);
    expect(
      shouldPreferMockInBrowser("read_layered_design_project_export"),
    ).toBe(false);
    expect(
      shouldDisallowMockFallbackInBrowser("save_layered_design_project_export"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("read_layered_design_project_export"),
    ).toBe(true);
  });

  it("模型与运行时真相命令在浏览器模式下禁止静默退回 mock", () => {
    expect(shouldDisallowMockFallbackInBrowser("aster_agent_init")).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("open_update_window")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("agent_generate_title")).toBe(
      false,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("get_or_create_default_project"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("workspace_list")).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("workspace_get_default")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("workspace_get")).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("workspace_ensure_ready")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_submit_turn"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_runtime_start_task"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_inspect_local_package"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_save_installed_state"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_list_installed"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("knowledge_list_packs"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("get_automation_jobs")).toBe(
      false,
    );
    expect(shouldDisallowMockFallbackInBrowser("project_memory_get")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_start_ui_runtime"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_get_ui_runtime_status"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_stop_ui_runtime"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_runtime_cancel_task"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_runtime_get_task"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "agent_app_runtime_submit_host_response",
      ),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "agent_runtime_list_file_checkpoints",
      ),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_get_file_checkpoint"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_diff_file_checkpoint"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "agent_runtime_restore_file_checkpoint",
      ),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_list_sessions"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_update_session"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("execute_skill")).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("gateway_channel_status")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("wechat_channel_list_accounts"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("get_model_registry_provider_ids"),
    ).toBe(true);
    expect(shouldPreferMockInBrowser("session_files_save_file")).toBe(false);
    expect(shouldDisallowMockFallbackInBrowser("session_files_save_file")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("read_file_preview_cmd")).toBe(
      false,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("session_files_resolve_file_path"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("list_dir")).toBe(false);
    expect(
      shouldDisallowMockFallbackInBrowser("get_file_manager_locations"),
    ).toBe(false);
    expect(shouldDisallowMockFallbackInBrowser("get_file_icon_data_url")).toBe(
      false,
    );
    expect(shouldDisallowMockFallbackInBrowser("reveal_in_finder")).toBe(
      false,
    );
    expect(shouldDisallowMockFallbackInBrowser("open_with_default_app")).toBe(
      false,
    );
    expect(shouldDisallowMockFallbackInBrowser("upload_material")).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "create_image_generation_task_artifact",
      ),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("get_media_task_artifact")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("list_media_task_artifacts"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("cancel_media_task_artifact"),
    ).toBe(true);
    expect(shouldPreferMockInBrowser("voice_models_download")).toBe(false);
    expect(shouldPreferMockInBrowser("voice_models_get_install_state")).toBe(
      false,
    );
    expect(shouldDisallowMockFallbackInBrowser("voice_models_download")).toBe(
      true,
    );
  });

  it("Skills 管理命令在浏览器模式下禁止静默退回空 mock", () => {
    expect(shouldPreferMockInBrowser("get_local_skills_for_app")).toBe(false);
    expect(
      shouldDisallowMockFallbackInBrowser("get_local_skills_for_app"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("refresh_skill_cache")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("uninstall_skill_for_app")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("import_local_skill_for_app"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("install_marketplace_skill_for_app"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "install_skill_from_download_url_for_app",
      ),
    ).toBe(true);
  });

  it("运行时真相事件在浏览器模式下禁止静默退回 mock", () => {
    expect(
      shouldDisallowMockEventFallbackInBrowser("voice-model-download-progress"),
    ).toBe(true);
    expect(
      shouldDisallowMockEventFallbackInBrowser("aster_stream_session-1"),
    ).toBe(true);
    expect(
      shouldDisallowMockEventFallbackInBrowser(
        "agent_subagent_status:session-1",
      ),
    ).toBe(true);
    expect(
      shouldDisallowMockEventFallbackInBrowser(
        "agent_subagent_stream:session-1",
      ),
    ).toBe(true);
    expect(
      shouldDisallowMockEventFallbackInBrowser("companion-pet-status"),
    ).toBe(false);
  });
});
