import { describe, expect, it } from "vitest";

import {
  shouldDisallowMockEventFallbackInBrowser,
  shouldDisallowMockFallbackInBrowser,
  shouldPreferMockInBrowser,
} from "./mockPriorityCommands";

describe("mockPriorityCommands", () => {
  it("工作台阶段缺失桥接命令优先走 mock", () => {
    expect(
      shouldPreferMockInBrowser("execution_run_get_general_workbench_state"),
    ).toBe(true);
    expect(shouldPreferMockInBrowser("get_hint_routes")).toBe(true);
    expect(shouldPreferMockInBrowser("memory_cleanup_memdir")).toBe(true);
    expect(shouldPreferMockInBrowser("aster_agent_init")).toBe(false);
    expect(shouldPreferMockInBrowser("agent_runtime_get_tool_inventory")).toBe(
      false,
    );
    expect(shouldPreferMockInBrowser("list_dir")).toBe(false);
    expect(shouldPreferMockInBrowser("get_file_manager_locations")).toBe(false);
    expect(shouldPreferMockInBrowser("content_workflow_get_by_content")).toBe(
      false,
    );
    expect(shouldPreferMockInBrowser("close_webview_panel")).toBe(true);
    expect(shouldPreferMockInBrowser("agent_app_list_installed")).toBe(false);
    expect(shouldPreferMockInBrowser("agent_app_inspect_local_package")).toBe(
      false,
    );
    expect(shouldPreferMockInBrowser("agent_app_start_ui_runtime")).toBe(false);
    expect(shouldPreferMockInBrowser("agent_app_get_ui_runtime_status")).toBe(
      false,
    );
    expect(shouldPreferMockInBrowser("agent_app_stop_ui_runtime")).toBe(false);
    expect(
      shouldPreferMockInBrowser("start_oem_cloud_oauth_callback_bridge"),
    ).toBe(false);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "start_oem_cloud_oauth_callback_bridge",
      ),
    ).toBe(true);
  });

  it("图层设计工程目录命令在浏览器模式必须走真实桥接", () => {
    expect(
      shouldPreferMockInBrowser("save_layered_design_project_export"),
    ).toBe(false);
    expect(
      shouldPreferMockInBrowser("read_layered_design_project_export"),
    ).toBe(false);
    expect(
      shouldDisallowMockFallbackInBrowser("save_layered_design_project_export"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("read_layered_design_project_export"),
    ).toBe(true);
  });

  it("模型与运行时真相命令在浏览器模式下禁止静默退回 mock", () => {
    expect(shouldDisallowMockFallbackInBrowser("aster_agent_init")).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("agent_generate_title")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("get_or_create_default_project"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("workspace_list")).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("workspace_get_default")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("workspace_get")).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("workspace_ensure_ready")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_submit_turn"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_runtime_start_task"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_inspect_local_package"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_save_installed_state"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("agent_app_list_installed")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_start_ui_runtime"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_get_ui_runtime_status"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_stop_ui_runtime"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_runtime_cancel_task"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_app_runtime_get_task"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "agent_app_runtime_submit_host_response",
      ),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "agent_runtime_list_file_checkpoints",
      ),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_get_file_checkpoint"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_diff_file_checkpoint"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_list_sessions"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("agent_runtime_update_session"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("list_executable_skills")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("get_skill_detail")).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("execute_skill")).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("gateway_channel_status")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("wechat_channel_list_accounts"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("get_model_registry_provider_ids"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("get_provider_ui_state")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("get_api_key_provider")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("add_custom_api_key_provider"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("update_api_key_provider")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("delete_custom_api_key_provider"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("add_api_key")).toBe(true);
    expect(shouldPreferMockInBrowser("session_files_save_file")).toBe(false);
    expect(shouldDisallowMockFallbackInBrowser("session_files_save_file")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("read_file_preview_cmd")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("session_files_resolve_file_path"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("list_dir")).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("get_file_manager_locations"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("get_file_icon_data_url")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("upload_material")).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "create_image_generation_task_artifact",
      ),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("get_media_task_artifact")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("list_media_task_artifacts"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("cancel_media_task_artifact"),
    ).toBe(true);
    expect(shouldPreferMockInBrowser("voice_models_download")).toBe(false);
    expect(shouldPreferMockInBrowser("voice_models_get_install_state")).toBe(
      false,
    );
    expect(shouldDisallowMockFallbackInBrowser("voice_models_download")).toBe(
      true,
    );
  });

  it("Skills 管理命令在浏览器模式下禁止静默退回空 mock", () => {
    expect(shouldPreferMockInBrowser("get_local_skills_for_app")).toBe(false);
    expect(
      shouldDisallowMockFallbackInBrowser("get_local_skills_for_app"),
    ).toBe(true);
    expect(shouldDisallowMockFallbackInBrowser("refresh_skill_cache")).toBe(
      true,
    );
    expect(shouldDisallowMockFallbackInBrowser("uninstall_skill_for_app")).toBe(
      true,
    );
    expect(
      shouldDisallowMockFallbackInBrowser("import_local_skill_for_app"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser("install_marketplace_skill_for_app"),
    ).toBe(true);
    expect(
      shouldDisallowMockFallbackInBrowser(
        "install_skill_from_download_url_for_app",
      ),
    ).toBe(true);
  });

  it("运行时真相事件在浏览器模式下禁止静默退回 mock", () => {
    expect(
      shouldDisallowMockEventFallbackInBrowser("voice-model-download-progress"),
    ).toBe(true);
    expect(
      shouldDisallowMockEventFallbackInBrowser("aster_stream_session-1"),
    ).toBe(true);
    expect(
      shouldDisallowMockEventFallbackInBrowser(
        "agent_subagent_status:session-1",
      ),
    ).toBe(true);
    expect(
      shouldDisallowMockEventFallbackInBrowser(
        "agent_subagent_stream:session-1",
      ),
    ).toBe(true);
    expect(
      shouldDisallowMockEventFallbackInBrowser("companion-pet-status"),
    ).toBe(false);
  });
});
