/**
 * 浏览器模式下优先走 mock 的命令集合。
 *
 * 这些命令要么依赖当前 DevBridge 尚未桥接的原生能力，
 * 要么即使缺少真实后端也不应阻塞默认页面渲染。
 */

const mockPriorityCommands = new Set<string>([
  "agent_runtime_export_analysis_handoff",
  "agent_runtime_export_handoff_bundle",
  "agent_runtime_export_evidence_pack",
  "agent_runtime_export_review_decision_template",
  "agent_runtime_save_review_decision",
  "agent_runtime_export_replay_case",
  "companion_get_pet_status",
  "companion_launch_pet",
  "companion_send_pet_command",
  "subscribe_sysinfo",
  "unsubscribe_sysinfo",
  "session_files_get_or_create",
  "session_files_update_meta",
  "session_files_list_files",
  "session_files_read_file",
  "session_files_delete_file",
  "save_exported_document",
  "execution_run_get_general_workbench_state",
  "get_hint_routes",
  "memory_runtime_get_working_memory",
  "memory_runtime_get_extraction_status",
  "memory_runtime_prefetch_for_turn",
  "memory_cleanup_memdir",
  "memory_scaffold_memdir",
  "close_webview_panel",
  "get_webview_panels",
  "focus_webview_panel",
  "navigate_webview_panel",
  "get_browser_connector_settings_cmd",
  "set_browser_connector_install_root_cmd",
  "set_browser_connector_enabled_cmd",
  "set_system_connector_enabled_cmd",
  "set_browser_action_capability_enabled_cmd",
  "get_browser_connector_install_status_cmd",
  "install_browser_connector_extension_cmd",
  "open_browser_extensions_page_cmd",
  "open_browser_remote_debugging_page_cmd",
  "open_browser_connector_guide_window",
  "disconnect_browser_connector_session",
  "launch_browser_session",
  "launch_browser_profile_runtime_assist_cmd",
  "get_browser_action_audit_logs",
]);

/**
 * 浏览器模式下必须以桥接后端为真相源的命令集合。
 *
 * 这些命令一旦桥接失败，就必须直接暴露错误；
 * 不能再静默回退到 mock，把“后端未连上 / 命令失败”伪装成“只是没有数据”。
 */
const bridgeTruthCommands = new Set<string>([
  "aster_agent_init",
  "aster_agent_status",
  "start_oem_cloud_oauth_callback_bridge",
  "agent_generate_title",
  "get_or_create_default_project",
  "workspace_list",
  "workspace_get_default",
  "workspace_get",
  "workspace_ensure_ready",
  "agent_runtime_submit_turn",
  "agent_runtime_interrupt_turn",
  "agent_runtime_compact_session",
  "agent_runtime_resume_thread",
  "agent_runtime_replay_request",
  "agent_runtime_get_thread_read",
  "agent_runtime_get_objective",
  "agent_runtime_set_objective",
  "agent_runtime_update_objective_status",
  "agent_runtime_clear_objective",
  "agent_runtime_continue_objective",
  "agent_runtime_audit_objective",
  "agent_runtime_list_file_checkpoints",
  "agent_runtime_get_file_checkpoint",
  "agent_runtime_diff_file_checkpoint",
  "agent_runtime_promote_queued_turn",
  "agent_runtime_remove_queued_turn",
  "agent_runtime_respond_action",
  "agent_app_start_ui_runtime",
  "agent_app_get_ui_runtime_status",
  "agent_app_stop_ui_runtime",
  "agent_app_select_directory",
  "agent_app_launch_shell",
  "agent_app_runtime_start_task",
  "agent_app_runtime_cancel_task",
  "agent_app_runtime_get_task",
  "agent_app_runtime_submit_host_response",
  "agent_runtime_create_session",
  "agent_runtime_list_sessions",
  "agent_runtime_get_session",
  "agent_runtime_update_session",
  "agent_runtime_delete_session",
  "agent_runtime_get_tool_inventory",
  "agent_runtime_spawn_subagent",
  "agent_runtime_send_subagent_input",
  "agent_runtime_wait_subagents",
  "agent_runtime_resume_subagent",
  "agent_runtime_close_subagent",
  "list_executable_skills",
  "get_skill_detail",
  "execute_skill",
  "gateway_channel_status",
  "wechat_channel_list_accounts",
  "get_default_provider",
  "get_provider_ui_state",
  "get_api_key_providers",
  "get_api_key_provider",
  "add_custom_api_key_provider",
  "update_api_key_provider",
  "delete_custom_api_key_provider",
  "add_api_key",
  "get_model_registry",
  "get_model_registry_provider_ids",
  "get_models_for_provider",
  "get_models_by_tier",
  "get_provider_alias_config",
  "get_all_alias_configs",
  "refresh_model_registry",
  "fetch_provider_models_auto",
  "create_image_generation_task_artifact",
  "create_audio_generation_task_artifact",
  "complete_audio_generation_task_artifact",
  "get_media_task_artifact",
  "list_media_task_artifacts",
  "cancel_media_task_artifact",
  "save_layered_design_project_export",
  "read_layered_design_project_export",
  "agent_app_inspect_local_package",
  "agent_app_fetch_cloud_package",
  "agent_app_save_installed_state",
  "agent_app_list_installed",
  "agent_app_set_disabled",
  "agent_app_uninstall_rehearsal",
  "agent_app_uninstall",
  "capability_draft_create",
  "capability_draft_list",
  "capability_draft_get",
  "capability_draft_verify",
  "capability_draft_register",
  "capability_draft_list_registered_skills",
  "capability_draft_submit_approval_session_inputs",
  "capability_draft_execute_controlled_get",
  "agent_runtime_list_workspace_skill_bindings",
  "get_skills_for_app",
  "get_local_skills_for_app",
  "install_skill_for_app",
  "uninstall_skill_for_app",
  "get_skill_repos",
  "add_skill_repo",
  "remove_skill_repo",
  "get_installed_lime_skills",
  "refresh_skill_cache",
  "inspect_local_skill_for_app",
  "inspect_local_skill_detail_for_app",
  "reveal_local_skill_for_app",
  "rename_local_skill_for_app",
  "replace_local_skill_package_for_app",
  "create_skill_scaffold_for_app",
  "import_local_skill_for_app",
  "inspect_local_skill_package_for_app",
  "install_local_skill_package_for_app",
  "export_local_skill_package_for_app",
  "take_pending_skill_package_open_requests",
  "get_skill_package_file_association_status",
  "set_skill_package_file_association_default",
  "install_marketplace_skill_for_app",
  "install_skill_from_download_url_for_app",
  "inspect_remote_skill",
  "knowledge_import_source",
  "knowledge_compile_pack",
  "knowledge_list_packs",
  "knowledge_get_pack",
  "knowledge_set_default_pack",
  "knowledge_update_pack_status",
  "knowledge_resolve_context",
  "knowledge_validate_context_run",
  "list_dir",
  "get_home_dir",
  "get_file_manager_locations",
  "get_file_icon_data_url",
  "create_file",
  "create_directory",
  "delete_file",
  "rename_file",
  "get_file_name",
  "reveal_in_finder",
  "open_with_default_app",
  "session_files_save_file",
  "read_file_preview_cmd",
  "session_files_resolve_file_path",
  "upload_material",
  "voice_models_download",
  "voice_models_delete",
  "voice_models_set_default",
  "voice_models_test_transcribe_file",
]);

const bridgeTruthEventPrefixes = [
  "voice-model-download-progress",
  "aster_stream_",
  "agent_subagent_status:",
  "agent_subagent_stream:",
];

export function shouldPreferMockInBrowser(cmd: string): boolean {
  return mockPriorityCommands.has(cmd);
}

export function shouldDisallowMockFallbackInBrowser(cmd: string): boolean {
  return bridgeTruthCommands.has(cmd);
}

export function shouldDisallowMockEventFallbackInBrowser(
  eventName: string,
): boolean {
  const normalizedEventName = eventName.trim();
  if (!normalizedEventName) {
    return false;
  }
  return bridgeTruthEventPrefixes.some((prefix) =>
    normalizedEventName.startsWith(prefix),
  );
}
