export const MESSAGE_LIST_PROGRESSIVE_RENDER_THRESHOLD = 72;
export const MESSAGE_LIST_INITIAL_RENDER_COUNT = 36;
export const MESSAGE_LIST_RENDER_BATCH_SIZE = 48;
export const MESSAGE_LIST_RESTORED_PROGRESSIVE_RENDER_THRESHOLD = 20;
export const MESSAGE_LIST_RESTORED_INITIAL_RENDER_COUNT = 10;
export const MESSAGE_LIST_RESTORED_RENDER_BATCH_SIZE = 6;
export const MESSAGE_LIST_PROGRESSIVE_RENDER_MINIMUM_DELAY_MS = 120;
export const MESSAGE_LIST_RESTORED_PROGRESSIVE_RENDER_MINIMUM_DELAY_MS = 600;
export const MESSAGE_LIST_TIMELINE_DEFER_MESSAGE_THRESHOLD = 24;
export const MESSAGE_LIST_TIMELINE_DEFER_ITEM_THRESHOLD = 24;
export const MESSAGE_LIST_HISTORICAL_TIMELINE_COMPACT_ITEM_THRESHOLD = 8;
export const MESSAGE_LIST_HISTORICAL_TIMELINE_IDLE_DELAY_MS = 80;
export const MESSAGE_LIST_RESTORED_HISTORICAL_TIMELINE_IDLE_DELAY_MS = 900;
export const MESSAGE_LIST_COMPACT_HISTORICAL_ASSISTANT_THRESHOLD = 900;
export const MESSAGE_LIST_COMPACT_HISTORICAL_ASSISTANT_PREVIEW_CHARS = 900;
export const MESSAGE_LIST_LONG_HISTORICAL_MESSAGE_THRESHOLD = 24_000;
export const MESSAGE_LIST_LONG_HISTORICAL_MESSAGE_PREVIEW_CHARS = 2_000;
export const MESSAGE_LIST_RESTORED_MARKDOWN_HYDRATION_INITIAL_COUNT = 2;
export const MESSAGE_LIST_RESTORED_MARKDOWN_HYDRATION_BATCH_SIZE = 2;
export const MESSAGE_LIST_RESTORED_MARKDOWN_HYDRATION_DELAY_MS = 140;
export const MESSAGE_LIST_RENDER_WINDOW_SETTINGS = {
  regular: {
    progressiveRenderThreshold: MESSAGE_LIST_PROGRESSIVE_RENDER_THRESHOLD,
    initialRenderCount: MESSAGE_LIST_INITIAL_RENDER_COUNT,
    renderBatchSize: MESSAGE_LIST_RENDER_BATCH_SIZE,
    minimumDelayMs: MESSAGE_LIST_PROGRESSIVE_RENDER_MINIMUM_DELAY_MS,
  },
  restored: {
    progressiveRenderThreshold:
      MESSAGE_LIST_RESTORED_PROGRESSIVE_RENDER_THRESHOLD,
    initialRenderCount: MESSAGE_LIST_RESTORED_INITIAL_RENDER_COUNT,
    renderBatchSize: MESSAGE_LIST_RESTORED_RENDER_BATCH_SIZE,
    minimumDelayMs: MESSAGE_LIST_RESTORED_PROGRESSIVE_RENDER_MINIMUM_DELAY_MS,
  },
} as const;
