import type { AgentAppProjection, AppCleanupPlan, CleanupTarget } from "../types";

const DEFAULT_AGENT_APP_DATA_ROOT = "<LimeAppData>/agent-apps";

function pathTarget(value: string, reason: string): CleanupTarget {
  return {
    kind: "path",
    value,
    exists: "unknown",
    safeToDelete: true,
    reason,
  };
}

function namespaceTarget(value: string, reason: string): CleanupTarget {
  return {
    kind: "namespace",
    value,
    exists: "unknown",
    safeToDelete: true,
    reason,
  };
}

export function buildCleanupPlan(params: {
  projection: AgentAppProjection;
  dataRoot?: string;
  generatedAt?: string;
}): AppCleanupPlan {
  const { projection } = params;
  const dataRoot = params.dataRoot ?? DEFAULT_AGENT_APP_DATA_ROOT;
  const appId = projection.app.appId;
  const packageHash = projection.package.packageHash;

  return {
    mode: "dry-run",
    appId,
    packageHash,
    generatedAt: params.generatedAt ?? new Date().toISOString(),
    packageCachePaths: [
      pathTarget(`${dataRoot}/packages/${packageHash}`, "Cached runtime package for this Agent App."),
    ],
    projectionPaths: [
      pathTarget(`${dataRoot}/projections/${appId}.json`, "Read-only projection generated from manifest."),
    ],
    readinessPaths: [
      pathTarget(`${dataRoot}/readiness/${appId}.json`, "Readiness snapshot generated by P0 host."),
    ],
    storageNamespaces: projection.storage
      ? [
          namespaceTarget(
            `${dataRoot}/storage/${projection.storage.namespace}`,
            "App storage namespace declared by manifest; P0 only previews it.",
          ),
        ]
      : [],
    artifactRefs: [],
    evidenceRefs: [],
    taskRefs: [],
    secretRefs: [],
    logPaths: [pathTarget(`${dataRoot}/logs/${appId}`, "Agent App host logs for this app.")],
    exportPaths: [pathTarget(`${dataRoot}/exports/${appId}`, "Optional user exports before deletion.")],
    warnings: [
      {
        code: "DRY_RUN_ONLY",
        message: "P0 only builds cleanup plans and does not delete local data.",
      },
    ],
  };
}
