import type { AgentAppProjection, AppCleanupPlan, CleanupTarget } from "../types";

const DEFAULT_AGENT_APP_DATA_ROOT = "<LimeAppData>/agent-apps";

function pathTarget(value: string, reason: string): CleanupTarget {
  return {
    kind: "path",
    value,
    exists: "unknown",
    safeToDelete: true,
    reason,
  };
}

function namespaceTarget(value: string, reason: string): CleanupTarget {
  return {
    kind: "namespace",
    value,
    exists: "unknown",
    safeToDelete: true,
    reason,
  };
}

function refTarget(value: string, reason: string): CleanupTarget {
  return {
    kind: "ref",
    value,
    exists: "unknown",
    safeToDelete: true,
    reason,
  };
}

export function buildCleanupPlan(params: {
  projection: AgentAppProjection;
  dataRoot?: string;
  generatedAt?: string;
}): AppCleanupPlan {
  const { projection } = params;
  const dataRoot = params.dataRoot ?? DEFAULT_AGENT_APP_DATA_ROOT;
  const appId = projection.app.appId;
  const packageHash = projection.package.packageHash;

  return {
    mode: "dry-run",
    appId,
    packageHash,
    generatedAt: params.generatedAt ?? new Date().toISOString(),
    installedStatePaths: [
      pathTarget(
        `${dataRoot}/installed/${appId}.json`,
        "Installed Agent App state snapshot for restore and review.",
      ),
    ],
    packageCachePaths: [
      pathTarget(`${dataRoot}/packages/${packageHash}`, "Cached runtime package for this Agent App."),
    ],
    packageCacheIndexPaths: [
      pathTarget(
        `${dataRoot}/package-index/${appId}.json`,
        "Package cache index and verified package pointer for this Agent App.",
      ),
    ],
    packageStagingPaths: [
      pathTarget(
        `${dataRoot}/staging/${appId}`,
        "Staged Agent App package used for upgrade verification before commit.",
      ),
    ],
    projectionPaths: [
      pathTarget(`${dataRoot}/projections/${appId}.json`, "Read-only projection generated from manifest."),
    ],
    readinessPaths: [
      pathTarget(`${dataRoot}/readiness/${appId}.json`, "Readiness snapshot generated by P0 host."),
    ],
    setupStatePaths: [
      pathTarget(
        `${dataRoot}/setup/${appId}.json`,
        "Installed setup binding state for this Agent App.",
      ),
    ],
    overlayRefs: projection.overlayTemplates.map((overlay) =>
      refTarget(
        `overlay-ref:${appId}:${overlay.key}`,
        "Overlay binding reference; cleanup evidence never includes overlay values.",
      ),
    ),
    storageNamespaces: projection.storage
      ? [
          namespaceTarget(
            `${dataRoot}/storage/${projection.storage.namespace}`,
            "App storage namespace declared by manifest; P0 only previews it.",
          ),
        ]
      : [],
    artifactRefs: projection.artifactTypes.map((artifact) =>
      refTarget(
        `artifact-ref:${appId}:${artifact.key}`,
        "Artifact namespace declared by manifest; P17.3 only classifies the reference.",
      ),
    ),
    evidenceRefs: projection.evals
      .filter((evalRule) => evalRule.evidenceRequired)
      .map((evalRule) =>
        refTarget(
          `evidence-ref:${appId}:${evalRule.key}`,
          "Evidence namespace declared by eval rules; P17.3 only classifies the reference.",
        ),
      ),
    taskRefs: projection.workflows.map((workflow) =>
      refTarget(
        `task-ref:${appId}:${workflow.key}`,
        "Workflow task namespace declared by manifest; P17.3 only classifies the reference.",
      ),
    ),
    secretRefs: projection.secrets.map((secret) =>
      refTarget(
        `secret-ref:${appId}:${secret.key}`,
        "Secret binding reference only; secret values are never exported.",
      ),
    ),
    logPaths: [pathTarget(`${dataRoot}/logs/${appId}`, "Agent App host logs for this app.")],
    exportPaths: [pathTarget(`${dataRoot}/exports/${appId}`, "Optional user exports before deletion.")],
    warnings: [
      {
        code: "DRY_RUN_ONLY",
        message: "P0 only builds cleanup plans and does not delete local data.",
      },
    ],
  };
}
