import type { CodexSlashCommandDefinition } from "./types";

export const CODEX_SLASH_COMMANDS: CodexSlashCommandDefinition[] = [
  {
    key: "compact",
    commandName: "compact",
    commandPrefix: "/compact",
    label: "压缩上下文",
    description: "压缩当前会话上下文并写入摘要",
    aliases: ["compress", "summarize"],
    kind: "local_action",
    support: "supported",
  },
  {
    key: "clear",
    commandName: "clear",
    commandPrefix: "/clear",
    label: "清空任务",
    description: "清空当前任务消息并回到空白输入态",
    aliases: ["reset"],
    kind: "local_action",
    support: "supported",
  },
  {
    key: "new",
    commandName: "new",
    commandPrefix: "/new",
    label: "新建任务",
    description: "创建一个新任务，可选附带标题",
    aliases: ["chat-new", "task-new"],
    kind: "local_action",
    support: "supported",
    argumentHint: "[title]",
  },
  {
    key: "review",
    commandName: "review",
    commandPrefix: "/review",
    label: "代码审查",
    description: "以审查模式检查当前改动或指定范围",
    aliases: ["cr"],
    kind: "prompt_action",
    support: "supported",
    argumentHint: "[scope]",
  },
  {
    key: "init",
    commandName: "init",
    commandPrefix: "/init",
    label: "初始化仓库指令",
    description: "生成或更新仓库根目录的 AGENTS.md",
    aliases: ["bootstrap"],
    kind: "prompt_action",
    support: "supported",
    argumentHint: "[requirements]",
  },
  {
    key: "diff",
    commandName: "diff",
    commandPrefix: "/diff",
    label: "检查变更",
    description: "分析当前 diff 或指定变更范围",
    aliases: ["changes"],
    kind: "prompt_action",
    support: "supported",
    argumentHint: "[scope]",
  },
  {
    key: "status",
    commandName: "status",
    commandPrefix: "/status",
    label: "会话状态",
    description: "查看当前会话、执行与排队状态",
    aliases: ["state"],
    kind: "info",
    support: "supported",
  },
  {
    key: "model",
    commandName: "model",
    commandPrefix: "/model",
    label: "当前模型",
    description: "查看当前 provider 与模型配置",
    aliases: ["models"],
    kind: "info",
    support: "supported",
  },
  {
    key: "subagents",
    commandName: "subagents",
    commandPrefix: "/subagents",
    label: "Subagents",
    description: "切换或查看子代理线程",
    aliases: ["agent"],
    kind: "local_action",
    support: "supported",
  },
  {
    key: "help",
    commandName: "help",
    commandPrefix: "/help",
    label: "命令帮助",
    description: "查看已接入的 Codex slash 命令",
    aliases: ["?"],
    kind: "info",
    support: "supported",
  },
  {
    key: "quit",
    commandName: "quit",
    commandPrefix: "/quit",
    label: "退出",
    description: "Codex TUI 退出命令，Lime 暂未接入",
    aliases: ["exit"],
    kind: "local_action",
    support: "unsupported",
  },
  {
    key: "ps",
    commandName: "ps",
    commandPrefix: "/ps",
    label: "任务列表",
    description: "Codex 任务面板命令，Lime 暂未接入",
    aliases: [],
    kind: "info",
    support: "unsupported",
  },
  {
    key: "stop",
    commandName: "stop",
    commandPrefix: "/stop",
    label: "停止任务",
    description: "Codex stop 命令，Lime 暂未接入",
    aliases: [],
    kind: "local_action",
    support: "unsupported",
  },
  {
    key: "statusline",
    commandName: "statusline",
    commandPrefix: "/statusline",
    label: "状态栏",
    description: "Codex 状态栏命令，Lime 暂未接入",
    aliases: [],
    kind: "info",
    support: "unsupported",
  },
  {
    key: "theme",
    commandName: "theme",
    commandPrefix: "/theme",
    label: "界面主题",
    description: "Codex TUI 主题命令，Lime 暂未接入",
    aliases: [],
    kind: "info",
    support: "unsupported",
  },
  {
    key: "mcp",
    commandName: "mcp",
    commandPrefix: "/mcp",
    label: "MCP 面板",
    description: "Codex MCP 面板命令，Lime 暂未接入",
    aliases: [],
    kind: "info",
    support: "unsupported",
  },
  {
    key: "apps",
    commandName: "apps",
    commandPrefix: "/apps",
    label: "应用面板",
    description: "Codex apps 命令，Lime 暂未接入",
    aliases: [],
    kind: "info",
    support: "unsupported",
  },
  {
    key: "plugins",
    commandName: "plugins",
    commandPrefix: "/plugins",
    label: "插件面板",
    description: "Codex plugins 命令，Lime 暂未接入",
    aliases: [],
    kind: "info",
    support: "unsupported",
  },
];
