import {
  resolveLimeColorSchemeId,
  type LimeColorSchemeId,
} from "./colorSchemes";
import { normalizeLocale, type SupportedLocale } from "@/i18n/locales";

export interface LimeSkinHomeCopy {
  brandSubtitle?: string;
  eyebrow: string;
  slogan: string;
  description: string;
  status: string;
  tagline: string;
}

interface LimeSkinCopy extends LimeSkinHomeCopy {
  brandSubtitle: string;
}

type LocalizedSkinCopy = Record<SupportedLocale, LimeSkinCopy>;

function localized(
  zhCN: LimeSkinCopy,
  zhTW: LimeSkinCopy,
  enUS: LimeSkinCopy,
  jaJP: LimeSkinCopy,
  koKR: LimeSkinCopy,
): LocalizedSkinCopy {
  return {
    "zh-CN": zhCN,
    "zh-TW": zhTW,
    "en-US": enUS,
    "ja-JP": jaJP,
    "ko-KR": koKR,
  };
}

const SKIN_CONTENT: Record<LimeColorSchemeId, LocalizedSkinCopy> = {
  "dream-blossom": localized(
    {
      brandSubtitle: "DREAM BLOSSOM",
      tagline: "让灵感在花幕里慢慢展开。",
      eyebrow: "创作",
      slogan: "青柠一下，灵感即来",
      description: "说一句目标，Lime 就接着帮你做。",
      status: "花境在线",
    },
    {
      brandSubtitle: "DREAM BLOSSOM",
      tagline: "讓靈感在花幕裡慢慢展開。",
      eyebrow: "創作",
      slogan: "青檸一下，靈感即來",
      description: "說一句目標，Lime 就接著幫你做。",
      status: "花境在線",
    },
    {
      brandSubtitle: "DREAM BLOSSOM",
      tagline: "Let ideas unfold in a quiet bloom.",
      eyebrow: "Create",
      slogan: "Say the goal. Let Lime carry it forward.",
      description: "Give Lime one clear goal and keep moving.",
      status: "BLOOM ONLINE",
    },
    {
      brandSubtitle: "DREAM BLOSSOM",
      tagline: "花の中で、ひらめきをゆっくり育てる。",
      eyebrow: "制作",
      slogan: "Limeに聞けば、ひらめきが動き出す",
      description: "目標を一言伝えれば、Limeが続きの作業を進めます。",
      status: "BLOOM ONLINE",
    },
    {
      brandSubtitle: "DREAM BLOSSOM",
      tagline: "꽃 사이에서 영감을 천천히 펼쳐 보세요.",
      eyebrow: "제작",
      slogan: "Lime에게 말하면 아이디어가 시작됩니다",
      description: "목표를 한마디로 말하면 Lime이 이어서 도와드립니다.",
      status: "BLOOM ONLINE",
    },
  ),
  "lime-classic": localized(
    {
      brandSubtitle: "FOREST WORKSPACE",
      tagline: "把复杂工作放进一片安静的森林。",
      eyebrow: "森林工作台",
      slogan: "进林子，先把事情做完",
      description: "目标交给 Lime，剩下的步骤一起稳稳推进。",
      status: "森林在线",
    },
    {
      brandSubtitle: "FOREST WORKSPACE",
      tagline: "把複雜工作放進一片安靜的森林。",
      eyebrow: "森林工作台",
      slogan: "進林子，先把事情做完",
      description: "目標交給 Lime，剩下的步驟一起穩穩推進。",
      status: "森林在線",
    },
    {
      brandSubtitle: "FOREST WORKSPACE",
      tagline: "A quiet forest for focused work.",
      eyebrow: "Forest workspace",
      slogan: "Step in. Get the work done.",
      description: "Give Lime the goal and move through every next step.",
      status: "FOREST ONLINE",
    },
    {
      brandSubtitle: "FOREST WORKSPACE",
      tagline: "静かな森に、複雑な仕事を置いていく。",
      eyebrow: "森のワークスペース",
      slogan: "森に入り、まず仕事を終わらせる",
      description: "目標をLimeに渡せば、次の手順を一緒に進められます。",
      status: "FOREST ONLINE",
    },
    {
      brandSubtitle: "FOREST WORKSPACE",
      tagline: "복잡한 일을 고요한 숲에 내려놓으세요.",
      eyebrow: "숲 작업 공간",
      slogan: "숲에 들어와, 일부터 끝내세요",
      description: "목표를 Lime에 맡기고 다음 단계를 차분히 진행합니다.",
      status: "FOREST ONLINE",
    },
  ),
  "lime-forest": localized(
    {
      brandSubtitle: "财神打工版 · LIME",
      tagline: "让代码为你打工，效率和财运一起到位。",
      eyebrow: "财神打工版",
      slogan: "财神坐镇，项目稳稳推进",
      description: "说一句目标，财神就接着帮你做；今天的灵感和进度都不掉线。",
      status: "今日财运在线",
    },
    {
      brandSubtitle: "財神打工版 · LIME",
      tagline: "讓程式碼替你打工，效率和財運一起到位。",
      eyebrow: "財神打工版",
      slogan: "財神坐鎮，專案穩穩推進",
      description: "說一句目標，財神就接著幫你做；今天的靈感和進度都不掉線。",
      status: "今日財運在線",
    },
    {
      brandSubtitle: "GOD OF WEALTH · LIME",
      tagline: "Let your code work for you, with a little extra luck.",
      eyebrow: "God of Wealth mode",
      slogan: "Good fortune. Steady progress.",
      description: "Say the goal and let Lime keep the work moving with you.",
      status: "LUCK ONLINE",
    },
    {
      brandSubtitle: "財神ワーク · LIME",
      tagline: "コードに働いてもらい、効率と運を一緒に上げる。",
      eyebrow: "財神ワーク",
      slogan: "財神と一緒に、着実に前へ",
      description: "目標を一言伝えれば、Limeが今日の作業を続けます。",
      status: "LUCK ONLINE",
    },
    {
      brandSubtitle: "재물신 워크 · LIME",
      tagline: "코드가 대신 일하게 하고, 효율과 행운을 함께 챙기세요.",
      eyebrow: "재물신 모드",
      slogan: "행운을 켜고, 작업은 착착",
      description: "목표를 한마디로 말하면 Lime이 다음 일을 이어갑니다.",
      status: "LUCK ONLINE",
    },
  ),
  "lime-ocean": localized(
    {
      brandSubtitle: "ULTRAMAN GUARD",
      tagline: "守住目标，也守住每一步进度。",
      eyebrow: "守护模式",
      slogan: "能量上线，任务稳住",
      description: "把目标交给 Lime，让每一步都有清晰回应。",
      status: "守护在线",
    },
    {
      brandSubtitle: "ULTRAMAN GUARD",
      tagline: "守住目標，也守住每一步進度。",
      eyebrow: "守護模式",
      slogan: "能量上線，任務穩住",
      description: "把目標交給 Lime，讓每一步都有清晰回應。",
      status: "守護在線",
    },
    {
      brandSubtitle: "ULTRAMAN GUARD",
      tagline: "Protect the goal. Keep every step moving.",
      eyebrow: "Guard mode",
      slogan: "Power on. Mission steady.",
      description: "Give Lime the objective and keep every next step clear.",
      status: "GUARD ONLINE",
    },
    {
      brandSubtitle: "ULTRAMAN GUARD",
      tagline: "目標を守り、進捗の一歩一歩を守る。",
      eyebrow: "ガードモード",
      slogan: "エネルギー全開、任務は安定",
      description: "目標をLimeに渡して、次の一歩を明確に進めます。",
      status: "GUARD ONLINE",
    },
    {
      brandSubtitle: "ULTRAMAN GUARD",
      tagline: "목표를 지키고, 모든 진행을 이어가세요.",
      eyebrow: "수호 모드",
      slogan: "에너지 온, 임무 안정",
      description: "목표를 Lime에 맡기고 다음 단계를 또렷하게 진행합니다.",
      status: "GUARD ONLINE",
    },
  ),
  "lime-sand": localized(
    {
      brandSubtitle: "东方国潮",
      tagline: "在山河与云纹之间，把事情做成。",
      eyebrow: "国潮创作",
      slogan: "借一程山河，把灵感落地",
      description: "一句目标，Lime 帮你把想法整理成下一步。",
      status: "山河在线",
    },
    {
      brandSubtitle: "東方國潮",
      tagline: "在山河與雲紋之間，把事情做成。",
      eyebrow: "國潮創作",
      slogan: "借一程山河，把靈感落地",
      description: "一句目標，Lime 幫你把想法整理成下一步。",
      status: "山河在線",
    },
    {
      brandSubtitle: "EASTERN FLOW",
      tagline: "Turn a clear idea into the next decisive step.",
      eyebrow: "Eastern flow",
      slogan: "Let the landscape carry the idea forward.",
      description: "Give Lime one goal and turn the thought into motion.",
      status: "FLOW ONLINE",
    },
    {
      brandSubtitle: "東方国潮",
      tagline: "山河と雲の間で、仕事を形にする。",
      eyebrow: "国潮クリエイト",
      slogan: "山河を借りて、ひらめきを形に",
      description: "目標を一言で伝えれば、Limeが次の一歩に整えます。",
      status: "FLOW ONLINE",
    },
    {
      brandSubtitle: "EASTERN FLOW",
      tagline: "산과 구름 사이에서 아이디어를 현실로 만드세요.",
      eyebrow: "동양 창작",
      slogan: "풍경을 빌려, 영감을 현실로",
      description: "목표를 말하면 Lime이 다음 단계로 정리합니다.",
      status: "FLOW ONLINE",
    },
  ),
  "lime-neon": localized(
    {
      brandSubtitle: "MUSIC MODE",
      tagline: "让每个想法都跟上自己的节拍。",
      eyebrow: "舞台模式",
      slogan: "开麦，灵感开始发光",
      description: "一句目标，Lime 帮你把节奏接着写下去。",
      status: "STAGE ONLINE",
    },
    {
      brandSubtitle: "MUSIC MODE",
      tagline: "讓每個想法都跟上自己的節拍。",
      eyebrow: "舞台模式",
      slogan: "開麥，靈感開始發光",
      description: "一句目標，Lime 幫你把節奏接著寫下去。",
      status: "STAGE ONLINE",
    },
    {
      brandSubtitle: "MUSIC MODE",
      tagline: "Give every idea its own rhythm.",
      eyebrow: "Stage mode",
      slogan: "Mic on. Let ideas glow.",
      description: "Say the goal and let Lime keep the rhythm going.",
      status: "STAGE ONLINE",
    },
    {
      brandSubtitle: "MUSIC MODE",
      tagline: "ひらめきそれぞれのリズムに乗せる。",
      eyebrow: "ステージモード",
      slogan: "マイクオン、ひらめきが光り出す",
      description: "目標を伝えれば、Limeが次のリズムを書き進めます。",
      status: "STAGE ONLINE",
    },
    {
      brandSubtitle: "MUSIC MODE",
      tagline: "모든 아이디어가 자기 박자를 찾게 하세요.",
      eyebrow: "스테이지 모드",
      slogan: "마이크 온, 영감이 빛나요",
      description: "목표를 말하면 Lime이 리듬을 이어갑니다.",
      status: "STAGE ONLINE",
    },
  ),
  "lime-citron": localized(
    {
      brandSubtitle: "IDEA BOY",
      tagline: "把脑洞打开，把下一步点亮。",
      eyebrow: "灵感少年",
      slogan: "脑洞一开，事情就来",
      description: "把想法说出来，Lime 帮你把它变成能执行的动作。",
      status: "IDEA ONLINE",
    },
    {
      brandSubtitle: "IDEA BOY",
      tagline: "把腦洞打開，把下一步點亮。",
      eyebrow: "靈感少年",
      slogan: "腦洞一開，事情就來",
      description: "把想法說出來，Lime 幫你把它變成能執行的動作。",
      status: "IDEA ONLINE",
    },
    {
      brandSubtitle: "IDEA BOY",
      tagline: "Open the idea. Light up the next move.",
      eyebrow: "Idea mode",
      slogan: "Open the loop. Start the work.",
      description:
        "Say what is on your mind and turn it into an action with Lime.",
      status: "IDEA ONLINE",
    },
    {
      brandSubtitle: "IDEA BOY",
      tagline: "アイデアを開き、次の一歩を照らす。",
      eyebrow: "ひらめきボーイ",
      slogan: "ひらめいたら、すぐ動き出そう",
      description: "考えを話せば、Limeが実行できる動きに整えます。",
      status: "IDEA ONLINE",
    },
    {
      brandSubtitle: "IDEA BOY",
      tagline: "아이디어를 열고 다음 행동을 밝혀 보세요.",
      eyebrow: "아이디어 모드",
      slogan: "생각이 열리면, 일이 시작돼요",
      description: "떠오른 생각을 말하면 Lime이 실행 가능한 행동으로 바꿉니다.",
      status: "IDEA ONLINE",
    },
  ),
  "lime-dusk": localized(
    {
      brandSubtitle: "GOLDEN STAGE",
      tagline: "把每一个交付时刻都做成高光。",
      eyebrow: "黑金舞台",
      slogan: "灯光一亮，主场开工",
      description: "一句目标，Lime 帮你把作品推到聚光灯下。",
      status: "SPOTLIGHT ONLINE",
    },
    {
      brandSubtitle: "GOLDEN STAGE",
      tagline: "把每一個交付時刻都做成高光。",
      eyebrow: "黑金舞台",
      slogan: "燈光一亮，主場開工",
      description: "一句目標，Lime 幫你把作品推到聚光燈下。",
      status: "SPOTLIGHT ONLINE",
    },
    {
      brandSubtitle: "GOLDEN STAGE",
      tagline: "Make every delivery a headline moment.",
      eyebrow: "Golden stage",
      slogan: "Lights on. Make it yours.",
      description: "Give Lime the goal and bring the work into the spotlight.",
      status: "SPOTLIGHT ONLINE",
    },
    {
      brandSubtitle: "GOLDEN STAGE",
      tagline: "届ける瞬間を、すべてハイライトに。",
      eyebrow: "ブラックゴールド",
      slogan: "ライトが点けば、主役の出番",
      description: "目標をLimeに渡して、作品をスポットライトへ。",
      status: "SPOTLIGHT ONLINE",
    },
    {
      brandSubtitle: "GOLDEN STAGE",
      tagline: "모든 결과물을 빛나는 순간으로 만드세요.",
      eyebrow: "골든 스테이지",
      slogan: "조명이 켜지면, 무대가 시작돼요",
      description: "목표를 Lime에 맡기고 작업을 스포트라이트로 가져갑니다.",
      status: "SPOTLIGHT ONLINE",
    },
  ),
  "lime-minimal": localized(
    {
      brandSubtitle: "MINIMAL FUTURE",
      tagline: "把噪音收走，只留下下一步。",
      eyebrow: "极简未来",
      slogan: "少一点干扰，多一点完成",
      description: "说清楚目标，Lime 帮你把路径变短。",
      status: "FOCUS ONLINE",
    },
    {
      brandSubtitle: "MINIMAL FUTURE",
      tagline: "把噪音收走，只留下下一步。",
      eyebrow: "極簡未來",
      slogan: "少一點干擾，多一點完成",
      description: "說清楚目標，Lime 幫你把路徑變短。",
      status: "FOCUS ONLINE",
    },
    {
      brandSubtitle: "MINIMAL FUTURE",
      tagline: "Remove the noise. Keep the next step.",
      eyebrow: "Minimal future",
      slogan: "Less noise. More done.",
      description: "State the goal clearly and let Lime shorten the path.",
      status: "FOCUS ONLINE",
    },
    {
      brandSubtitle: "MINIMAL FUTURE",
      tagline: "ノイズを減らし、次の一歩だけを残す。",
      eyebrow: "ミニマルフューチャー",
      slogan: "ノイズを減らし、完了を増やす",
      description: "目標を明確にすれば、Limeが道筋を短くします。",
      status: "FOCUS ONLINE",
    },
    {
      brandSubtitle: "MINIMAL FUTURE",
      tagline: "잡음을 덜고 다음 단계만 남겨 보세요.",
      eyebrow: "미니멀 퓨처",
      slogan: "잡음은 줄이고, 완료는 늘리고",
      description: "목표를 분명히 말하면 Lime이 경로를 줄입니다.",
      status: "FOCUS ONLINE",
    },
  ),
  "lime-vivid": localized(
    {
      brandSubtitle: "VIVID STUDIO",
      tagline: "把灵感涂上颜色，直接开工。",
      eyebrow: "爆燃涂鸦",
      slogan: "先画出来，再把它做出来",
      description: "想法不用等完美，Lime 帮你一路改到能交付。",
      status: "VIVID ONLINE",
    },
    {
      brandSubtitle: "VIVID STUDIO",
      tagline: "把靈感塗上顏色，直接開工。",
      eyebrow: "爆燃塗鴉",
      slogan: "先畫出來，再把它做出來",
      description: "想法不用等完美，Lime 幫你一路改到能交付。",
      status: "VIVID ONLINE",
    },
    {
      brandSubtitle: "VIVID STUDIO",
      tagline: "Color the idea. Start the work.",
      eyebrow: "Vivid studio",
      slogan: "Sketch it. Ship it.",
      description:
        "Your idea does not need to be perfect before Lime helps you deliver it.",
      status: "VIVID ONLINE",
    },
    {
      brandSubtitle: "VIVID STUDIO",
      tagline: "ひらめきに色をつけて、すぐ始める。",
      eyebrow: "ビビッドスタジオ",
      slogan: "描いて、作って、届けよう",
      description: "完璧を待たず、Limeと一緒に届けられる形へ整えます。",
      status: "VIVID ONLINE",
    },
    {
      brandSubtitle: "VIVID STUDIO",
      tagline: "영감에 색을 입히고 바로 시작하세요.",
      eyebrow: "비비드 스튜디오",
      slogan: "그려 보고, 만들어 보내요",
      description:
        "완벽을 기다리지 않고 Lime과 함께 전달 가능한 결과로 다듬습니다.",
      status: "VIVID ONLINE",
    },
  ),
  "lime-literary": localized(
    {
      brandSubtitle: "CLEAR WINDOW",
      tagline: "让每一次创作都留一点自然光。",
      eyebrow: "清透少年",
      slogan: "有光的地方，思路会更清楚",
      description: "把目标说给 Lime，慢慢整理出漂亮而可靠的结果。",
      status: "CLEAR ONLINE",
    },
    {
      brandSubtitle: "CLEAR WINDOW",
      tagline: "讓每一次創作都留一點自然光。",
      eyebrow: "清透少年",
      slogan: "有光的地方，思路會更清楚",
      description: "把目標說給 Lime，慢慢整理出漂亮而可靠的結果。",
      status: "CLEAR ONLINE",
    },
    {
      brandSubtitle: "CLEAR WINDOW",
      tagline: "Leave a little daylight in every idea.",
      eyebrow: "Clear window",
      slogan: "Clear light. Clearer thinking.",
      description: "Give Lime the goal and shape a calm, reliable result.",
      status: "CLEAR ONLINE",
    },
    {
      brandSubtitle: "CLEAR WINDOW",
      tagline: "どの創作にも、少しの自然光を残す。",
      eyebrow: "クリアウィンドウ",
      slogan: "光があれば、考えはもっと澄む",
      description: "目標をLimeに渡し、きれいで確かな結果へ整えます。",
      status: "CLEAR ONLINE",
    },
    {
      brandSubtitle: "CLEAR WINDOW",
      tagline: "모든 창작에 자연광을 조금 남겨 보세요.",
      eyebrow: "클리어 윈도우",
      slogan: "빛이 있으면 생각도 맑아져요",
      description:
        "목표를 Lime에 맡기고 차분하고 믿을 수 있는 결과를 만듭니다.",
      status: "CLEAR ONLINE",
    },
  ),
  "lime-luxury": localized(
    {
      brandSubtitle: "MIDNIGHT LUXE",
      tagline: "让重要的想法在星夜里保持清醒。",
      eyebrow: "蓝紫星夜",
      slogan: "夜色越深，灵感越亮",
      description: "把目标交给 Lime，在安静的光里推进每个细节。",
      status: "NIGHT ONLINE",
    },
    {
      brandSubtitle: "MIDNIGHT LUXE",
      tagline: "讓重要的想法在星夜裡保持清醒。",
      eyebrow: "藍紫星夜",
      slogan: "夜色越深，靈感越亮",
      description: "把目標交給 Lime，在安靜的光裡推進每個細節。",
      status: "NIGHT ONLINE",
    },
    {
      brandSubtitle: "MIDNIGHT LUXE",
      tagline: "Keep important ideas bright after dark.",
      eyebrow: "Midnight luxe",
      slogan: "The darker the night, the brighter the idea.",
      description:
        "Give Lime the goal and refine every detail in a quiet glow.",
      status: "NIGHT ONLINE",
    },
    {
      brandSubtitle: "MIDNIGHT LUXE",
      tagline: "大切なアイデアを、星夜の中でも鮮やかに。",
      eyebrow: "ミッドナイトリュクス",
      slogan: "夜が深いほど、ひらめきは光る",
      description: "目標をLimeに渡し、静かな光の中で細部を進めます。",
      status: "NIGHT ONLINE",
    },
    {
      brandSubtitle: "MIDNIGHT LUXE",
      tagline: "중요한 아이디어를 밤에도 선명하게 유지하세요.",
      eyebrow: "미드나이트 럭스",
      slogan: "밤이 깊을수록 영감은 빛나요",
      description: "목표를 Lime에 맡기고 고요한 빛 속에서 세부를 다듬습니다.",
      status: "NIGHT ONLINE",
    },
  ),
  "lime-future": localized(
    {
      brandSubtitle: "RED FUTURE CITY",
      tagline: "把下一座城市，先从一个目标开始。",
      eyebrow: "红白未来城",
      slogan: "未来不等人，现在就发车",
      description: "说清楚目的地，Lime 帮你把路线铺开。",
      status: "CITY ONLINE",
    },
    {
      brandSubtitle: "RED FUTURE CITY",
      tagline: "把下一座城市，先從一個目標開始。",
      eyebrow: "紅白未來城",
      slogan: "未來不等人，現在就發車",
      description: "說清楚目的地，Lime 幫你把路線鋪開。",
      status: "CITY ONLINE",
    },
    {
      brandSubtitle: "RED FUTURE CITY",
      tagline: "Build the next city from one clear goal.",
      eyebrow: "Red future city",
      slogan: "The future is moving. Get on board.",
      description: "Name the destination and let Lime lay out the route.",
      status: "CITY ONLINE",
    },
    {
      brandSubtitle: "RED FUTURE CITY",
      tagline: "次の都市を、一つの明確な目標から始める。",
      eyebrow: "レッドフューチャー",
      slogan: "未来は待たない、今出発しよう",
      description: "目的地を伝えれば、Limeがルートを広げます。",
      status: "CITY ONLINE",
    },
    {
      brandSubtitle: "RED FUTURE CITY",
      tagline: "다음 도시를 하나의 분명한 목표에서 시작하세요.",
      eyebrow: "레드 퓨처 시티",
      slogan: "미래는 기다리지 않아요, 지금 출발해요",
      description: "목적지를 말하면 Lime이 경로를 펼칩니다.",
      status: "CITY ONLINE",
    },
  ),
};

export function getLimeSkinCopy(
  skinId: string | null | undefined,
  locale?: string | null,
): LimeSkinCopy {
  const resolvedSkinId = resolveLimeColorSchemeId(skinId);
  const skinCopy = SKIN_CONTENT[resolvedSkinId];
  const normalizedLocale = normalizeLocale(locale);
  return skinCopy[normalizedLocale] ?? skinCopy["zh-CN"];
}
