use serde::Serialize;

use super::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum AppServerMethodKind {
    Request,
    Notification,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct AppServerMethodSpec {
    pub method: &'static str,
    pub kind: AppServerMethodKind,
}

macro_rules! method {
    ($method:ident, $kind:ident) => {
        AppServerMethodSpec {
            method: $method,
            kind: AppServerMethodKind::$kind,
        }
    };
}

pub const APP_SERVER_METHODS: &[AppServerMethodSpec] = &[
    method!(METHOD_INITIALIZE, Request),
    method!(METHOD_INITIALIZED, Notification),
    method!(METHOD_CAPABILITY_LIST, Request),
    method!(METHOD_ARTIFACT_READ, Request),
    method!(METHOD_FILE_SYSTEM_LIST_DIRECTORY, Request),
    method!(METHOD_FILE_SYSTEM_READ_FILE_PREVIEW, Request),
    method!(METHOD_FILE_SYSTEM_CREATE_FILE, Request),
    method!(METHOD_FILE_SYSTEM_CREATE_DIRECTORY, Request),
    method!(METHOD_FILE_SYSTEM_RENAME_FILE, Request),
    method!(METHOD_FILE_SYSTEM_DELETE_FILE, Request),
    method!(METHOD_PROJECT_GIT_STATUS, Request),
    method!(METHOD_PROJECT_GIT_DIFF, Request),
    method!(METHOD_PROJECT_GIT_COMMITS_LIST, Request),
    method!(METHOD_PROJECT_GIT_BRANCH_CHECKOUT, Request),
    method!(METHOD_PROJECT_GIT_BRANCH_CREATE, Request),
    method!(METHOD_PROJECT_GIT_WORKTREE_CREATE, Request),
    method!(METHOD_PROJECT_SHELL_SESSION_START, Request),
    method!(METHOD_PROJECT_SHELL_SESSION_WRITE, Request),
    method!(METHOD_PROJECT_SHELL_SESSION_RESIZE, Request),
    method!(METHOD_PROJECT_SHELL_SESSION_KILL, Request),
    method!(METHOD_PROJECT_SHELL_SESSION_DRAIN_EVENTS, Request),
    method!(METHOD_EXECUTION_PROCESS_START, Request),
    method!(METHOD_EXECUTION_PROCESS_WRITE_STDIN, Request),
    method!(METHOD_EXECUTION_PROCESS_INTERRUPT, Request),
    method!(METHOD_EXECUTION_PROCESS_TERMINATE, Request),
    method!(METHOD_EXECUTION_PROCESS_STATUS, Request),
    method!(METHOD_EXECUTION_PROCESS_DRAIN_OUTPUT, Request),
    method!(METHOD_EVIDENCE_EXPORT, Request),
    method!(METHOD_AGENT_SESSION_HANDOFF_BUNDLE_EXPORT, Request),
    method!(METHOD_AGENT_SESSION_REPLAY_CASE_EXPORT, Request),
    method!(METHOD_AGENT_SESSION_ANALYSIS_HANDOFF_EXPORT, Request),
    method!(
        METHOD_AGENT_SESSION_REVIEW_DECISION_TEMPLATE_EXPORT,
        Request
    ),
    method!(METHOD_AGENT_SESSION_REVIEW_DECISION_SAVE, Request),
    method!(METHOD_AGENT_SESSION_LIST, Request),
    method!(METHOD_AGENT_SESSION_UPDATE, Request),
    method!(METHOD_AGENT_SESSION_ARCHIVE_MANY, Request),
    method!(METHOD_AGENT_SESSION_DELETE, Request),
    method!(METHOD_AGENT_SESSION_OBJECTIVE_READ, Request),
    method!(METHOD_AGENT_SESSION_OBJECTIVE_SET, Request),
    method!(METHOD_AGENT_SESSION_OBJECTIVE_STATUS_UPDATE, Request),
    method!(METHOD_AGENT_SESSION_OBJECTIVE_CLEAR, Request),
    method!(METHOD_AGENT_SESSION_OBJECTIVE_CONTINUE, Request),
    method!(METHOD_AGENT_SESSION_OBJECTIVE_AUDIT, Request),
    method!(METHOD_AGENT_SESSION_COMPACT, Request),
    method!(METHOD_AGENT_SESSION_THREAD_RESUME, Request),
    method!(METHOD_AGENT_SESSION_QUEUED_TURN_REMOVE, Request),
    method!(METHOD_AGENT_SESSION_QUEUED_TURN_PROMOTE, Request),
    method!(METHOD_AGENT_SESSION_FILE_CHECKPOINT_LIST, Request),
    method!(METHOD_AGENT_SESSION_FILE_CHECKPOINT_GET, Request),
    method!(METHOD_AGENT_SESSION_FILE_CHECKPOINT_DIFF, Request),
    method!(METHOD_AGENT_SESSION_FILE_CHECKPOINT_RESTORE, Request),
    method!(METHOD_AGENT_SESSION_TOOL_INVENTORY_READ, Request),
    method!(METHOD_SESSION_FILE_GET_OR_CREATE, Request),
    method!(METHOD_SESSION_FILE_UPDATE_META, Request),
    method!(METHOD_SESSION_FILE_SAVE, Request),
    method!(METHOD_SESSION_FILE_READ, Request),
    method!(METHOD_SESSION_FILE_RESOLVE_PATH, Request),
    method!(METHOD_SESSION_FILE_DELETE, Request),
    method!(METHOD_SESSION_FILE_LIST, Request),
    method!(METHOD_WORKSPACE_LIST, Request),
    method!(METHOD_WORKSPACE_READ, Request),
    method!(METHOD_WORKSPACE_UPDATE, Request),
    method!(METHOD_WORKSPACE_DELETE, Request),
    method!(METHOD_WORKSPACE_ENSURE, Request),
    method!(METHOD_WORKSPACE_BY_PATH_READ, Request),
    method!(METHOD_WORKSPACE_DEFAULT_READ, Request),
    method!(METHOD_WORKSPACE_DEFAULT_ENSURE, Request),
    method!(METHOD_WORKSPACE_PROJECTS_ROOT_READ, Request),
    method!(METHOD_WORKSPACE_PROJECT_PATH_RESOLVE, Request),
    method!(METHOD_WORKSPACE_ENSURE_READY, Request),
    method!(METHOD_SKILL_LIST, Request),
    method!(METHOD_SKILL_READ, Request),
    method!(METHOD_SKILL_MANAGEMENT_LIST, Request),
    method!(METHOD_SKILL_MANAGEMENT_INSTALL, Request),
    method!(METHOD_SKILL_MANAGEMENT_UNINSTALL, Request),
    method!(METHOD_SKILL_REPOSITORY_LIST, Request),
    method!(METHOD_SKILL_REPOSITORY_SAVE, Request),
    method!(METHOD_SKILL_REPOSITORY_DELETE, Request),
    method!(METHOD_SKILL_CACHE_REFRESH, Request),
    method!(METHOD_SKILL_INSTALLED_DIRECTORIES_LIST, Request),
    method!(METHOD_SKILL_LOCAL_INSPECT, Request),
    method!(METHOD_SKILL_LOCAL_DETAIL_INSPECT, Request),
    method!(METHOD_SKILL_LOCAL_SCAFFOLD_CREATE, Request),
    method!(METHOD_SKILL_LOCAL_IMPORT, Request),
    method!(METHOD_SKILL_LOCAL_RENAME, Request),
    method!(METHOD_SKILL_REMOTE_INSPECT, Request),
    method!(METHOD_SKILL_PACKAGE_LOCAL_INSPECT, Request),
    method!(METHOD_SKILL_PACKAGE_LOCAL_INSTALL, Request),
    method!(METHOD_SKILL_PACKAGE_LOCAL_REPLACE, Request),
    method!(METHOD_SKILL_PACKAGE_EXPORT, Request),
    method!(METHOD_SKILL_MARKETPLACE_INSTALL, Request),
    method!(METHOD_SKILL_PACKAGE_DOWNLOAD_INSTALL, Request),
    method!(METHOD_GATEWAY_CHANNEL_START, Request),
    method!(METHOD_GATEWAY_CHANNEL_STOP, Request),
    method!(METHOD_GATEWAY_CHANNEL_STATUS, Request),
    method!(METHOD_TELEGRAM_CHANNEL_PROBE, Request),
    method!(METHOD_FEISHU_CHANNEL_PROBE, Request),
    method!(METHOD_DISCORD_CHANNEL_PROBE, Request),
    method!(METHOD_WECHAT_CHANNEL_PROBE, Request),
    method!(METHOD_WECHAT_CHANNEL_LOGIN_START, Request),
    method!(METHOD_WECHAT_CHANNEL_LOGIN_WAIT, Request),
    method!(METHOD_WECHAT_CHANNEL_ACCOUNT_LIST, Request),
    method!(METHOD_WECHAT_CHANNEL_ACCOUNT_REMOVE, Request),
    method!(METHOD_WECHAT_CHANNEL_RUNTIME_MODEL_SET, Request),
    method!(METHOD_GATEWAY_TUNNEL_PROBE, Request),
    method!(METHOD_GATEWAY_TUNNEL_CLOUDFLARED_DETECT, Request),
    method!(METHOD_GATEWAY_TUNNEL_CLOUDFLARED_INSTALL, Request),
    method!(METHOD_GATEWAY_TUNNEL_CREATE, Request),
    method!(METHOD_GATEWAY_TUNNEL_START, Request),
    method!(METHOD_GATEWAY_TUNNEL_STOP, Request),
    method!(METHOD_GATEWAY_TUNNEL_RESTART, Request),
    method!(METHOD_GATEWAY_TUNNEL_STATUS, Request),
    method!(METHOD_GATEWAY_TUNNEL_SYNC_WEBHOOK_URL, Request),
    method!(METHOD_MEDIA_TASK_ARTIFACT_IMAGE_CREATE, Request),
    method!(METHOD_MEDIA_TASK_ARTIFACT_AUDIO_CREATE, Request),
    method!(METHOD_MEDIA_TASK_ARTIFACT_VIDEO_CREATE, Request),
    method!(METHOD_MEDIA_TASK_ARTIFACT_IMAGE_COMPLETE, Request),
    method!(METHOD_MEDIA_TASK_ARTIFACT_AUDIO_COMPLETE, Request),
    method!(METHOD_MEDIA_TASK_ARTIFACT_GET, Request),
    method!(METHOD_MEDIA_TASK_ARTIFACT_LIST, Request),
    method!(METHOD_MEDIA_TASK_ARTIFACT_CANCEL, Request),
    method!(METHOD_GALLERY_MATERIAL_GET, Request),
    method!(METHOD_GALLERY_MATERIAL_METADATA_CREATE, Request),
    method!(METHOD_GALLERY_MATERIAL_METADATA_GET, Request),
    method!(METHOD_GALLERY_MATERIAL_METADATA_UPDATE, Request),
    method!(METHOD_GALLERY_MATERIAL_METADATA_DELETE, Request),
    method!(METHOD_GALLERY_MATERIAL_LIST_BY_IMAGE_CATEGORY, Request),
    method!(METHOD_GALLERY_MATERIAL_LIST_BY_LAYOUT_CATEGORY, Request),
    method!(METHOD_GALLERY_MATERIAL_LIST_BY_MOOD, Request),
    method!(METHOD_PROJECT_MATERIAL_LIST, Request),
    method!(METHOD_PROJECT_MATERIAL_GET, Request),
    method!(METHOD_PROJECT_MATERIAL_COUNT, Request),
    method!(METHOD_PROJECT_MATERIAL_UPLOAD, Request),
    method!(METHOD_PROJECT_MATERIAL_IMPORT_FROM_URL, Request),
    method!(METHOD_PROJECT_MATERIAL_UPDATE, Request),
    method!(METHOD_PROJECT_MATERIAL_DELETE, Request),
    method!(METHOD_PROJECT_MATERIAL_CONTENT, Request),
    method!(METHOD_VOICE_ASR_CREDENTIAL_LIST, Request),
    method!(METHOD_VOICE_ASR_CREDENTIAL_CREATE, Request),
    method!(METHOD_VOICE_ASR_CREDENTIAL_UPDATE, Request),
    method!(METHOD_VOICE_ASR_CREDENTIAL_DELETE, Request),
    method!(METHOD_VOICE_ASR_CREDENTIAL_DEFAULT_SET, Request),
    method!(METHOD_VOICE_ASR_CREDENTIAL_TEST, Request),
    method!(METHOD_VOICE_INSTRUCTION_LIST, Request),
    method!(METHOD_VOICE_INSTRUCTION_SAVE, Request),
    method!(METHOD_VOICE_INSTRUCTION_DELETE, Request),
    method!(METHOD_VOICE_MODEL_DEFAULT_SET, Request),
    method!(METHOD_VOICE_MODEL_TEST_TRANSCRIBE_FILE, Request),
    method!(METHOD_WORKSPACE_SKILL_BINDINGS_LIST, Request),
    method!(METHOD_WORKSPACE_REGISTERED_SKILLS_LIST, Request),
    method!(METHOD_WORKSPACE_RIGHT_SURFACE_REQUEST, Request),
    method!(METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_LIST, Request),
    method!(METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_CONSUME, Request),
    method!(METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_DISMISS, Request),
    method!(METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_CHANGED, Notification),
    method!(METHOD_BROWSER_SESSION_TARGET_LIST, Request),
    method!(METHOD_BROWSER_SESSION_OPEN, Request),
    method!(METHOD_BROWSER_SESSION_READ, Request),
    method!(METHOD_BROWSER_SESSION_CLOSE, Request),
    method!(METHOD_BROWSER_SESSION_EVENT_LIST, Request),
    method!(METHOD_BROWSER_SESSION_ACTION_EXECUTE, Request),
    method!(METHOD_PLUGIN_LOCAL_PACKAGE_INSPECT, Request),
    method!(METHOD_PLUGIN_PACKAGE_FETCH_CLOUD, Request),
    method!(METHOD_PLUGIN_INSTALLED_SAVE, Request),
    method!(METHOD_PLUGIN_INSTALLED_LIST, Request),
    method!(METHOD_PLUGIN_INSTALLED_DISABLED_SET, Request),
    method!(METHOD_PLUGIN_INSTALLED_UNINSTALL_REHEARSAL, Request),
    method!(METHOD_PLUGIN_INSTALLED_UNINSTALL, Request),
    method!(METHOD_PLUGIN_HOST_LIFECYCLE_LIST, Request),
    method!(METHOD_PLUGIN_SHELL_PREPARE, Request),
    method!(METHOD_PLUGIN_UI_RUNTIME_START, Request),
    method!(METHOD_PLUGIN_UI_RUNTIME_STATUS, Request),
    method!(METHOD_PLUGIN_UI_RUNTIME_STOP, Request),
    method!(METHOD_KNOWLEDGE_PACK_LIST, Request),
    method!(METHOD_KNOWLEDGE_PACK_READ, Request),
    method!(METHOD_KNOWLEDGE_SOURCE_IMPORT, Request),
    method!(METHOD_KNOWLEDGE_PACK_COMPILE, Request),
    method!(METHOD_KNOWLEDGE_PACK_DEFAULT_SET, Request),
    method!(METHOD_KNOWLEDGE_PACK_STATUS_UPDATE, Request),
    method!(METHOD_KNOWLEDGE_CONTEXT_RESOLVE, Request),
    method!(METHOD_KNOWLEDGE_CONTEXT_RUN_VALIDATE, Request),
    method!(METHOD_AUTOMATION_SCHEDULER_CONFIG_READ, Request),
    method!(METHOD_AUTOMATION_SCHEDULER_CONFIG_UPDATE, Request),
    method!(METHOD_AUTOMATION_SCHEDULER_STATUS, Request),
    method!(METHOD_AUTOMATION_JOB_LIST, Request),
    method!(METHOD_AUTOMATION_JOB_READ, Request),
    method!(METHOD_AUTOMATION_JOB_CREATE, Request),
    method!(METHOD_AUTOMATION_JOB_UPDATE, Request),
    method!(METHOD_AUTOMATION_JOB_DELETE, Request),
    method!(METHOD_AUTOMATION_JOB_RUN_NOW, Request),
    method!(METHOD_AUTOMATION_JOB_HEALTH, Request),
    method!(METHOD_AUTOMATION_JOB_RUN_HISTORY, Request),
    method!(METHOD_AUTOMATION_SCHEDULE_PREVIEW, Request),
    method!(METHOD_AUTOMATION_SCHEDULE_VALIDATE, Request),
    method!(METHOD_MCP_SERVER_LIST, Request),
    method!(METHOD_MCP_SERVER_STATUS_LIST, Request),
    method!(METHOD_MCP_SERVER_CREATE, Request),
    method!(METHOD_MCP_SERVER_UPDATE, Request),
    method!(METHOD_MCP_SERVER_DELETE, Request),
    method!(METHOD_MCP_SERVER_ENABLED_SET, Request),
    method!(METHOD_MCP_SERVER_IMPORT_FROM_APP, Request),
    method!(METHOD_MCP_SERVER_SYNC_ALL_TO_LIVE, Request),
    method!(METHOD_MCP_SERVER_OAUTH_LOGIN, Request),
    method!(METHOD_MCP_SERVER_START, Request),
    method!(METHOD_MCP_SERVER_STOP, Request),
    method!(METHOD_MCP_TOOL_LIST, Request),
    method!(METHOD_MCP_TOOL_LIST_FOR_CONTEXT, Request),
    method!(METHOD_MCP_TOOL_SEARCH, Request),
    method!(METHOD_MCP_TOOL_CALL, Request),
    method!(METHOD_MCP_TOOL_CALL_WITH_CALLER, Request),
    method!(METHOD_MCP_PROMPT_LIST, Request),
    method!(METHOD_MCP_PROMPT_GET, Request),
    method!(METHOD_MCP_RESOURCE_LIST, Request),
    method!(METHOD_MCP_RESOURCE_READ, Request),
    method!(METHOD_MCP_RESOURCE_SUBSCRIBE, Request),
    method!(METHOD_MCP_RESOURCE_UNSUBSCRIBE, Request),
    method!(METHOD_PROJECT_MEMORY_READ, Request),
    method!(METHOD_MEMORY_STORE_LIST, Request),
    method!(METHOD_MEMORY_STORE_READ, Request),
    method!(METHOD_MEMORY_STORE_SEARCH, Request),
    method!(METHOD_MEMORY_STORE_ADD_NOTE, Request),
    method!(METHOD_MEMORY_STORE_CONSOLIDATE, Request),
    method!(METHOD_MEMORY_STORE_REVIEW_LIST, Request),
    method!(METHOD_MEMORY_STORE_REVIEW_RESOLVE, Request),
    method!(METHOD_MEMORY_STORE_HEALTH, Request),
    method!(METHOD_MEMORY_STORE_RESET, Request),
    method!(METHOD_MEMORY_STORE_INDEX_REBUILD, Request),
    method!(METHOD_LOG_LIST, Request),
    method!(METHOD_LOG_PERSISTED_TAIL, Request),
    method!(METHOD_LOG_CLEAR, Request),
    method!(METHOD_LOG_DIAGNOSTIC_HISTORY_CLEAR, Request),
    method!(METHOD_DIAGNOSTICS_LOG_STORAGE_READ, Request),
    method!(METHOD_DIAGNOSTICS_SUPPORT_BUNDLE_EXPORT, Request),
    method!(METHOD_DIAGNOSTICS_SERVER_READ, Request),
    method!(METHOD_DIAGNOSTICS_WINDOWS_STARTUP_READ, Request),
    method!(METHOD_DIAGNOSTICS_TRACE_LIST, Request),
    method!(METHOD_DIAGNOSTICS_TRACE_READ, Request),
    method!(METHOD_DIAGNOSTICS_TRACE_EXPORT, Request),
    method!(METHOD_USAGE_STATS_READ, Request),
    method!(METHOD_USAGE_STATS_MODEL_RANKING_LIST, Request),
    method!(METHOD_USAGE_STATS_DAILY_TRENDS_LIST, Request),
    method!(METHOD_MODEL_LIST, Request),
    method!(METHOD_MODEL_PREFERENCES_LIST, Request),
    method!(METHOD_MODEL_SYNC_STATE_READ, Request),
    method!(METHOD_MODEL_PROVIDER_LIST, Request),
    method!(METHOD_MODEL_PROVIDER_CATALOG_LIST, Request),
    method!(METHOD_MODEL_PROVIDER_READ, Request),
    method!(METHOD_MODEL_PROVIDER_CREATE, Request),
    method!(METHOD_MODEL_PROVIDER_UPDATE, Request),
    method!(METHOD_MODEL_PROVIDER_DELETE, Request),
    method!(METHOD_MODEL_PROVIDER_SORT_ORDERS_UPDATE, Request),
    method!(METHOD_MODEL_PROVIDER_CONFIG_EXPORT, Request),
    method!(METHOD_MODEL_PROVIDER_CONFIG_IMPORT, Request),
    method!(METHOD_MODEL_PROVIDER_TEST_CONNECTION, Request),
    method!(METHOD_MODEL_PROVIDER_TEST_CHAT, Request),
    method!(METHOD_MODEL_PROVIDER_FETCH_MODELS, Request),
    method!(METHOD_MODEL_PROVIDER_KEY_CREATE, Request),
    method!(METHOD_MODEL_PROVIDER_KEY_UPDATE, Request),
    method!(METHOD_MODEL_PROVIDER_KEY_DELETE, Request),
    method!(METHOD_MODEL_PROVIDER_KEY_NEXT, Request),
    method!(METHOD_MODEL_PROVIDER_KEY_USAGE_RECORD, Request),
    method!(METHOD_MODEL_PROVIDER_KEY_ERROR_RECORD, Request),
    method!(METHOD_MODEL_PROVIDER_UI_STATE_READ, Request),
    method!(METHOD_MODEL_PROVIDER_UI_STATE_WRITE, Request),
    method!(METHOD_MODEL_PROVIDER_ALIAS_READ, Request),
    method!(METHOD_MODEL_PROVIDER_ALIAS_LIST, Request),
    method!(METHOD_CONNECT_DEEP_LINK_RESOLVE, Request),
    method!(METHOD_CONNECT_OPEN_DEEP_LINK_RESOLVE, Request),
    method!(METHOD_CONNECT_RELAY_API_KEY_SAVE, Request),
    method!(METHOD_CONNECT_CALLBACK_SEND, Request),
    method!(METHOD_CONVERSATION_IMPORT_SOURCE_SCAN, Request),
    method!(METHOD_CONVERSATION_IMPORT_THREAD_PREVIEW, Request),
    method!(METHOD_CONVERSATION_IMPORT_THREAD_COMMIT, Request),
    method!(
        METHOD_CONVERSATION_IMPORT_THREAD_RUNTIME_EVENTS_READ,
        Request
    ),
    method!(METHOD_AGENT_SESSION_START, Request),
    method!(METHOD_AGENT_SESSION_READ, Request),
    method!(METHOD_AGENT_SESSION_TURN_START, Request),
    method!(METHOD_AGENT_SESSION_TURN_CANCEL, Request),
    method!(METHOD_AGENT_SESSION_ACTION_REPLAY, Request),
    method!(METHOD_AGENT_SESSION_ACTION_RESPOND, Request),
    method!(METHOD_AGENT_SESSION_RUNTIME_EVENTS_APPEND, Request),
    method!(METHOD_WORKFLOW_READ, Request),
    method!(METHOD_AGENT_SESSION_EVENT, Notification),
];

pub fn is_app_server_request_method(method: &str) -> bool {
    APP_SERVER_METHODS
        .iter()
        .any(|spec| spec.kind == AppServerMethodKind::Request && spec.method == method)
}

pub fn is_app_server_notification_method(method: &str) -> bool {
    APP_SERVER_METHODS
        .iter()
        .any(|spec| spec.kind == AppServerMethodKind::Notification && spec.method == method)
}
