import {
  Code2,
  Edit3,
  Eye,
  FilePlus,
  FileText,
  FolderOpen,
  Globe,
  Search,
  Settings,
  Terminal,
  Wrench,
} from "lucide-react";
import type { ToolDisplayConfig } from "../toolDisplayTypes";

export const CORE_EXACT_TOOL_CONFIGS = [
  [
    "read",
    {
      family: "read",
      label: "文件读取",
      verb: "查看",
      icon: Eye,
      groupTitle: "探索",
      actionKey: "read",
    },
  ],
  [
    "readfile",
    {
      family: "read",
      label: "文件读取",
      verb: "查看",
      icon: Eye,
      groupTitle: "探索",
      actionKey: "read",
    },
  ],
  [
    "readdocs",
    {
      family: "read",
      label: "文档读取",
      verb: "查看",
      icon: FileText,
      groupTitle: "探索",
      actionKey: "read",
    },
  ],
  [
    "readmcpresource",
    {
      family: "read",
      label: "资源读取",
      verb: "查看",
      icon: FileText,
      groupTitle: "探索",
      actionKey: "read",
    },
  ],
  [
    "write",
    {
      family: "write",
      label: "文件写入",
      verb: "保存",
      icon: FilePlus,
      groupTitle: "写入",
      actionKey: "write",
    },
  ],
  [
    "writefile",
    {
      family: "write",
      label: "文件写入",
      verb: "保存",
      icon: FilePlus,
      groupTitle: "写入",
      actionKey: "write",
    },
  ],
  [
    "createfile",
    {
      family: "write",
      label: "文件创建",
      verb: "保存",
      icon: FilePlus,
      groupTitle: "写入",
      actionKey: "write",
    },
  ],
  [
    "edit",
    {
      family: "edit",
      label: "文件编辑",
      verb: "修改",
      icon: Edit3,
      groupTitle: "编辑",
      actionKey: "edit",
    },
  ],
  [
    "editfile",
    {
      family: "edit",
      label: "文件编辑",
      verb: "修改",
      icon: Edit3,
      groupTitle: "编辑",
      actionKey: "edit",
    },
  ],
  [
    "multiedit",
    {
      family: "edit",
      label: "批量编辑",
      verb: "批量修改",
      icon: Edit3,
      groupTitle: "编辑",
      actionKey: "edit",
    },
  ],
  [
    "notebookedit",
    {
      family: "edit",
      label: "笔记本编辑",
      verb: "修改",
      icon: Edit3,
      groupTitle: "编辑",
      actionKey: "edit",
    },
  ],
  [
    "applypatch",
    {
      family: "edit",
      label: "补丁应用",
      verb: "应用",
      icon: Edit3,
      groupTitle: "编辑",
      actionKey: "edit",
    },
  ],
  [
    "glob",
    {
      family: "list",
      label: "文件匹配",
      verb: "查找",
      icon: FolderOpen,
      groupTitle: "探索",
      actionKey: "list",
      actions: {
        failed: "查找失败",
        completed: "已找到",
        running: "查找中",
      },
    },
  ],
  [
    "ls",
    {
      family: "list",
      label: "目录浏览",
      verb: "查看",
      icon: FolderOpen,
      groupTitle: "探索",
      actionKey: "list",
    },
  ],
  [
    "list",
    {
      family: "list",
      label: "目录浏览",
      verb: "查看",
      icon: FolderOpen,
      groupTitle: "探索",
      actionKey: "list",
    },
  ],
  [
    "listdir",
    {
      family: "list",
      label: "目录浏览",
      verb: "查看",
      icon: FolderOpen,
      groupTitle: "探索",
      actionKey: "list",
    },
  ],
  [
    "listdirectory",
    {
      family: "list",
      label: "目录浏览",
      verb: "查看",
      icon: FolderOpen,
      groupTitle: "探索",
      actionKey: "list",
    },
  ],
  [
    "listmcpresources",
    {
      family: "list",
      label: "资源列表",
      verb: "查看",
      icon: FolderOpen,
      groupTitle: "探索",
      actionKey: "list",
    },
  ],
  [
    "listmcpresourcetemplates",
    {
      family: "list",
      label: "资源模板列表",
      verb: "查看",
      icon: FolderOpen,
      groupTitle: "探索",
      actionKey: "list",
    },
  ],
  [
    "mcp",
    {
      family: "generic",
      label: "MCP 工具",
      verb: "调用",
      icon: Wrench,
      groupTitle: "MCP",
      actionKey: "generic",
      actions: {
        failed: "调用失败",
        completed: "已调用 MCP 工具",
        running: "调用中",
      },
    },
  ],
  [
    "mcpauth",
    {
      family: "generic",
      label: "MCP 授权",
      verb: "授权",
      icon: Wrench,
      groupTitle: "MCP",
      actionKey: "generic",
      actions: {
        failed: "授权失败",
        completed: "已完成 MCP 授权",
        running: "授权中",
      },
    },
  ],
  [
    "repl",
    {
      family: "command",
      label: "REPL 执行",
      verb: "运行",
      icon: Terminal,
      groupTitle: "命令",
      actionKey: "command",
    },
  ],
  [
    "grep",
    {
      family: "search",
      label: "内容检索",
      verb: "搜索",
      icon: Search,
      groupTitle: "探索",
      actionKey: "search",
    },
  ],
  [
    "websearch",
    {
      family: "search",
      label: "网络搜索",
      verb: "搜索",
      icon: Search,
      groupTitle: "搜索",
      actionKey: "search",
    },
  ],
  [
    "searchquery",
    {
      family: "search",
      label: "网络搜索",
      verb: "搜索",
      icon: Search,
      groupTitle: "搜索",
      actionKey: "search",
    },
  ],
  [
    "imagequery",
    {
      family: "search",
      label: "图片搜索",
      verb: "搜索",
      icon: Search,
      groupTitle: "搜索",
      actionKey: "search",
    },
  ],
  [
    "limesearchwebimages",
    {
      family: "search",
      label: "联网搜图",
      verb: "搜索",
      icon: Search,
      groupTitle: "搜索",
      actionKey: "search",
    },
  ],
  [
    "toolsearch",
    {
      family: "search",
      label: "工具入口确认",
      verb: "确认",
      icon: Search,
      groupTitle: "工具入口",
      actionKey: "search",
    },
  ],
  [
    "searchdocs",
    {
      family: "search",
      label: "文档搜索",
      verb: "搜索",
      icon: Search,
      groupTitle: "搜索",
      actionKey: "search",
    },
  ],
  [
    "resolvelibraryid",
    {
      family: "search",
      label: "库解析",
      verb: "解析",
      icon: Search,
      groupTitle: "搜索",
      actionKey: "search",
    },
  ],
  [
    "querydocs",
    {
      family: "read",
      label: "文档查询",
      verb: "查询",
      icon: FileText,
      groupTitle: "探索",
      actionKey: "read",
    },
  ],
  [
    "webfetch",
    {
      family: "fetch",
      label: "网页抓取",
      verb: "抓取",
      icon: Globe,
      groupTitle: "获取",
      actionKey: "fetch",
    },
  ],
  [
    "finance",
    {
      family: "fetch",
      label: "行情查询",
      verb: "查询",
      icon: Globe,
      groupTitle: "获取",
      actionKey: "fetch",
    },
  ],
  [
    "weather",
    {
      family: "fetch",
      label: "天气查询",
      verb: "查询",
      icon: Globe,
      groupTitle: "获取",
      actionKey: "fetch",
    },
  ],
  [
    "sports",
    {
      family: "fetch",
      label: "体育查询",
      verb: "查询",
      icon: Globe,
      groupTitle: "获取",
      actionKey: "fetch",
    },
  ],
  [
    "time",
    {
      family: "fetch",
      label: "时间查询",
      verb: "查询",
      icon: Globe,
      groupTitle: "获取",
      actionKey: "fetch",
    },
  ],
  [
    "bash",
    {
      family: "command",
      label: "命令执行",
      verb: "运行",
      icon: Terminal,
      groupTitle: "命令",
      actionKey: "command",
    },
  ],
  [
    "killshell",
    {
      family: "command",
      label: "终止命令",
      verb: "终止",
      icon: Terminal,
      groupTitle: "命令",
      actionKey: "command",
    },
  ],
  [
    "lsp",
    {
      family: "read",
      label: "代码分析",
      verb: "分析",
      icon: Code2,
      groupTitle: "探索",
      actionKey: "read",
    },
  ],
  [
    "config",
    {
      family: "generic",
      label: "运行配置",
      verb: "调整",
      icon: Settings,
      groupTitle: "配置",
      actionKey: "generic",
      actions: {
        failed: "调整失败",
        completed: "已调整配置",
        running: "调整中",
      },
    },
  ],
  [
    "workflow",
    {
      family: "generic",
      label: "工作流执行",
      verb: "执行",
      icon: Settings,
      groupTitle: "工作流",
      actionKey: "generic",
      actions: {
        failed: "执行失败",
        completed: "已执行工作流",
        running: "执行中",
      },
    },
  ],
  [
    "sleep",
    {
      family: "generic",
      label: "等待",
      verb: "等待",
      icon: Settings,
      groupTitle: "执行",
      actionKey: "generic",
      actions: {
        failed: "等待失败",
        completed: "已完成等待",
        running: "等待中",
      },
    },
  ],
  [
    "powershell",
    {
      family: "command",
      label: "PowerShell",
      verb: "运行",
      icon: Terminal,
      groupTitle: "命令",
      actionKey: "command",
    },
  ],
  [
    "skill",
    {
      family: "skill",
      label: "技能执行",
      verb: "执行技能",
      icon: Settings,
      groupTitle: "技能",
      actionKey: "skill",
    },
  ],
  [
    "listskills",
    {
      family: "skill",
      label: "技能列表",
      verb: "列出",
      icon: Settings,
      groupTitle: "技能",
      actionKey: "skill",
      actions: {
        failed: "获取失败",
        completed: "已获取技能列表",
        running: "获取中",
      },
    },
  ],
  [
    "loadskill",
    {
      family: "skill",
      label: "技能加载",
      verb: "加载",
      icon: Settings,
      groupTitle: "技能",
      actionKey: "skill",
      actions: {
        failed: "加载失败",
        completed: "已加载技能",
        running: "加载中",
      },
    },
  ],
  [
    "taskcreate",
    {
      family: "plan",
      label: "开始这一步",
      verb: "开始",
      icon: FilePlus,
      groupTitle: "计划",
      actionKey: "plan",
      actions: {
        failed: "开始失败",
        completed: "已开始",
        running: "开始中",
      },
    },
  ],
  [
    "tasklist",
    {
      family: "plan",
      label: "任务列表",
      verb: "查看",
      icon: FileText,
      groupTitle: "计划",
      actionKey: "plan",
      actions: {
        failed: "获取失败",
        completed: "已获取任务列表",
        running: "获取中",
      },
    },
  ],
  [
    "taskget",
    {
      family: "plan",
      label: "任务详情",
      verb: "查看",
      icon: FileText,
      groupTitle: "计划",
      actionKey: "plan",
      actions: {
        failed: "获取失败",
        completed: "已获取任务详情",
        running: "获取中",
      },
    },
  ],
  [
    "taskupdate",
    {
      family: "plan",
      label: "任务更新",
      verb: "更新",
      icon: Edit3,
      groupTitle: "计划",
      actionKey: "plan",
      actions: {
        failed: "更新失败",
        completed: "已更新任务",
        running: "更新中",
      },
    },
  ],
  [
    "updateplan",
    {
      family: "plan",
      label: "计划更新",
      verb: "更新",
      icon: Edit3,
      groupTitle: "计划",
      actionKey: "plan",
      actions: {
        failed: "更新失败",
        completed: "已更新计划",
        running: "更新中",
      },
    },
  ],
  [
    "taskoutput",
    {
      family: "task",
      label: "任务输出",
      verb: "查看结果",
      icon: FileText,
      groupTitle: "任务",
      actionKey: "task",
      actions: {
        failed: "查看结果失败",
        completed: "已查看结果",
        running: "查看结果中",
      },
    },
  ],
  [
    "taskstop",
    {
      family: "task",
      label: "终止任务",
      verb: "终止",
      icon: Terminal,
      groupTitle: "任务",
      actionKey: "task",
      actions: {
        failed: "终止失败",
        completed: "已终止任务",
        running: "终止中",
      },
    },
  ],
  [
    "enterplanmode",
    {
      family: "plan",
      label: "进入计划模式",
      verb: "进入",
      icon: FileText,
      groupTitle: "计划",
      actionKey: "plan",
    },
  ],
  [
    "exitplanmode",
    {
      family: "plan",
      label: "退出计划模式",
      verb: "退出",
      icon: FileText,
      groupTitle: "计划",
      actionKey: "plan",
    },
  ],
  [
    "enterworktree",
    {
      family: "generic",
      label: "进入工作树",
      verb: "进入",
      icon: FolderOpen,
      groupTitle: "工作树",
      actionKey: "generic",
      actions: {
        failed: "进入失败",
        completed: "已进入工作树",
        running: "进入中",
      },
    },
  ],
  [
    "exitworktree",
    {
      family: "generic",
      label: "退出工作树",
      verb: "退出",
      icon: FolderOpen,
      groupTitle: "工作树",
      actionKey: "generic",
      actions: {
        failed: "退出失败",
        completed: "已退出工作树",
        running: "退出中",
      },
    },
  ],
  [
    "analyzeimage",
    {
      family: "vision",
      label: "图像分析",
      verb: "分析",
      icon: Eye,
      groupTitle: "图像",
      actionKey: "vision",
    },
  ],
  [
    "viewimage",
    {
      family: "vision",
      label: "图片查看",
      verb: "查看",
      icon: Eye,
      groupTitle: "图像",
      actionKey: "vision",
      actions: {
        failed: "查看失败",
        completed: "已查看图片",
        running: "查看中",
      },
    },
  ],
] as const satisfies ReadonlyArray<readonly [string, ToolDisplayConfig]>;
