export const CONVERSATION_CONTENT_TARGET_WIDTH = "clamp(900px, 76%, 1280px)";

export const CONVERSATION_CONTENT_MAX_WIDTH =
  `min(100%, ${CONVERSATION_CONTENT_TARGET_WIDTH})`;

export const INLINE_CONVERSATION_CONTENT_WIDTH = `min(calc(100% - 20px), ${CONVERSATION_CONTENT_MAX_WIDTH})`;

export const FLOATING_CONVERSATION_CONTENT_WIDTH = `min(calc(100% - 16px), ${CONVERSATION_CONTENT_MAX_WIDTH})`;
