export {
  containsRuntimeAttachmentPlaceholder as containsInternalImagePlaceholder,
  isOnlyRuntimeAttachmentPlaceholderText as isOnlyInternalImagePlaceholderText,
  replaceRuntimeAttachmentPlaceholders as replaceInternalImagePlaceholders,
  resolveRuntimeAttachmentTaskDisplayName as resolveInternalImageTaskDisplayName,
} from "./runtimeAttachmentPlaceholder";
