import {
  resolveAgentChatCopy,
  resolveRequiredAgentChatCopy,
} from "./agentChatCopy";

type ToolStatusActionFamily =
  | "subagent"
  | "task"
  | "plan"
  | "skill"
  | "write"
  | "read"
  | "edit"
  | "command"
  | "search"
  | "list"
  | "browser"
  | "fetch"
  | "vision"
  | "generic";

type ToolStatusActionStatus = "failed" | "completed" | "running";

export type ToolStatusActionKey = ToolStatusActionFamily;

const TOOL_DISPLAY_LABEL_KEYS: Record<string, string> = {
  文件读取: "toolCall.label.fileRead",
  文档读取: "toolCall.label.documentRead",
  资源读取: "toolCall.label.resourceRead",
  文件写入: "toolCall.label.fileWrite",
  文件创建: "toolCall.label.fileCreate",
  文件编辑: "toolCall.label.fileEdit",
  批量编辑: "toolCall.label.multiEdit",
  笔记本编辑: "toolCall.label.notebookEdit",
  补丁应用: "toolCall.label.patchApply",
  文件匹配: "toolCall.label.fileMatch",
  目录浏览: "toolCall.label.directoryBrowse",
  资源列表: "toolCall.label.resourceList",
  资源模板列表: "toolCall.label.resourceTemplateList",
  "MCP 工具": "toolCall.label.mcpTool",
  "MCP 授权": "toolCall.label.mcpAuth",
  "REPL 执行": "toolCall.label.repl",
  内容检索: "toolCall.label.contentSearch",
  网络搜索: "toolCall.label.webSearch",
  图片搜索: "toolCall.label.imageSearch",
  联网搜图: "toolCall.label.webImageSearch",
  工具入口确认: "toolCall.label.toolEntry",
  文档搜索: "toolCall.label.documentSearch",
  库解析: "toolCall.label.libraryResolve",
  文档查询: "toolCall.label.documentQuery",
  网页抓取: "toolCall.label.webFetch",
  行情查询: "toolCall.label.marketData",
  天气查询: "toolCall.label.weather",
  体育查询: "toolCall.label.sports",
  时间查询: "toolCall.label.time",
  命令执行: "toolCall.label.command",
  终止命令: "toolCall.label.killCommand",
  代码分析: "toolCall.label.codeAnalysis",
  运行配置: "toolCall.label.config",
  工作流执行: "toolCall.label.workflow",
  等待: "toolCall.label.wait",
  PowerShell: "toolCall.label.powershell",
  技能执行: "toolCall.label.skillRun",
  技能列表: "toolCall.label.skillList",
  技能加载: "toolCall.label.skillLoad",
  开始这一步: "toolCall.label.taskCreate",
  任务列表: "toolCall.label.taskList",
  任务详情: "toolCall.label.taskDetail",
  任务更新: "toolCall.label.taskUpdate",
  计划更新: "toolCall.label.planUpdate",
  任务输出: "toolCall.label.taskOutput",
  终止任务: "toolCall.label.taskStop",
  进入计划模式: "toolCall.label.enterPlanMode",
  退出计划模式: "toolCall.label.exitPlanMode",
  进入工作树: "toolCall.label.enterWorktree",
  退出工作树: "toolCall.label.exitWorktree",
  图像分析: "toolCall.label.imageAnalyze",
  图片查看: "toolCall.label.imageView",
  用户输入: "toolCall.label.userInput",
  用户消息: "toolCall.label.userMessage",
  最终答复: "toolCall.label.finalAnswer",
  创建子任务: "toolCall.label.subtaskCreate",
  补充说明: "toolCall.label.sendMessage",
  创建子代理组: "toolCall.label.teamCreate",
  删除子代理组: "toolCall.label.teamDelete",
  子任务: "toolCall.label.subtask",
  查看任务进展: "toolCall.label.waitAgent",
  继续处理: "toolCall.label.resumeAgent",
  暂停处理: "toolCall.label.closeAgent",
  定时触发器: "toolCall.label.cron",
  远程触发器: "toolCall.label.remoteTrigger",
  图片生成: "toolCall.label.imageGeneration",
  封面图生成: "toolCall.label.coverImageGeneration",
  视频生成: "toolCall.label.videoGeneration",
  配音生成: "toolCall.label.audioGeneration",
  转写: "toolCall.label.transcription",
  口播生成: "toolCall.label.broadcastGeneration",
  封面生成: "toolCall.label.coverGeneration",
  素材检索: "toolCall.label.resourceSearch",
  链接解析: "toolCall.label.urlParse",
  排版: "toolCall.label.typesetting",
  服务技能执行: "toolCall.label.serviceSkillRun",
  站点能力目录: "toolCall.label.siteCatalog",
  站点能力推荐: "toolCall.label.siteRecommend",
  站点能力搜索: "toolCall.label.siteSearch",
  站点能力详情: "toolCall.label.siteDetail",
  站点能力执行: "toolCall.label.siteRun",
  页面打开: "toolCall.label.pageOpen",
  页面返回: "toolCall.label.pageBack",
  页面点击: "toolCall.label.pageClick",
  页面定位: "toolCall.label.pageHover",
  页面输入: "toolCall.label.pageType",
  页面拖拽: "toolCall.label.pageDrag",
  页面截图: "toolCall.label.pageScreenshot",
  页面脚本: "toolCall.label.pageScript",
  页面日志: "toolCall.label.pageLog",
  浏览器操作: "toolCall.label.browserOperation",
  工作区同步: "toolCall.label.workspaceSync",
  计划: "toolCall.label.plan",
  搜索: "toolCall.label.search",
  记忆列表: "toolCall.label.memoryList",
  记忆读取: "toolCall.label.memoryRead",
  记忆搜索: "toolCall.label.memorySearch",
  记忆修正: "toolCall.label.memoryAddNote",
};

const TOOL_DISPLAY_GROUP_TITLE_KEYS: Record<string, string> = {
  探索: "toolCall.groupTitle.explore",
  写入: "toolCall.groupTitle.write",
  编辑: "toolCall.groupTitle.edit",
  MCP: "toolCall.groupTitle.mcp",
  命令: "toolCall.groupTitle.command",
  搜索: "toolCall.groupTitle.search",
  工具入口: "toolCall.groupTitle.toolEntry",
  获取: "toolCall.groupTitle.fetch",
  配置: "toolCall.groupTitle.config",
  工作流: "toolCall.groupTitle.workflow",
  执行: "toolCall.groupTitle.execution",
  技能: "toolCall.groupTitle.skill",
  计划: "toolCall.groupTitle.plan",
  任务: "toolCall.groupTitle.task",
  工作树: "toolCall.groupTitle.worktree",
  图像: "toolCall.groupTitle.image",
  交互: "toolCall.groupTitle.interaction",
  用户消息: "toolCall.groupTitle.userMessage",
  回复: "toolCall.groupTitle.reply",
  子任务: "toolCall.groupTitle.subtask",
  创建子代理组: "toolCall.groupTitle.teamCreate",
  删除子代理组: "toolCall.groupTitle.teamDelete",
  定时触发: "toolCall.groupTitle.cron",
  远程触发: "toolCall.groupTitle.remoteTrigger",
  服务技能: "toolCall.groupTitle.serviceSkill",
  站点: "toolCall.groupTitle.site",
  浏览器: "toolCall.groupTitle.browser",
  工作区: "toolCall.groupTitle.workspace",
  记忆: "toolCall.groupTitle.memory",
  工具: "toolCall.groupTitle.generic",
};

const TOOL_DISPLAY_VERB_KEYS: Record<string, string> = {
  查看: "toolCall.verb.view",
  保存: "toolCall.verb.save",
  修改: "toolCall.verb.modify",
  批量修改: "toolCall.verb.batchModify",
  应用: "toolCall.verb.apply",
  查找: "toolCall.verb.find",
  调用: "toolCall.verb.call",
  授权: "toolCall.verb.authorize",
  运行: "toolCall.verb.run",
  搜索: "toolCall.verb.search",
  确认: "toolCall.verb.confirm",
  解析: "toolCall.verb.parse",
  查询: "toolCall.verb.query",
  抓取: "toolCall.verb.fetch",
  终止: "toolCall.verb.terminate",
  分析: "toolCall.verb.analyze",
  调整: "toolCall.verb.adjust",
  执行: "toolCall.verb.execute",
  等待: "toolCall.verb.wait",
  执行技能: "toolCall.verb.runSkill",
  列出: "toolCall.verb.list",
  加载: "toolCall.verb.load",
  开始: "toolCall.verb.start",
  更新: "toolCall.verb.update",
  查看结果: "toolCall.verb.viewResult",
  进入: "toolCall.verb.enter",
  退出: "toolCall.verb.exit",
  生成: "toolCall.verb.generate",
  收集: "toolCall.verb.collect",
  发送: "toolCall.verb.send",
  整理: "toolCall.verb.organize",
  创建: "toolCall.verb.create",
  继续: "toolCall.verb.continue",
  暂停: "toolCall.verb.pause",
  删除: "toolCall.verb.delete",
  处理: "toolCall.verb.handle",
  发起: "toolCall.verb.startTask",
  浏览: "toolCall.verb.browse",
  推荐: "toolCall.verb.recommend",
  打开: "toolCall.verb.open",
  返回: "toolCall.verb.back",
  点击: "toolCall.verb.click",
  定位: "toolCall.verb.locate",
  填写: "toolCall.verb.fill",
  拖拽: "toolCall.verb.drag",
  截图: "toolCall.verb.screenshot",
  执行脚本: "toolCall.verb.runScript",
  获取日志: "toolCall.verb.getLog",
  操作: "toolCall.verb.operate",
  同步: "toolCall.verb.sync",
  更新计划: "toolCall.verb.updatePlan",
};

const TOOL_DISPLAY_ACTION_OVERRIDE_KEYS: Record<string, string> = {
  查找失败: "toolCall.actionOverride.find.failed",
  已找到: "toolCall.actionOverride.find.completed",
  查找中: "toolCall.actionOverride.find.running",
  调用失败: "toolCall.actionOverride.call.failed",
  已调用MCP工具: "toolCall.actionOverride.mcpCall.completed",
  调用中: "toolCall.actionOverride.call.running",
  授权失败: "toolCall.actionOverride.auth.failed",
  已完成MCP授权: "toolCall.actionOverride.mcpAuth.completed",
  授权中: "toolCall.actionOverride.auth.running",
  调整失败: "toolCall.actionOverride.adjust.failed",
  已调整配置: "toolCall.actionOverride.config.completed",
  调整中: "toolCall.actionOverride.adjust.running",
  执行失败: "toolCall.actionOverride.execute.failed",
  已执行工作流: "toolCall.actionOverride.workflow.completed",
  执行中: "toolCall.actionOverride.execute.running",
  等待失败: "toolCall.actionOverride.wait.failed",
  已完成等待: "toolCall.actionOverride.wait.completed",
  等待中: "toolCall.actionOverride.wait.running",
  获取失败: "toolCall.actionOverride.fetch.failed",
  已获取技能列表: "toolCall.actionOverride.skillList.completed",
  获取中: "toolCall.actionOverride.fetch.running",
  加载失败: "toolCall.actionOverride.load.failed",
  已加载技能: "toolCall.actionOverride.skillLoad.completed",
  加载中: "toolCall.actionOverride.load.running",
  开始失败: "toolCall.actionOverride.start.failed",
  已开始: "toolCall.actionOverride.start.completed",
  开始中: "toolCall.actionOverride.start.running",
  已获取任务列表: "toolCall.actionOverride.taskList.completed",
  已获取任务详情: "toolCall.actionOverride.taskDetail.completed",
  更新失败: "toolCall.actionOverride.update.failed",
  已更新任务: "toolCall.actionOverride.taskUpdate.completed",
  更新中: "toolCall.actionOverride.update.running",
  已更新计划: "toolCall.actionOverride.planUpdate.completed",
  查看结果失败: "toolCall.actionOverride.viewResult.failed",
  已查看结果: "toolCall.actionOverride.viewResult.completed",
  查看结果中: "toolCall.actionOverride.viewResult.running",
  终止失败: "toolCall.actionOverride.terminate.failed",
  已终止任务: "toolCall.actionOverride.taskStop.completed",
  终止中: "toolCall.actionOverride.terminate.running",
  进入失败: "toolCall.actionOverride.enter.failed",
  已进入工作树: "toolCall.actionOverride.worktreeEnter.completed",
  进入中: "toolCall.actionOverride.enter.running",
  退出失败: "toolCall.actionOverride.exit.failed",
  已退出工作树: "toolCall.actionOverride.worktreeExit.completed",
  退出中: "toolCall.actionOverride.exit.running",
  查看失败: "toolCall.actionOverride.view.failed",
  已查看图片: "toolCall.actionOverride.imageView.completed",
  查看中: "toolCall.actionOverride.view.running",
  生成失败: "toolCall.actionOverride.generate.failed",
  已生成: "toolCall.actionOverride.generate.completed",
  生成中: "toolCall.actionOverride.generate.running",
  收集失败: "toolCall.actionOverride.collect.failed",
  已收集: "toolCall.actionOverride.collect.completed",
  等待输入: "toolCall.actionOverride.collect.running",
  发送失败: "toolCall.actionOverride.send.failed",
  已发送: "toolCall.actionOverride.send.completed",
  发送中: "toolCall.actionOverride.send.running",
  整理失败: "toolCall.actionOverride.organize.failed",
  已整理最终答复: "toolCall.actionOverride.finalAnswer.completed",
  整理最终答复中: "toolCall.actionOverride.finalAnswer.running",
  创建失败: "toolCall.actionOverride.create.failed",
  已创建: "toolCall.actionOverride.create.completed",
  创建中: "toolCall.actionOverride.create.running",
  删除失败: "toolCall.actionOverride.delete.failed",
  已删除: "toolCall.actionOverride.delete.completed",
  删除中: "toolCall.actionOverride.delete.running",
  处理失败: "toolCall.actionOverride.handle.failed",
  已处理: "toolCall.actionOverride.handle.completed",
  处理中: "toolCall.actionOverride.handle.running",
  已执行: "toolCall.actionOverride.execute.completed",
  浏览失败: "toolCall.actionOverride.browse.failed",
  已浏览: "toolCall.actionOverride.browse.completed",
  浏览中: "toolCall.actionOverride.browse.running",
  推荐失败: "toolCall.actionOverride.recommend.failed",
  已推荐: "toolCall.actionOverride.recommend.completed",
  推荐中: "toolCall.actionOverride.recommend.running",
  搜索失败: "toolCall.actionOverride.search.failed",
  已搜索: "toolCall.actionOverride.search.completed",
  搜索中: "toolCall.actionOverride.search.running",
  打开失败: "toolCall.actionOverride.open.failed",
  已打开: "toolCall.actionOverride.open.completed",
  打开中: "toolCall.actionOverride.open.running",
  返回失败: "toolCall.actionOverride.back.failed",
  已返回: "toolCall.actionOverride.back.completed",
  返回中: "toolCall.actionOverride.back.running",
  点击失败: "toolCall.actionOverride.click.failed",
  已点击: "toolCall.actionOverride.click.completed",
  点击中: "toolCall.actionOverride.click.running",
  定位失败: "toolCall.actionOverride.locate.failed",
  已定位: "toolCall.actionOverride.locate.completed",
  定位中: "toolCall.actionOverride.locate.running",
  填写失败: "toolCall.actionOverride.fill.failed",
  已填写: "toolCall.actionOverride.fill.completed",
  填写中: "toolCall.actionOverride.fill.running",
  拖拽失败: "toolCall.actionOverride.drag.failed",
  已拖拽: "toolCall.actionOverride.drag.completed",
  拖拽中: "toolCall.actionOverride.drag.running",
  截图失败: "toolCall.actionOverride.screenshot.failed",
  已截图: "toolCall.actionOverride.screenshot.completed",
  截图中: "toolCall.actionOverride.screenshot.running",
  脚本执行失败: "toolCall.actionOverride.runScript.failed",
  已执行脚本: "toolCall.actionOverride.runScript.completed",
  执行脚本中: "toolCall.actionOverride.runScript.running",
  获取日志失败: "toolCall.actionOverride.getLog.failed",
  已获取日志: "toolCall.actionOverride.getLog.completed",
  获取日志中: "toolCall.actionOverride.getLog.running",
  记忆列表读取失败: "toolCall.actionOverride.memoryList.failed",
  已查看记忆列表: "toolCall.actionOverride.memoryList.completed",
  正在查看记忆列表: "toolCall.actionOverride.memoryList.running",
  记忆读取失败: "toolCall.actionOverride.memoryRead.failed",
  已读取记忆: "toolCall.actionOverride.memoryRead.completed",
  正在读取记忆: "toolCall.actionOverride.memoryRead.running",
  记忆搜索失败: "toolCall.actionOverride.memorySearch.failed",
  已搜索记忆: "toolCall.actionOverride.memorySearch.completed",
  正在搜索记忆: "toolCall.actionOverride.memorySearch.running",
  记忆修正保存失败: "toolCall.actionOverride.memoryAddNote.failed",
  已保存记忆修正: "toolCall.actionOverride.memoryAddNote.completed",
  正在保存记忆修正: "toolCall.actionOverride.memoryAddNote.running",
};

const USER_FACING_TOOL_LABEL_KEYS: Record<string, string> = {
  文件读取: "toolCall.userFacing.fileRead",
  文档读取: "toolCall.userFacing.documentRead",
  资源读取: "toolCall.userFacing.resourceRead",
  "MCP 搜索": "toolCall.userFacing.mcpSearch",
  "MCP 列表": "toolCall.userFacing.mcpList",
  "MCP 读取": "toolCall.userFacing.mcpRead",
  "MCP 浏览器": "toolCall.userFacing.mcpBrowser",
  "MCP 工具": "toolCall.userFacing.mcpTool",
  "MCP 授权": "toolCall.userFacing.mcpAuth",
  文件写入: "toolCall.userFacing.fileWrite",
  文件创建: "toolCall.userFacing.fileCreate",
  文件编辑: "toolCall.userFacing.fileEdit",
  批量编辑: "toolCall.userFacing.multiEdit",
  笔记本编辑: "toolCall.userFacing.notebookEdit",
  补丁应用: "toolCall.userFacing.patchApply",
  文件匹配: "toolCall.userFacing.fileMatch",
  目录浏览: "toolCall.userFacing.directoryBrowse",
  资源列表: "toolCall.userFacing.resourceList",
  资源模板列表: "toolCall.userFacing.resourceTemplateList",
  内容检索: "toolCall.userFacing.contentSearch",
  工具入口确认: "toolCall.userFacing.toolEntry",
  文档搜索: "toolCall.userFacing.documentSearch",
  文档查询: "toolCall.userFacing.documentQuery",
  库解析: "toolCall.userFacing.libraryResolve",
  网络搜索: "toolCall.userFacing.webSearch",
  代码分析: "toolCall.userFacing.codeAnalysis",
  图片搜索: "toolCall.userFacing.imageSearch",
  联网搜图: "toolCall.userFacing.webImageSearch",
  行情查询: "toolCall.userFacing.marketData",
  天气查询: "toolCall.userFacing.weather",
  体育查询: "toolCall.userFacing.sports",
  时间查询: "toolCall.userFacing.time",
  命令执行: "toolCall.userFacing.command",
  "REPL 执行": "toolCall.userFacing.repl",
  PowerShell: "toolCall.userFacing.powershell",
  技能执行: "toolCall.userFacing.skillRun",
  技能列表: "toolCall.userFacing.skillList",
  技能加载: "toolCall.userFacing.skillLoad",
  运行配置: "toolCall.userFacing.config",
  工作流执行: "toolCall.userFacing.workflow",
  等待: "toolCall.userFacing.wait",
  任务创建: "toolCall.userFacing.taskCreate",
  任务列表: "toolCall.userFacing.taskList",
  任务详情: "toolCall.userFacing.taskDetail",
  任务更新: "toolCall.userFacing.taskUpdate",
  进入计划模式: "toolCall.userFacing.enterPlanMode",
  退出计划模式: "toolCall.userFacing.exitPlanMode",
  进入工作树: "toolCall.userFacing.enterWorktree",
  退出工作树: "toolCall.userFacing.exitWorktree",
  创建子代理组: "toolCall.userFacing.teamCreate",
  删除子代理组: "toolCall.userFacing.teamDelete",
  任务输出: "toolCall.userFacing.taskOutput",
  工作区同步: "toolCall.userFacing.workspaceSync",
  图像分析: "toolCall.userFacing.imageAnalyze",
  图片查看: "toolCall.userFacing.imageView",
  图片生成: "contentWorkbenchTools.userFacing.imageGeneration",
  视频生成: "contentWorkbenchTools.userFacing.videoGeneration",
  配音生成: "contentWorkbenchTools.userFacing.audioGeneration",
  音频生成: "contentWorkbenchTools.userFacing.audioGeneration",
  转写: "contentWorkbenchTools.userFacing.transcription",
  口播生成: "contentWorkbenchTools.userFacing.broadcastGeneration",
  封面生成: "contentWorkbenchTools.userFacing.coverGeneration",
  素材检索: "contentWorkbenchTools.userFacing.resourceSearch",
  链接解析: "contentWorkbenchTools.userFacing.urlParse",
  排版: "contentWorkbenchTools.userFacing.typesetting",
  封面图生成: "contentWorkbenchTools.userFacing.coverImageGeneration",
  服务技能执行: "toolCall.userFacing.serviceSkillRun",
  站点能力目录: "toolCall.userFacing.siteCatalog",
  站点能力推荐: "toolCall.userFacing.siteRecommend",
  站点能力搜索: "toolCall.userFacing.siteSearch",
  站点能力详情: "toolCall.userFacing.siteDetail",
  站点能力执行: "toolCall.userFacing.siteRun",
  页面截图: "toolCall.userFacing.pageScreenshot",
  页面点击: "toolCall.userFacing.pageClick",
  页面输入: "toolCall.userFacing.pageType",
  页面导航: "toolCall.userFacing.pageNavigate",
  页面等待: "toolCall.userFacing.pageWait",
  页面选择: "toolCall.userFacing.pageSelect",
  页面按键: "toolCall.userFacing.pageKey",
  页面悬停: "toolCall.userFacing.pageHover",
  页面滚动: "toolCall.userFacing.pageScroll",
  页面状态: "toolCall.userFacing.pageState",
  创建子任务: "toolCall.userFacing.subtaskCreate",
  补充说明: "toolCall.userFacing.sendMessage",
  子任务: "toolCall.userFacing.subtask",
  定时触发器: "toolCall.userFacing.cron",
  最终答复: "toolCall.userFacing.finalAnswer",
  查看任务进展: "toolCall.userFacing.waitAgent",
  继续处理: "toolCall.userFacing.resumeAgent",
  暂停处理: "toolCall.userFacing.closeAgent",
};

const TOOL_SUBJECT_FALLBACK_KEYS = {
  image: "toolCall.subject.image",
  targetSubtask: "toolCall.subject.targetSubtask",
  user: "toolCall.subject.user",
  currentSubagentGroup: "toolCall.subject.currentSubagentGroup",
  page: "toolCall.subject.page",
  serviceSkill: "toolCall.subject.serviceSkill",
  siteCapabilityCatalog: "toolCall.subject.siteCapabilityCatalog",
  siteAdapter: "toolCall.subject.siteAdapter",
  siteCapability: "toolCall.subject.siteCapability",
  toolEntry: "toolCall.subject.toolEntry",
  remoteTrigger: "toolCall.subject.remoteTrigger",
  cronTrigger: "toolCall.subject.cronTrigger",
  internalProcess: "toolCall.subject.internalProcess",
} as const;

export type ToolSubjectFallbackKey = keyof typeof TOOL_SUBJECT_FALLBACK_KEYS;

const TOOL_SUBJECT_FALLBACK_DEFAULTS: Record<ToolSubjectFallbackKey, string> = {
  image: "图片",
  targetSubtask: "目标子任务",
  user: "用户",
  currentSubagentGroup: "当前子代理组",
  page: "页面",
  serviceSkill: "服务技能",
  siteCapabilityCatalog: "站点能力目录",
  siteAdapter: "站点适配器",
  siteCapability: "站点能力",
  toolEntry: "工具入口",
  remoteTrigger: "远程触发器",
  cronTrigger: "定时触发器",
  internalProcess: "内部流程",
};

function normalizeCopyLookupKey(value: string): string {
  return value.replace(/\s+/g, "");
}

function resolveMappedCopy(
  keys: Record<string, string>,
  value: string,
): string {
  const normalized = value.trim();
  const key = keys[normalized] ?? keys[normalizeCopyLookupKey(normalized)];
  return key ? resolveAgentChatCopy(key, normalized) : normalized;
}

export function selectToolAction(
  actionKey: ToolStatusActionKey,
  status: ToolStatusActionStatus,
): string {
  return resolveRequiredAgentChatCopy(`toolCall.action.${actionKey}.${status}`);
}

export function resolveToolDisplayConfigLabel(label: string): string {
  return resolveMappedCopy(TOOL_DISPLAY_LABEL_KEYS, label);
}

export function resolveToolDisplayConfigGroupTitle(groupTitle: string): string {
  return resolveMappedCopy(TOOL_DISPLAY_GROUP_TITLE_KEYS, groupTitle);
}

export function resolveToolDisplayConfigVerb(verb: string): string {
  return resolveMappedCopy(TOOL_DISPLAY_VERB_KEYS, verb);
}

export function resolveToolDisplayActionOverride(action: string): string {
  return resolveMappedCopy(TOOL_DISPLAY_ACTION_OVERRIDE_KEYS, action);
}

export function resolveToolSubjectFallback(
  key: ToolSubjectFallbackKey,
): string {
  return resolveAgentChatCopy(
    TOOL_SUBJECT_FALLBACK_KEYS[key],
    TOOL_SUBJECT_FALLBACK_DEFAULTS[key],
  );
}

export function toUserFacingToolDisplayLabel(label: string): string {
  const normalized = label.trim();
  const key = USER_FACING_TOOL_LABEL_KEYS[normalized];
  return key ? resolveRequiredAgentChatCopy(key) : normalized;
}
