import * as protocol from "./protocol.js";
import type { AppServerClient } from "./request-client.js";

export type RequestClientMethodKind = "request" | "notification";
export type RequestClientParamsMode = "none" | "required" | "optional-empty";

export type AppServerRequestClientMethodSpec = {
  name: string;
  method: string;
  kind: RequestClientMethodKind;
  params: RequestClientParamsMode;
};

export const APP_SERVER_REQUEST_CLIENT_METHODS: readonly AppServerRequestClientMethodSpec[] =
  [
    {
      name: "initialize",
      method: protocol.METHOD_INITIALIZE,
      kind: "request",
      params: "required",
    },
    {
      name: "initialized",
      method: protocol.METHOD_INITIALIZED,
      kind: "notification",
      params: "none",
    },
    {
      name: "listCapabilities",
      method: protocol.METHOD_CAPABILITY_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "listSessions",
      method: protocol.METHOD_AGENT_SESSION_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "updateSession",
      method: protocol.METHOD_AGENT_SESSION_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "archiveManySessions",
      method: protocol.METHOD_AGENT_SESSION_ARCHIVE_MANY,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteSession",
      method: protocol.METHOD_AGENT_SESSION_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "readAgentSessionObjective",
      method: protocol.METHOD_AGENT_SESSION_OBJECTIVE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "setAgentSessionObjective",
      method: protocol.METHOD_AGENT_SESSION_OBJECTIVE_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "updateAgentSessionObjectiveStatus",
      method: protocol.METHOD_AGENT_SESSION_OBJECTIVE_STATUS_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "clearAgentSessionObjective",
      method: protocol.METHOD_AGENT_SESSION_OBJECTIVE_CLEAR,
      kind: "request",
      params: "required",
    },
    {
      name: "continueAgentSessionObjective",
      method: protocol.METHOD_AGENT_SESSION_OBJECTIVE_CONTINUE,
      kind: "request",
      params: "required",
    },
    {
      name: "auditAgentSessionObjective",
      method: protocol.METHOD_AGENT_SESSION_OBJECTIVE_AUDIT,
      kind: "request",
      params: "required",
    },
    {
      name: "appendAgentSessionRuntimeEvents",
      method: protocol.METHOD_AGENT_SESSION_RUNTIME_EVENTS_APPEND,
      kind: "request",
      params: "required",
    },
    {
      name: "compactAgentSession",
      method: protocol.METHOD_AGENT_SESSION_COMPACT,
      kind: "request",
      params: "required",
    },
    {
      name: "resumeAgentSessionThread",
      method: protocol.METHOD_AGENT_SESSION_THREAD_RESUME,
      kind: "request",
      params: "required",
    },
    {
      name: "removeAgentSessionQueuedTurn",
      method: protocol.METHOD_AGENT_SESSION_QUEUED_TURN_REMOVE,
      kind: "request",
      params: "required",
    },
    {
      name: "promoteAgentSessionQueuedTurn",
      method: protocol.METHOD_AGENT_SESSION_QUEUED_TURN_PROMOTE,
      kind: "request",
      params: "required",
    },
    {
      name: "listAgentSessionFileCheckpoints",
      method: protocol.METHOD_AGENT_SESSION_FILE_CHECKPOINT_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "getAgentSessionFileCheckpoint",
      method: protocol.METHOD_AGENT_SESSION_FILE_CHECKPOINT_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "diffAgentSessionFileCheckpoint",
      method: protocol.METHOD_AGENT_SESSION_FILE_CHECKPOINT_DIFF,
      kind: "request",
      params: "required",
    },
    {
      name: "restoreAgentSessionFileCheckpoint",
      method: protocol.METHOD_AGENT_SESSION_FILE_CHECKPOINT_RESTORE,
      kind: "request",
      params: "required",
    },
    {
      name: "getOrCreateSessionFile",
      method: protocol.METHOD_SESSION_FILE_GET_OR_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateSessionFileMeta",
      method: protocol.METHOD_SESSION_FILE_UPDATE_META,
      kind: "request",
      params: "required",
    },
    {
      name: "saveSessionFile",
      method: protocol.METHOD_SESSION_FILE_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "readSessionFile",
      method: protocol.METHOD_SESSION_FILE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "resolveSessionFilePath",
      method: protocol.METHOD_SESSION_FILE_RESOLVE_PATH,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteSessionFile",
      method: protocol.METHOD_SESSION_FILE_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "listSessionFiles",
      method: protocol.METHOD_SESSION_FILE_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "listWorkspaces",
      method: protocol.METHOD_WORKSPACE_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readWorkspace",
      method: protocol.METHOD_WORKSPACE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "updateWorkspace",
      method: protocol.METHOD_WORKSPACE_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteWorkspace",
      method: protocol.METHOD_WORKSPACE_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "ensureWorkspace",
      method: protocol.METHOD_WORKSPACE_ENSURE,
      kind: "request",
      params: "required",
    },
    {
      name: "readWorkspaceByPath",
      method: protocol.METHOD_WORKSPACE_BY_PATH_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "readDefaultWorkspace",
      method: protocol.METHOD_WORKSPACE_DEFAULT_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "ensureDefaultWorkspace",
      method: protocol.METHOD_WORKSPACE_DEFAULT_ENSURE,
      kind: "request",
      params: "none",
    },
    {
      name: "readWorkspaceProjectsRoot",
      method: protocol.METHOD_WORKSPACE_PROJECTS_ROOT_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "resolveWorkspaceProjectPath",
      method: protocol.METHOD_WORKSPACE_PROJECT_PATH_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "ensureWorkspaceReady",
      method: protocol.METHOD_WORKSPACE_ENSURE_READY,
      kind: "request",
      params: "required",
    },
    {
      name: "requestWorkspaceRightSurface",
      method: protocol.METHOD_WORKSPACE_RIGHT_SURFACE_REQUEST,
      kind: "request",
      params: "required",
    },
    {
      name: "listWorkspaceRightSurfacePending",
      method: protocol.METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "consumeWorkspaceRightSurfacePending",
      method: protocol.METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_CONSUME,
      kind: "request",
      params: "required",
    },
    {
      name: "dismissWorkspaceRightSurfacePending",
      method: protocol.METHOD_WORKSPACE_RIGHT_SURFACE_PENDING_DISMISS,
      kind: "request",
      params: "required",
    },
    {
      name: "listBrowserSessionTargets",
      method: protocol.METHOD_BROWSER_SESSION_TARGET_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "openBrowserSession",
      method: protocol.METHOD_BROWSER_SESSION_OPEN,
      kind: "request",
      params: "required",
    },
    {
      name: "readBrowserSession",
      method: protocol.METHOD_BROWSER_SESSION_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "closeBrowserSession",
      method: protocol.METHOD_BROWSER_SESSION_CLOSE,
      kind: "request",
      params: "required",
    },
    {
      name: "listBrowserSessionEvents",
      method: protocol.METHOD_BROWSER_SESSION_EVENT_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "executeBrowserSessionAction",
      method: protocol.METHOD_BROWSER_SESSION_ACTION_EXECUTE,
      kind: "request",
      params: "required",
    },
    {
      name: "listSkills",
      method: protocol.METHOD_SKILL_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readSkill",
      method: protocol.METHOD_SKILL_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listManagementSkills",
      method: protocol.METHOD_SKILL_MANAGEMENT_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "installManagementSkill",
      method: protocol.METHOD_SKILL_MANAGEMENT_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "uninstallManagementSkill",
      method: protocol.METHOD_SKILL_MANAGEMENT_UNINSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "listSkillRepositories",
      method: protocol.METHOD_SKILL_REPOSITORY_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "saveSkillRepository",
      method: protocol.METHOD_SKILL_REPOSITORY_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteSkillRepository",
      method: protocol.METHOD_SKILL_REPOSITORY_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "refreshSkillCache",
      method: protocol.METHOD_SKILL_CACHE_REFRESH,
      kind: "request",
      params: "none",
    },
    {
      name: "listInstalledSkillDirectories",
      method: protocol.METHOD_SKILL_INSTALLED_DIRECTORIES_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "inspectLocalSkill",
      method: protocol.METHOD_SKILL_LOCAL_INSPECT,
      kind: "request",
      params: "required",
    },
    {
      name: "inspectLocalSkillDetail",
      method: protocol.METHOD_SKILL_LOCAL_DETAIL_INSPECT,
      kind: "request",
      params: "required",
    },
    {
      name: "createSkillScaffold",
      method: protocol.METHOD_SKILL_LOCAL_SCAFFOLD_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "importLocalSkill",
      method: protocol.METHOD_SKILL_LOCAL_IMPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "renameLocalSkill",
      method: protocol.METHOD_SKILL_LOCAL_RENAME,
      kind: "request",
      params: "required",
    },
    {
      name: "inspectRemoteSkill",
      method: protocol.METHOD_SKILL_REMOTE_INSPECT,
      kind: "request",
      params: "required",
    },
    {
      name: "inspectLocalSkillPackage",
      method: protocol.METHOD_SKILL_PACKAGE_LOCAL_INSPECT,
      kind: "request",
      params: "required",
    },
    {
      name: "installLocalSkillPackage",
      method: protocol.METHOD_SKILL_PACKAGE_LOCAL_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "replaceLocalSkillPackage",
      method: protocol.METHOD_SKILL_PACKAGE_LOCAL_REPLACE,
      kind: "request",
      params: "required",
    },
    {
      name: "exportSkillPackage",
      method: protocol.METHOD_SKILL_PACKAGE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "installMarketplaceSkill",
      method: protocol.METHOD_SKILL_MARKETPLACE_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "installSkillFromDownload",
      method: protocol.METHOD_SKILL_PACKAGE_DOWNLOAD_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "listWorkspaceSkillBindings",
      method: protocol.METHOD_WORKSPACE_SKILL_BINDINGS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "listWorkspaceRegisteredSkills",
      method: protocol.METHOD_WORKSPACE_REGISTERED_SKILLS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "inspectPluginLocalPackage",
      method: protocol.METHOD_PLUGIN_LOCAL_PACKAGE_INSPECT,
      kind: "request",
      params: "required",
    },
    {
      name: "exportPluginLocalPackage",
      method: protocol.METHOD_PLUGIN_LOCAL_PACKAGE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "fetchPluginCloudPackage",
      method: protocol.METHOD_PLUGIN_PACKAGE_FETCH_CLOUD,
      kind: "request",
      params: "required",
    },
    {
      name: "savePluginInstalled",
      method: protocol.METHOD_PLUGIN_INSTALLED_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "listPluginInstalled",
      method: protocol.METHOD_PLUGIN_INSTALLED_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "setPluginInstalledDisabled",
      method: protocol.METHOD_PLUGIN_INSTALLED_DISABLED_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "previewPluginUninstall",
      method: protocol.METHOD_PLUGIN_INSTALLED_UNINSTALL_REHEARSAL,
      kind: "request",
      params: "required",
    },
    {
      name: "uninstallPlugin",
      method: protocol.METHOD_PLUGIN_INSTALLED_UNINSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "listPluginHostLifecycle",
      method: protocol.METHOD_PLUGIN_HOST_LIFECYCLE_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "preparePluginShell",
      method: protocol.METHOD_PLUGIN_SHELL_PREPARE,
      kind: "request",
      params: "required",
    },
    {
      name: "startPluginUiRuntime",
      method: protocol.METHOD_PLUGIN_UI_RUNTIME_START,
      kind: "request",
      params: "required",
    },
    {
      name: "getPluginUiRuntimeStatus",
      method: protocol.METHOD_PLUGIN_UI_RUNTIME_STATUS,
      kind: "request",
      params: "required",
    },
    {
      name: "stopPluginUiRuntime",
      method: protocol.METHOD_PLUGIN_UI_RUNTIME_STOP,
      kind: "request",
      params: "required",
    },
    {
      name: "listKnowledgePacks",
      method: protocol.METHOD_KNOWLEDGE_PACK_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "readKnowledgePack",
      method: protocol.METHOD_KNOWLEDGE_PACK_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "importKnowledgeSource",
      method: protocol.METHOD_KNOWLEDGE_SOURCE_IMPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "compileKnowledgePack",
      method: protocol.METHOD_KNOWLEDGE_PACK_COMPILE,
      kind: "request",
      params: "required",
    },
    {
      name: "setDefaultKnowledgePack",
      method: protocol.METHOD_KNOWLEDGE_PACK_DEFAULT_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "updateKnowledgePackStatus",
      method: protocol.METHOD_KNOWLEDGE_PACK_STATUS_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "resolveKnowledgeContext",
      method: protocol.METHOD_KNOWLEDGE_CONTEXT_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "validateKnowledgeContextRun",
      method: protocol.METHOD_KNOWLEDGE_CONTEXT_RUN_VALIDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "listAutomationJobs",
      method: protocol.METHOD_AUTOMATION_JOB_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readAutomationSchedulerConfig",
      method: protocol.METHOD_AUTOMATION_SCHEDULER_CONFIG_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "updateAutomationSchedulerConfig",
      method: protocol.METHOD_AUTOMATION_SCHEDULER_CONFIG_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "readAutomationSchedulerStatus",
      method: protocol.METHOD_AUTOMATION_SCHEDULER_STATUS,
      kind: "request",
      params: "none",
    },
    {
      name: "readAutomationJob",
      method: protocol.METHOD_AUTOMATION_JOB_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "createAutomationJob",
      method: protocol.METHOD_AUTOMATION_JOB_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateAutomationJob",
      method: protocol.METHOD_AUTOMATION_JOB_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteAutomationJob",
      method: protocol.METHOD_AUTOMATION_JOB_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "runAutomationJobNow",
      method: protocol.METHOD_AUTOMATION_JOB_RUN_NOW,
      kind: "request",
      params: "required",
    },
    {
      name: "readAutomationHealth",
      method: protocol.METHOD_AUTOMATION_JOB_HEALTH,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readAutomationRunHistory",
      method: protocol.METHOD_AUTOMATION_JOB_RUN_HISTORY,
      kind: "request",
      params: "required",
    },
    {
      name: "previewAutomationSchedule",
      method: protocol.METHOD_AUTOMATION_SCHEDULE_PREVIEW,
      kind: "request",
      params: "required",
    },
    {
      name: "validateAutomationSchedule",
      method: protocol.METHOD_AUTOMATION_SCHEDULE_VALIDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "listMcpServers",
      method: protocol.METHOD_MCP_SERVER_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "listMcpServersWithStatus",
      method: protocol.METHOD_MCP_SERVER_STATUS_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "createMcpServer",
      method: protocol.METHOD_MCP_SERVER_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateMcpServer",
      method: protocol.METHOD_MCP_SERVER_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteMcpServer",
      method: protocol.METHOD_MCP_SERVER_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "setMcpServerEnabled",
      method: protocol.METHOD_MCP_SERVER_ENABLED_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "importMcpServersFromApp",
      method: protocol.METHOD_MCP_SERVER_IMPORT_FROM_APP,
      kind: "request",
      params: "required",
    },
    {
      name: "syncAllMcpServersToLive",
      method: protocol.METHOD_MCP_SERVER_SYNC_ALL_TO_LIVE,
      kind: "request",
      params: "none",
    },
    {
      name: "loginMcpServerOauth",
      method: protocol.METHOD_MCP_SERVER_OAUTH_LOGIN,
      kind: "request",
      params: "required",
    },
    {
      name: "startMcpServer",
      method: protocol.METHOD_MCP_SERVER_START,
      kind: "request",
      params: "required",
    },
    {
      name: "stopMcpServer",
      method: protocol.METHOD_MCP_SERVER_STOP,
      kind: "request",
      params: "required",
    },
    {
      name: "listMcpTools",
      method: protocol.METHOD_MCP_TOOL_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "listMcpToolsForContext",
      method: protocol.METHOD_MCP_TOOL_LIST_FOR_CONTEXT,
      kind: "request",
      params: "required",
    },
    {
      name: "searchMcpTools",
      method: protocol.METHOD_MCP_TOOL_SEARCH,
      kind: "request",
      params: "required",
    },
    {
      name: "callMcpTool",
      method: protocol.METHOD_MCP_TOOL_CALL,
      kind: "request",
      params: "required",
    },
    {
      name: "callMcpToolWithCaller",
      method: protocol.METHOD_MCP_TOOL_CALL_WITH_CALLER,
      kind: "request",
      params: "required",
    },
    {
      name: "listMcpPrompts",
      method: protocol.METHOD_MCP_PROMPT_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "getMcpPrompt",
      method: protocol.METHOD_MCP_PROMPT_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "listMcpResources",
      method: protocol.METHOD_MCP_RESOURCE_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readMcpResource",
      method: protocol.METHOD_MCP_RESOURCE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "subscribeMcpResource",
      method: protocol.METHOD_MCP_RESOURCE_SUBSCRIBE,
      kind: "request",
      params: "required",
    },
    {
      name: "unsubscribeMcpResource",
      method: protocol.METHOD_MCP_RESOURCE_UNSUBSCRIBE,
      kind: "request",
      params: "required",
    },
    {
      name: "readProjectMemory",
      method: protocol.METHOD_PROJECT_MEMORY_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "readMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "searchMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_SEARCH,
      kind: "request",
      params: "required",
    },
    {
      name: "addMemoryStoreNote",
      method: protocol.METHOD_MEMORY_STORE_ADD_NOTE,
      kind: "request",
      params: "required",
    },
    {
      name: "consolidateMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_CONSOLIDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "listMemoryStoreReviewNotes",
      method: protocol.METHOD_MEMORY_STORE_REVIEW_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "resolveMemoryStoreReviewNote",
      method: protocol.METHOD_MEMORY_STORE_REVIEW_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "healthMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_HEALTH,
      kind: "request",
      params: "required",
    },
    {
      name: "resetMemoryStore",
      method: protocol.METHOD_MEMORY_STORE_RESET,
      kind: "request",
      params: "required",
    },
    {
      name: "rebuildMemoryStoreIndex",
      method: protocol.METHOD_MEMORY_STORE_INDEX_REBUILD,
      kind: "request",
      params: "required",
    },
    {
      name: "listLogs",
      method: protocol.METHOD_LOG_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readPersistedLogTail",
      method: protocol.METHOD_LOG_PERSISTED_TAIL,
      kind: "request",
      params: "required",
    },
    {
      name: "clearLogs",
      method: protocol.METHOD_LOG_CLEAR,
      kind: "request",
      params: "none",
    },
    {
      name: "clearDiagnosticLogHistory",
      method: protocol.METHOD_LOG_DIAGNOSTIC_HISTORY_CLEAR,
      kind: "request",
      params: "none",
    },
    {
      name: "readLogStorageDiagnostics",
      method: protocol.METHOD_DIAGNOSTICS_LOG_STORAGE_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "exportSupportBundle",
      method: protocol.METHOD_DIAGNOSTICS_SUPPORT_BUNDLE_EXPORT,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readServerDiagnostics",
      method: protocol.METHOD_DIAGNOSTICS_SERVER_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "readWindowsStartupDiagnostics",
      method: protocol.METHOD_DIAGNOSTICS_WINDOWS_STARTUP_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "listDiagnosticsTraces",
      method: protocol.METHOD_DIAGNOSTICS_TRACE_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "readDiagnosticsTrace",
      method: protocol.METHOD_DIAGNOSTICS_TRACE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "exportDiagnosticsTrace",
      method: protocol.METHOD_DIAGNOSTICS_TRACE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "readGatewayChannelStatus",
      method: protocol.METHOD_GATEWAY_CHANNEL_STATUS,
      kind: "request",
      params: "required",
    },
    {
      name: "startGatewayChannel",
      method: protocol.METHOD_GATEWAY_CHANNEL_START,
      kind: "request",
      params: "required",
    },
    {
      name: "stopGatewayChannel",
      method: protocol.METHOD_GATEWAY_CHANNEL_STOP,
      kind: "request",
      params: "required",
    },
    {
      name: "probeTelegramChannel",
      method: protocol.METHOD_TELEGRAM_CHANNEL_PROBE,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "probeFeishuChannel",
      method: protocol.METHOD_FEISHU_CHANNEL_PROBE,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "probeDiscordChannel",
      method: protocol.METHOD_DISCORD_CHANNEL_PROBE,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "probeWechatChannel",
      method: protocol.METHOD_WECHAT_CHANNEL_PROBE,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "startWechatChannelLogin",
      method: protocol.METHOD_WECHAT_CHANNEL_LOGIN_START,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "waitWechatChannelLogin",
      method: protocol.METHOD_WECHAT_CHANNEL_LOGIN_WAIT,
      kind: "request",
      params: "required",
    },
    {
      name: "listWechatChannelAccounts",
      method: protocol.METHOD_WECHAT_CHANNEL_ACCOUNT_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "removeWechatChannelAccount",
      method: protocol.METHOD_WECHAT_CHANNEL_ACCOUNT_REMOVE,
      kind: "request",
      params: "required",
    },
    {
      name: "setWechatChannelRuntimeModel",
      method: protocol.METHOD_WECHAT_CHANNEL_RUNTIME_MODEL_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "probeGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_PROBE,
      kind: "request",
      params: "none",
    },
    {
      name: "detectGatewayTunnelCloudflared",
      method: protocol.METHOD_GATEWAY_TUNNEL_CLOUDFLARED_DETECT,
      kind: "request",
      params: "none",
    },
    {
      name: "installGatewayTunnelCloudflared",
      method: protocol.METHOD_GATEWAY_TUNNEL_CLOUDFLARED_INSTALL,
      kind: "request",
      params: "required",
    },
    {
      name: "createGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "startGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_START,
      kind: "request",
      params: "none",
    },
    {
      name: "stopGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_STOP,
      kind: "request",
      params: "none",
    },
    {
      name: "restartGatewayTunnel",
      method: protocol.METHOD_GATEWAY_TUNNEL_RESTART,
      kind: "request",
      params: "none",
    },
    {
      name: "readGatewayTunnelStatus",
      method: protocol.METHOD_GATEWAY_TUNNEL_STATUS,
      kind: "request",
      params: "none",
    },
    {
      name: "syncGatewayTunnelWebhookUrl",
      method: protocol.METHOD_GATEWAY_TUNNEL_SYNC_WEBHOOK_URL,
      kind: "request",
      params: "required",
    },
    {
      name: "createImageMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_IMAGE_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "createAudioMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_AUDIO_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "createVideoMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_VIDEO_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "completeImageMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_IMAGE_COMPLETE,
      kind: "request",
      params: "required",
    },
    {
      name: "completeAudioMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_AUDIO_COMPLETE,
      kind: "request",
      params: "required",
    },
    {
      name: "getMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "listMediaTaskArtifacts",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "cancelMediaTaskArtifact",
      method: protocol.METHOD_MEDIA_TASK_ARTIFACT_CANCEL,
      kind: "request",
      params: "required",
    },
    {
      name: "getGalleryMaterial",
      method: protocol.METHOD_GALLERY_MATERIAL_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "createGalleryMaterialMetadata",
      method: protocol.METHOD_GALLERY_MATERIAL_METADATA_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "getGalleryMaterialMetadata",
      method: protocol.METHOD_GALLERY_MATERIAL_METADATA_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "updateGalleryMaterialMetadata",
      method: protocol.METHOD_GALLERY_MATERIAL_METADATA_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteGalleryMaterialMetadata",
      method: protocol.METHOD_GALLERY_MATERIAL_METADATA_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "listGalleryMaterialsByImageCategory",
      method: protocol.METHOD_GALLERY_MATERIAL_LIST_BY_IMAGE_CATEGORY,
      kind: "request",
      params: "required",
    },
    {
      name: "listGalleryMaterialsByLayoutCategory",
      method: protocol.METHOD_GALLERY_MATERIAL_LIST_BY_LAYOUT_CATEGORY,
      kind: "request",
      params: "required",
    },
    {
      name: "listGalleryMaterialsByMood",
      method: protocol.METHOD_GALLERY_MATERIAL_LIST_BY_MOOD,
      kind: "request",
      params: "required",
    },
    {
      name: "listProjectMaterials",
      method: protocol.METHOD_PROJECT_MATERIAL_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "getProjectMaterial",
      method: protocol.METHOD_PROJECT_MATERIAL_GET,
      kind: "request",
      params: "required",
    },
    {
      name: "countProjectMaterials",
      method: protocol.METHOD_PROJECT_MATERIAL_COUNT,
      kind: "request",
      params: "required",
    },
    {
      name: "uploadProjectMaterial",
      method: protocol.METHOD_PROJECT_MATERIAL_UPLOAD,
      kind: "request",
      params: "required",
    },
    {
      name: "importProjectMaterialFromUrl",
      method: protocol.METHOD_PROJECT_MATERIAL_IMPORT_FROM_URL,
      kind: "request",
      params: "required",
    },
    {
      name: "updateProjectMaterial",
      method: protocol.METHOD_PROJECT_MATERIAL_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteProjectMaterial",
      method: protocol.METHOD_PROJECT_MATERIAL_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "readProjectMaterialContent",
      method: protocol.METHOD_PROJECT_MATERIAL_CONTENT,
      kind: "request",
      params: "required",
    },
    {
      name: "listVoiceAsrCredentials",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "createVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "setDefaultVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_DEFAULT_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "testVoiceAsrCredential",
      method: protocol.METHOD_VOICE_ASR_CREDENTIAL_TEST,
      kind: "request",
      params: "required",
    },
    {
      name: "listVoiceInstructions",
      method: protocol.METHOD_VOICE_INSTRUCTION_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "saveVoiceInstruction",
      method: protocol.METHOD_VOICE_INSTRUCTION_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteVoiceInstruction",
      method: protocol.METHOD_VOICE_INSTRUCTION_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "setDefaultVoiceModel",
      method: protocol.METHOD_VOICE_MODEL_DEFAULT_SET,
      kind: "request",
      params: "required",
    },
    {
      name: "testTranscribeVoiceModelFile",
      method: protocol.METHOD_VOICE_MODEL_TEST_TRANSCRIBE_FILE,
      kind: "request",
      params: "required",
    },
    {
      name: "readUsageStats",
      method: protocol.METHOD_USAGE_STATS_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listUsageStatsModelRanking",
      method: protocol.METHOD_USAGE_STATS_MODEL_RANKING_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "listUsageStatsDailyTrends",
      method: protocol.METHOD_USAGE_STATS_DAILY_TRENDS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "readArtifacts",
      method: protocol.METHOD_ARTIFACT_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listDirectory",
      method: protocol.METHOD_FILE_SYSTEM_LIST_DIRECTORY,
      kind: "request",
      params: "required",
    },
    {
      name: "readFilePreview",
      method: protocol.METHOD_FILE_SYSTEM_READ_FILE_PREVIEW,
      kind: "request",
      params: "required",
    },
    {
      name: "createFile",
      method: protocol.METHOD_FILE_SYSTEM_CREATE_FILE,
      kind: "request",
      params: "required",
    },
    {
      name: "createDirectory",
      method: protocol.METHOD_FILE_SYSTEM_CREATE_DIRECTORY,
      kind: "request",
      params: "required",
    },
    {
      name: "renameFile",
      method: protocol.METHOD_FILE_SYSTEM_RENAME_FILE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteFile",
      method: protocol.METHOD_FILE_SYSTEM_DELETE_FILE,
      kind: "request",
      params: "required",
    },
    {
      name: "readProjectGitStatus",
      method: protocol.METHOD_PROJECT_GIT_STATUS,
      kind: "request",
      params: "required",
    },
    {
      name: "readProjectGitDiff",
      method: protocol.METHOD_PROJECT_GIT_DIFF,
      kind: "request",
      params: "required",
    },
    {
      name: "listProjectGitCommits",
      method: protocol.METHOD_PROJECT_GIT_COMMITS_LIST,
      kind: "request",
      params: "required",
    },
    {
      name: "checkoutProjectGitBranch",
      method: protocol.METHOD_PROJECT_GIT_BRANCH_CHECKOUT,
      kind: "request",
      params: "required",
    },
    {
      name: "createProjectGitBranch",
      method: protocol.METHOD_PROJECT_GIT_BRANCH_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "createProjectGitWorktree",
      method: protocol.METHOD_PROJECT_GIT_WORKTREE_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "startProjectShellSession",
      method: protocol.METHOD_PROJECT_SHELL_SESSION_START,
      kind: "request",
      params: "required",
    },
    {
      name: "writeProjectShellSession",
      method: protocol.METHOD_PROJECT_SHELL_SESSION_WRITE,
      kind: "request",
      params: "required",
    },
    {
      name: "resizeProjectShellSession",
      method: protocol.METHOD_PROJECT_SHELL_SESSION_RESIZE,
      kind: "request",
      params: "required",
    },
    {
      name: "killProjectShellSession",
      method: protocol.METHOD_PROJECT_SHELL_SESSION_KILL,
      kind: "request",
      params: "required",
    },
    {
      name: "drainProjectShellSessionEvents",
      method: protocol.METHOD_PROJECT_SHELL_SESSION_DRAIN_EVENTS,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "startExecutionProcess",
      method: protocol.METHOD_EXECUTION_PROCESS_START,
      kind: "request",
      params: "required",
    },
    {
      name: "writeExecutionProcessStdin",
      method: protocol.METHOD_EXECUTION_PROCESS_WRITE_STDIN,
      kind: "request",
      params: "required",
    },
    {
      name: "interruptExecutionProcess",
      method: protocol.METHOD_EXECUTION_PROCESS_INTERRUPT,
      kind: "request",
      params: "required",
    },
    {
      name: "terminateExecutionProcess",
      method: protocol.METHOD_EXECUTION_PROCESS_TERMINATE,
      kind: "request",
      params: "required",
    },
    {
      name: "readExecutionProcessStatus",
      method: protocol.METHOD_EXECUTION_PROCESS_STATUS,
      kind: "request",
      params: "required",
    },
    {
      name: "drainExecutionProcessOutput",
      method: protocol.METHOD_EXECUTION_PROCESS_DRAIN_OUTPUT,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "exportEvidence",
      method: protocol.METHOD_EVIDENCE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "exportHandoffBundle",
      method: protocol.METHOD_AGENT_SESSION_HANDOFF_BUNDLE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "exportReplayCase",
      method: protocol.METHOD_AGENT_SESSION_REPLAY_CASE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "exportAnalysisHandoff",
      method: protocol.METHOD_AGENT_SESSION_ANALYSIS_HANDOFF_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "exportReviewDecisionTemplate",
      method: protocol.METHOD_AGENT_SESSION_REVIEW_DECISION_TEMPLATE_EXPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "saveReviewDecision",
      method: protocol.METHOD_AGENT_SESSION_REVIEW_DECISION_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "startSession",
      method: protocol.METHOD_AGENT_SESSION_START,
      kind: "request",
      params: "required",
    },
    {
      name: "readSession",
      method: protocol.METHOD_AGENT_SESSION_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "readWorkflow",
      method: protocol.METHOD_WORKFLOW_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "cancelWorkflow",
      method: protocol.METHOD_WORKFLOW_CANCEL,
      kind: "request",
      params: "required",
    },
    {
      name: "retryWorkflow",
      method: protocol.METHOD_WORKFLOW_RETRY,
      kind: "request",
      params: "required",
    },
    {
      name: "respondWorkflow",
      method: protocol.METHOD_WORKFLOW_RESPOND,
      kind: "request",
      params: "required",
    },
    {
      name: "readAgentSessionToolInventory",
      method: protocol.METHOD_AGENT_SESSION_TOOL_INVENTORY_READ,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "readAgentSessionMedia",
      method: protocol.METHOD_AGENT_SESSION_MEDIA_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listModels",
      method: protocol.METHOD_MODEL_LIST,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "listModelPreferences",
      method: protocol.METHOD_MODEL_PREFERENCES_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readModelSyncState",
      method: protocol.METHOD_MODEL_SYNC_STATE_READ,
      kind: "request",
      params: "none",
    },
    {
      name: "listModelProviders",
      method: protocol.METHOD_MODEL_PROVIDER_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "listModelProviderCatalog",
      method: protocol.METHOD_MODEL_PROVIDER_CATALOG_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "readModelProvider",
      method: protocol.METHOD_MODEL_PROVIDER_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "createModelProvider",
      method: protocol.METHOD_MODEL_PROVIDER_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateModelProvider",
      method: protocol.METHOD_MODEL_PROVIDER_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteModelProvider",
      method: protocol.METHOD_MODEL_PROVIDER_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateModelProviderSortOrders",
      method: protocol.METHOD_MODEL_PROVIDER_SORT_ORDERS_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "exportModelProviderConfig",
      method: protocol.METHOD_MODEL_PROVIDER_CONFIG_EXPORT,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "importModelProviderConfig",
      method: protocol.METHOD_MODEL_PROVIDER_CONFIG_IMPORT,
      kind: "request",
      params: "required",
    },
    {
      name: "testModelProviderConnection",
      method: protocol.METHOD_MODEL_PROVIDER_TEST_CONNECTION,
      kind: "request",
      params: "required",
    },
    {
      name: "testModelProviderChat",
      method: protocol.METHOD_MODEL_PROVIDER_TEST_CHAT,
      kind: "request",
      params: "required",
    },
    {
      name: "fetchModelProviderModels",
      method: protocol.METHOD_MODEL_PROVIDER_FETCH_MODELS,
      kind: "request",
      params: "required",
    },
    {
      name: "createModelProviderKey",
      method: protocol.METHOD_MODEL_PROVIDER_KEY_CREATE,
      kind: "request",
      params: "required",
    },
    {
      name: "updateModelProviderKey",
      method: protocol.METHOD_MODEL_PROVIDER_KEY_UPDATE,
      kind: "request",
      params: "required",
    },
    {
      name: "deleteModelProviderKey",
      method: protocol.METHOD_MODEL_PROVIDER_KEY_DELETE,
      kind: "request",
      params: "required",
    },
    {
      name: "readNextModelProviderKey",
      method: protocol.METHOD_MODEL_PROVIDER_KEY_NEXT,
      kind: "request",
      params: "required",
    },
    {
      name: "recordModelProviderKeyUsage",
      method: protocol.METHOD_MODEL_PROVIDER_KEY_USAGE_RECORD,
      kind: "request",
      params: "required",
    },
    {
      name: "recordModelProviderKeyError",
      method: protocol.METHOD_MODEL_PROVIDER_KEY_ERROR_RECORD,
      kind: "request",
      params: "required",
    },
    {
      name: "readModelProviderUiState",
      method: protocol.METHOD_MODEL_PROVIDER_UI_STATE_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "writeModelProviderUiState",
      method: protocol.METHOD_MODEL_PROVIDER_UI_STATE_WRITE,
      kind: "request",
      params: "required",
    },
    {
      name: "readModelProviderAlias",
      method: protocol.METHOD_MODEL_PROVIDER_ALIAS_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "listModelProviderAliases",
      method: protocol.METHOD_MODEL_PROVIDER_ALIAS_LIST,
      kind: "request",
      params: "none",
    },
    {
      name: "resolveConnectDeepLink",
      method: protocol.METHOD_CONNECT_DEEP_LINK_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "resolveConnectOpenDeepLink",
      method: protocol.METHOD_CONNECT_OPEN_DEEP_LINK_RESOLVE,
      kind: "request",
      params: "required",
    },
    {
      name: "saveConnectRelayApiKey",
      method: protocol.METHOD_CONNECT_RELAY_API_KEY_SAVE,
      kind: "request",
      params: "required",
    },
    {
      name: "sendConnectCallback",
      method: protocol.METHOD_CONNECT_CALLBACK_SEND,
      kind: "request",
      params: "required",
    },
    {
      name: "scanConversationImportSource",
      method: protocol.METHOD_CONVERSATION_IMPORT_SOURCE_SCAN,
      kind: "request",
      params: "optional-empty",
    },
    {
      name: "previewConversationImportThread",
      method: protocol.METHOD_CONVERSATION_IMPORT_THREAD_PREVIEW,
      kind: "request",
      params: "required",
    },
    {
      name: "commitConversationImportThread",
      method: protocol.METHOD_CONVERSATION_IMPORT_THREAD_COMMIT,
      kind: "request",
      params: "required",
    },
    {
      name: "readConversationImportRuntimeEvents",
      method: protocol.METHOD_CONVERSATION_IMPORT_THREAD_RUNTIME_EVENTS_READ,
      kind: "request",
      params: "required",
    },
    {
      name: "startTurn",
      method: protocol.METHOD_AGENT_SESSION_TURN_START,
      kind: "request",
      params: "required",
    },
    {
      name: "cancelTurn",
      method: protocol.METHOD_AGENT_SESSION_TURN_CANCEL,
      kind: "request",
      params: "required",
    },
    {
      name: "replayAction",
      method: protocol.METHOD_AGENT_SESSION_ACTION_REPLAY,
      kind: "request",
      params: "required",
    },
    {
      name: "respondAction",
      method: protocol.METHOD_AGENT_SESSION_ACTION_RESPOND,
      kind: "request",
      params: "required",
    },
  ];

function resolveParams(
  mode: RequestClientParamsMode,
  args: IArguments,
): unknown {
  if (mode === "none") {
    return {};
  }
  if (mode === "optional-empty") {
    return args.length === 0 || args[0] === undefined ? {} : args[0];
  }
  return args[0];
}

export function installAppServerRequestClientMethods(
  prototype: AppServerClient,
): void {
  for (const spec of APP_SERVER_REQUEST_CLIENT_METHODS) {
    Object.defineProperty(prototype, spec.name, {
      configurable: true,
      writable: true,
      value: function (
        this: AppServerClient,
      ): protocol.JsonRpcRequest | protocol.JsonRpcNotification {
        const params = resolveParams(spec.params, arguments);
        if (spec.kind === "notification") {
          return protocol.notification(spec.method, params);
        }
        return this.request(spec.method, params);
      },
    });
  }
}
