export type JsonSchemaObject = Record<string, unknown>;

const stringSchema = { type: "string", minLength: 1 } as const;
const stringArraySchema = {
  type: "array",
  items: { type: "string" },
} as const;

export const AGENT_RUNTIME_EVENT_SCHEMA: JsonSchemaObject = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://limecloud.dev/schemas/agent-runtime-event.v0.1.schema.json",
  title: "AgentRuntimeExecutionEvent",
  type: "object",
  required: [
    "id",
    "schemaVersion",
    "runtimeId",
    "kind",
    "status",
    "sequence",
    "title",
    "createdAt",
  ],
  additionalProperties: true,
  not: {
    properties: {
      eventClass: {
        enum: [
          "done",
          "final_done",
          "cancelled",
          "turn.done",
          "turn.final_done",
          "turn.cancelled",
        ],
      },
    },
    required: ["eventClass"],
  },
  properties: {
    id: stringSchema,
    schemaVersion: { const: "lime-runtime-event/v0.1" },
    runtimeId: stringSchema,
    kind: stringSchema,
    status: stringSchema,
    eventClass: { type: "string" },
    owner: { type: "string" },
    sequence: { type: "integer", minimum: 0 },
    threadId: { type: "string" },
    turnId: { type: "string" },
    taskId: { type: "string" },
    subagentId: { type: "string" },
    runId: { type: "string" },
    stepId: { type: "string" },
    toolCallId: { type: "string" },
    actionId: { type: "string" },
    workerId: { type: "string" },
    channelId: { type: "string" },
    handoffId: { type: "string" },
    reviewId: { type: "string" },
    traceId: { type: "string" },
    spanId: { type: "string" },
    attemptId: { type: "string" },
    artifactId: { type: "string" },
    evidenceId: { type: "string" },
    phase: { type: "string" },
    title: stringSchema,
    detail: { type: "string" },
    refIds: stringArraySchema,
    artifactRefs: stringArraySchema,
    evidenceRefs: stringArraySchema,
    payload: { type: "object" },
    model: { type: "string" },
    createdAt: stringSchema,
    completedAt: { type: "string" },
  },
} as const;

export const AGENT_RUNTIME_STATE_DELTA_SCHEMA: JsonSchemaObject = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://limecloud.dev/schemas/agent-runtime-state-delta.v0.1.schema.json",
  title: "AgentRuntimeStateDelta",
  type: "object",
  required: [
    "schemaVersion",
    "runtimeId",
    "sequence",
    "target",
    "patch",
    "createdAt",
  ],
  additionalProperties: false,
  properties: {
    schemaVersion: { const: "lime-runtime-state-delta/v0.1" },
    runtimeId: stringSchema,
    threadId: { type: "string" },
    turnId: { type: "string" },
    sequence: { type: "integer", minimum: 0 },
    baseEventId: { type: "string" },
    target: { type: "string" },
    patch: {
      type: "array",
      items: {
        oneOf: [
          {
            type: "object",
            required: ["op", "path", "value"],
            additionalProperties: false,
            properties: {
              op: { enum: ["add", "replace", "test"] },
              path: stringSchema,
              value: true,
            },
          },
          {
            type: "object",
            required: ["op", "path"],
            additionalProperties: false,
            properties: {
              op: { const: "remove" },
              path: stringSchema,
            },
          },
          {
            type: "object",
            required: ["op", "path", "from"],
            additionalProperties: false,
            properties: {
              op: { enum: ["move", "copy"] },
              path: stringSchema,
              from: stringSchema,
            },
          },
        ],
      },
    },
    createdAt: stringSchema,
  },
} as const;

export const AGENT_UI_PROJECTION_STATE_SCHEMA: JsonSchemaObject = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://limecloud.dev/schemas/agent-ui-projection-state.v0.1.schema.json",
  title: "AgentUiProjectionState",
  type: "object",
  required: [
    "runtime",
    "messages",
    "timeline",
    "graph",
    "tools",
    "actions",
    "artifacts",
    "evidence",
    "diagnostics",
    "subagents",
    "readModel",
    "hydration",
    "ephemeralUi",
  ],
  additionalProperties: true,
  properties: {
    runtime: { type: "object" },
    messages: { type: "array" },
    timeline: { type: "array" },
    graph: { type: "array" },
    tools: { type: "array" },
    actions: { type: "array" },
    artifacts: { type: "array" },
    evidence: { type: "array" },
    diagnostics: { type: "array" },
    subagents: {
      type: "object",
      required: [
        "hasSubagents",
        "threads",
        "delegationCalls",
        "activities",
        "activeThreadIds",
        "completedThreadIds",
        "failedThreadIds",
      ],
      additionalProperties: true,
      properties: {
        hasSubagents: { type: "boolean" },
        threads: { type: "array" },
        delegationCalls: { type: "array" },
        activities: { type: "array" },
        activeThreadIds: stringArraySchema,
        completedThreadIds: stringArraySchema,
        failedThreadIds: stringArraySchema,
      },
    },
    readModel: { type: "object" },
    hydration: {
      type: "object",
      required: ["status", "eventCount"],
      additionalProperties: true,
      properties: {
        status: { type: "string" },
        eventCount: { type: "number" },
      },
    },
    ephemeralUi: { type: "object" },
  },
} as const;

export const AGENT_RUNTIME_CAPABILITY_MANIFEST_SCHEMA: JsonSchemaObject = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://limecloud.dev/schemas/agent-runtime-capability-manifest.v0.1.schema.json",
  title: "AgentRuntimeCapabilityManifest",
  type: "object",
  required: ["schemaVersion", "runtimeId", "generatedAt", "capabilities"],
  additionalProperties: false,
  properties: {
    schemaVersion: { const: "lime-runtime-capability-manifest/v0.1" },
    runtimeId: stringSchema,
    providerId: { type: "string" },
    sessionId: { type: "string" },
    generatedAt: stringSchema,
    capabilities: {
      type: "array",
      items: {
        type: "object",
        required: ["id", "status", "scope", "title"],
        additionalProperties: false,
        properties: {
          id: stringSchema,
          status: stringSchema,
          scope: stringSchema,
          title: stringSchema,
          detail: { type: "string" },
          version: { type: "string" },
          metadata: { type: "object" },
        },
      },
    },
  },
} as const;

export const AGENT_RUNTIME_RESUME_CONTRACT_SCHEMA: JsonSchemaObject = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://limecloud.dev/schemas/agent-runtime-resume-contract.v0.1.schema.json",
  title: "AgentRuntimeResumeContract",
  type: "object",
  required: [
    "schemaVersion",
    "runtimeId",
    "sessionId",
    "turnId",
    "resumeMode",
    "openActionIds",
    "decisions",
    "createdAt",
  ],
  additionalProperties: false,
  properties: {
    schemaVersion: { const: "lime-runtime-resume-contract/v0.1" },
    runtimeId: stringSchema,
    sessionId: stringSchema,
    turnId: stringSchema,
    resumeMode: stringSchema,
    openActionIds: stringArraySchema,
    decisions: {
      type: "array",
      items: {
        type: "object",
        required: ["actionId", "decision"],
        additionalProperties: false,
        properties: {
          actionId: stringSchema,
          decision: stringSchema,
          response: true,
          metadata: { type: "object" },
        },
      },
    },
    expiresAt: { type: "string" },
    createdAt: stringSchema,
  },
} as const;

export const agentUiJsonSchemas = {
  runtimeEvent: AGENT_RUNTIME_EVENT_SCHEMA,
  runtimeStateDelta: AGENT_RUNTIME_STATE_DELTA_SCHEMA,
  projectionState: AGENT_UI_PROJECTION_STATE_SCHEMA,
  runtimeCapabilityManifest: AGENT_RUNTIME_CAPABILITY_MANIFEST_SCHEMA,
  runtimeResumeContract: AGENT_RUNTIME_RESUME_CONTRACT_SCHEMA,
} as const;
