mod registry;

use crate::app_server_method_catalog;
use crate::AppServerMethodKind;
use crate::JSONRPC_VERSION;
use crate::PROTOCOL_VERSION;
use registry::jsonrpc_schemas;
use registry::{v0_schemas, v2_schemas};
use serde_json::json;
use serde_json::Value;
use std::collections::BTreeMap;
use std::path::PathBuf;

pub const GENERATED_SCHEMA_HEADER: &str = "Generated by app-server-protocol. Do not edit by hand.";
pub const SCHEMA_BUNDLE_FILE_NAME: &str = "app_server_protocol.schemas.json";

const V2_OWNED_V0_SCHEMA_NAMES: [&str; 1] = ["ServerNotification"];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SchemaExportOptions {
    pub include_envelopes: bool,
    pub include_method_catalog: bool,
    pub include_protocol_types: bool,
}

impl Default for SchemaExportOptions {
    fn default() -> Self {
        Self {
            include_envelopes: true,
            include_method_catalog: true,
            include_protocol_types: true,
        }
    }
}

pub fn generate_json_schema_bundle(options: SchemaExportOptions) -> Value {
    let mut properties = serde_json::Map::new();
    if options.include_envelopes {
        insert_unique_definition(
            &mut properties,
            "requestId",
            request_id_schema(),
            "envelope",
        );
        insert_unique_definition(
            &mut properties,
            "jsonRpcRequest",
            json_rpc_request_schema(),
            "envelope",
        );
        insert_unique_definition(
            &mut properties,
            "jsonRpcNotification",
            json_rpc_notification_schema(),
            "envelope",
        );
        insert_unique_definition(
            &mut properties,
            "jsonRpcResponse",
            json_rpc_response_schema(),
            "envelope",
        );
        insert_unique_definition(
            &mut properties,
            "jsonRpcError",
            json_rpc_error_schema(),
            "envelope",
        );
    }
    if options.include_method_catalog {
        insert_unique_definition(
            &mut properties,
            "methods",
            method_catalog_schema(),
            "method catalog",
        );
    }
    if options.include_envelopes {
        for schema in jsonrpc_schemas() {
            insert_unique_definition(
                &mut properties,
                schema.name,
                schema.value.clone(),
                "JSON-RPC",
            );
        }
    }
    if options.include_protocol_types {
        for schema in v0_schemas() {
            if !V2_OWNED_V0_SCHEMA_NAMES.contains(&schema.name) {
                insert_unique_definition(&mut properties, schema.name, schema.value.clone(), "v0");
            }
        }
        for schema in v2_schemas() {
            insert_unique_definition(&mut properties, schema.name, schema.value.clone(), "v2");
        }
    }

    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "app-server-protocol",
        "title": "App Server Protocol",
        "description": GENERATED_SCHEMA_HEADER,
        "protocolVersion": PROTOCOL_VERSION,
        "jsonRpcVersion": JSONRPC_VERSION,
        "type": "object",
        "$defs": properties,
    })
}

fn insert_unique_definition(
    definitions: &mut serde_json::Map<String, Value>,
    name: &str,
    value: Value,
    owner: &str,
) {
    assert!(
        !definitions.contains_key(name),
        "duplicate schema definition `{name}` from {owner}"
    );
    definitions.insert(name.to_string(), value);
}

pub fn generated_schema_tree() -> BTreeMap<PathBuf, Vec<u8>> {
    generated_schema_tree_with_options(SchemaExportOptions::default())
}

pub fn generated_schema_tree_with_options(
    options: SchemaExportOptions,
) -> BTreeMap<PathBuf, Vec<u8>> {
    let mut files = BTreeMap::new();
    files.insert(
        PathBuf::from("json").join(SCHEMA_BUNDLE_FILE_NAME),
        pretty_json_bytes(&generate_json_schema_bundle(options)),
    );
    if options.include_envelopes {
        for schema in jsonrpc_schemas() {
            files.insert(
                PathBuf::from("json")
                    .join("jsonrpc")
                    .join(format!("{}.json", schema.name)),
                pretty_json_bytes(&schema.value),
            );
        }
    }
    if options.include_protocol_types {
        for schema in v0_schemas() {
            files.insert(
                PathBuf::from("json")
                    .join("v0")
                    .join(format!("{}.json", schema.name)),
                pretty_json_bytes(&schema.value),
            );
        }
        for schema in v2_schemas() {
            files.insert(
                PathBuf::from("json")
                    .join("v2")
                    .join(format!("{}.json", schema.name)),
                pretty_json_bytes(&schema.value),
            );
        }
    }
    files
}

fn request_id_schema() -> Value {
    json!({
        "oneOf": [
            { "type": "integer" },
            { "type": "string" }
        ]
    })
}

fn json_rpc_request_schema() -> Value {
    json!({
        "type": "object",
        "required": ["id", "method"],
        "additionalProperties": false,
        "properties": {
            "id": { "$ref": "#/$defs/requestId" },
            "method": { "type": "string" },
            "params": true
        }
    })
}

fn json_rpc_notification_schema() -> Value {
    json!({
        "type": "object",
        "required": ["method"],
        "additionalProperties": false,
        "properties": {
            "method": { "type": "string" },
            "params": true
        }
    })
}

fn json_rpc_response_schema() -> Value {
    json!({
        "type": "object",
        "required": ["id", "result"],
        "additionalProperties": false,
        "properties": {
            "id": { "$ref": "#/$defs/requestId" },
            "result": true
        }
    })
}

fn json_rpc_error_schema() -> Value {
    json!({
        "type": "object",
        "required": ["id", "error"],
        "additionalProperties": false,
        "properties": {
            "id": { "$ref": "#/$defs/requestId" },
            "error": {
                "type": "object",
                "required": ["code", "message"],
                "additionalProperties": false,
                "properties": {
                    "code": { "type": "integer" },
                    "message": { "type": "string" },
                    "data": true
                }
            }
        }
    })
}

fn method_catalog_schema() -> Value {
    let catalog = app_server_method_catalog();
    let requests = catalog
        .iter()
        .filter(|method| method.kind == AppServerMethodKind::Request)
        .map(|method| method.method)
        .collect::<Vec<_>>();
    let notifications = catalog
        .iter()
        .filter(|method| method.kind == AppServerMethodKind::Notification)
        .map(|method| method.method)
        .collect::<Vec<_>>();
    let server_requests = catalog
        .iter()
        .filter(|method| method.kind == AppServerMethodKind::ServerRequest)
        .map(|method| method.method)
        .collect::<Vec<_>>();

    json!({
        "type": "object",
        "required": ["requests", "notifications", "serverRequests"],
        "additionalProperties": false,
        "properties": {
            "requests": {
                "type": "array",
                "items": { "enum": requests }
            },
            "notifications": {
                "type": "array",
                "items": { "enum": notifications }
            },
            "serverRequests": {
                "type": "array",
                "items": { "enum": server_requests }
            }
        }
    })
}

fn pretty_json_bytes(value: &Value) -> Vec<u8> {
    let mut bytes = serde_json::to_vec_pretty(value).expect("serialize schema JSON");
    bytes.push(b'\n');
    bytes
}

#[cfg(test)]
pub(super) mod tests {
    use super::*;
    use crate::protocol::v2::{
        METHODS, METHOD_MCP_SERVER_ELICITATION_REQUEST, METHOD_SERVER_REQUEST_RESOLVED,
        NOTIFICATION_METHODS, SERVER_REQUEST_METHODS,
    };

    #[test]
    fn schema_bundle_exports_json_rpc_envelopes_and_method_catalog() {
        let bundle = generate_json_schema_bundle(SchemaExportOptions::default());

        assert_eq!(bundle["protocolVersion"], PROTOCOL_VERSION);
        assert_eq!(bundle["$defs"]["jsonRpcRequest"]["required"][0], "id");
        assert_eq!(
            bundle["$defs"]["methods"]["properties"]["requests"]["items"]["enum"]
                .as_array()
                .expect("requests")
                .len(),
            app_server_method_catalog()
                .iter()
                .filter(|method| method.kind == AppServerMethodKind::Request)
                .count()
        );
        let requests = bundle["$defs"]["methods"]["properties"]["requests"]["items"]["enum"]
            .as_array()
            .expect("requests");
        for method in METHODS {
            assert!(requests.contains(&Value::String((*method).to_string())));
        }
        assert!(
            bundle["$defs"]["methods"]["properties"]["notifications"]["items"]["enum"]
                .as_array()
                .expect("notifications")
                .contains(&serde_json::Value::String(
                    METHOD_SERVER_REQUEST_RESOLVED.to_string()
                ))
        );
        let notifications = bundle["$defs"]["methods"]["properties"]["notifications"]["items"]
            ["enum"]
            .as_array()
            .expect("notifications");
        for method in NOTIFICATION_METHODS {
            assert!(notifications.contains(&Value::String((*method).to_string())));
        }
        assert_eq!(
            bundle["$defs"]["methods"]["properties"]["serverRequests"]["items"]["enum"]
                .as_array()
                .expect("server requests"),
            &SERVER_REQUEST_METHODS
                .iter()
                .map(|method| Value::String((*method).to_string()))
                .collect::<Vec<_>>()
        );
        assert!(SERVER_REQUEST_METHODS.contains(&METHOD_MCP_SERVER_ELICITATION_REQUEST));
        for schema_name in [
            "ClientRequest",
            "ClientResponse",
            "ServerRequest",
            "ServerNotification",
        ] {
            assert!(
                bundle["$defs"].get(schema_name).is_some(),
                "v2 envelope schema {schema_name} must be exported"
            );
        }
    }

    #[test]
    fn schema_tree_uses_stable_bundle_path() {
        let tree = generated_schema_tree();

        assert!(tree.contains_key(&PathBuf::from("json").join(SCHEMA_BUNDLE_FILE_NAME)));
        assert!(tree.contains_key(&PathBuf::from("json/v0/AgentSessionTurnStartParams.json")));
        assert!(tree.contains_key(&PathBuf::from("json/jsonrpc/JsonRpcRequest.json")));
        assert_eq!(
            tree.len(),
            1 + crate::JSONRPC_SCHEMA_TYPE_NAMES.len()
                + crate::V0_SCHEMA_TYPE_NAMES.len()
                + crate::V2_SCHEMA_TYPE_NAMES.len()
        );
    }

    #[test]
    fn schema_exports_gate_envelopes_and_protocol_types_independently() {
        for (include_envelopes, include_protocol_types) in
            [(false, false), (false, true), (true, false), (true, true)]
        {
            let options = SchemaExportOptions {
                include_envelopes,
                include_method_catalog: false,
                include_protocol_types,
            };
            let bundle = generate_json_schema_bundle(options);
            let definitions = bundle["$defs"].as_object().expect("schema definitions");

            assert_eq!(
                definitions.contains_key("jsonRpcRequest"),
                include_envelopes,
                "inline request envelope must follow include_envelopes"
            );
            assert_eq!(
                definitions.contains_key("JsonRpcRequest"),
                include_envelopes,
                "typed JSON-RPC envelope must follow include_envelopes"
            );
            assert_eq!(
                definitions.contains_key("ClientInfo"),
                include_protocol_types,
                "v0 schema must follow include_protocol_types"
            );
            assert_eq!(
                definitions.contains_key("Thread"),
                include_protocol_types,
                "v2 schema must follow include_protocol_types"
            );

            let tree = generated_schema_tree_with_options(options);
            assert_eq!(
                tree.contains_key(&PathBuf::from("json/jsonrpc/JsonRpcRequest.json")),
                include_envelopes,
                "JSON-RPC file must follow include_envelopes"
            );
            assert_eq!(
                tree.contains_key(&PathBuf::from("json/v0/ClientInfo.json")),
                include_protocol_types,
                "v0 file must follow include_protocol_types"
            );
            assert_eq!(
                tree.contains_key(&PathBuf::from("json/v2/Thread.json")),
                include_protocol_types,
                "v2 file must follow include_protocol_types"
            );
            assert_eq!(
                tree.len(),
                1 + usize::from(include_envelopes) * crate::JSONRPC_SCHEMA_TYPE_NAMES.len()
                    + usize::from(include_protocol_types)
                        * (crate::V0_SCHEMA_TYPE_NAMES.len() + crate::V2_SCHEMA_TYPE_NAMES.len()),
                "schema tree must contain only the enabled groups"
            );
        }
    }

    #[test]
    fn schema_registry_matches_declared_type_names() {
        let jsonrpc_schema_names = jsonrpc_schemas()
            .iter()
            .map(|schema| schema.name)
            .collect::<Vec<_>>();
        let v0_schema_names = v0_schemas()
            .iter()
            .map(|schema| schema.name)
            .collect::<Vec<_>>();
        let v2_schema_names = v2_schemas()
            .iter()
            .map(|schema| schema.name)
            .collect::<Vec<_>>();

        assert_eq!(jsonrpc_schema_names, crate::JSONRPC_SCHEMA_TYPE_NAMES);
        assert_eq!(v0_schema_names, crate::V0_SCHEMA_TYPE_NAMES);
        assert_eq!(v2_schema_names, crate::V2_SCHEMA_TYPE_NAMES);
    }

    #[test]
    fn v2_owns_the_declared_v0_schema_collisions_without_changing_bundle_values() {
        let v0_schemas = v0_schemas();
        let v2_schemas = v2_schemas();
        let v0_names = v0_schemas
            .iter()
            .map(|schema| schema.name)
            .collect::<std::collections::BTreeSet<_>>();
        let v2_names = v2_schemas
            .iter()
            .map(|schema| schema.name)
            .collect::<std::collections::BTreeSet<_>>();
        let collisions = v0_names
            .intersection(&v2_names)
            .copied()
            .collect::<Vec<_>>();

        assert_eq!(collisions, V2_OWNED_V0_SCHEMA_NAMES);

        let mut previous_values = serde_json::Map::new();
        for schema in v0_schemas.iter().chain(v2_schemas.iter()) {
            previous_values.insert(schema.name.to_string(), schema.value.clone());
        }
        let bundle = generate_json_schema_bundle(SchemaExportOptions::default());
        let definitions = bundle["$defs"].as_object().expect("schema definitions");

        for (name, previous_value) in previous_values {
            assert_eq!(
                definitions.get(&name),
                Some(&previous_value),
                "explicit schema ownership must preserve `{name}`"
            );
        }
    }

    #[test]
    #[should_panic(expected = "duplicate schema definition `Duplicate` from test")]
    fn schema_bundle_rejects_unexpected_duplicate_definitions() {
        let mut definitions = serde_json::Map::new();
        insert_unique_definition(&mut definitions, "Duplicate", json!(true), "test");
        insert_unique_definition(&mut definitions, "Duplicate", json!(false), "test");
    }
}
