use crate::AgentAppInstalledListResponse;
use crate::AgentAppUiRuntimeStartParams;
use crate::AgentAppUiRuntimeStatusParams;
use crate::AgentAppUiRuntimeStatusResponse;
use crate::AgentAppUiRuntimeStopParams;
use crate::AgentAttachment;
use crate::AgentEvent;
use crate::AgentInput;
use crate::AgentSession;
use crate::AgentSessionActionRespondParams;
use crate::AgentSessionActionRespondResponse;
use crate::AgentSessionActionScope;
use crate::AgentSessionActionType;
use crate::AgentSessionEventParams;
use crate::AgentSessionListParams;
use crate::AgentSessionListResponse;
use crate::AgentSessionOverview;
use crate::AgentSessionReadParams;
use crate::AgentSessionReadResponse;
use crate::AgentSessionStartParams;
use crate::AgentSessionStartResponse;
use crate::AgentSessionStatus;
use crate::AgentSessionTurnCancelParams;
use crate::AgentSessionTurnCancelResponse;
use crate::AgentSessionTurnStartParams;
use crate::AgentSessionTurnStartResponse;
use crate::AgentSessionUpdateParams;
use crate::AgentSessionUpdateResponse;
use crate::AgentTurn;
use crate::AgentTurnStatus;
use crate::AppServerMethodKind;
use crate::ArtifactContentStatus;
use crate::ArtifactReadParams;
use crate::ArtifactReadResponse;
use crate::ArtifactSummary;
use crate::AutomationJobListResponse;
use crate::BusinessObjectRef;
use crate::CapabilityDescriptor;
use crate::CapabilityListParams;
use crate::CapabilityListResponse;
use crate::ClientCapabilities;
use crate::ClientInfo;
use crate::ConnectCallbackSendParams;
use crate::ConnectCallbackSendResponse;
use crate::ConnectCallbackStatus;
use crate::ConnectDeepLinkResolveParams;
use crate::ConnectDeepLinkResolveResponse;
use crate::ConnectOpenDeepLinkResolveParams;
use crate::ConnectOpenDeepLinkResolveResponse;
use crate::ConnectPayload;
use crate::ConnectRelayApiKeySaveParams;
use crate::ConnectRelayApiKeySaveResponse;
use crate::EvidenceExportParams;
use crate::EvidenceExportResponse;
use crate::EvidencePackArtifact;
use crate::EvidencePackSummary;
use crate::FileSystemDirectoryListing;
use crate::FileSystemFileEntry;
use crate::FileSystemFilePreview;
use crate::FileSystemListDirectoryParams;
use crate::FileSystemReadFilePreviewParams;
use crate::InitializeParams;
use crate::InitializeResponse;
use crate::JsonRpcError;
use crate::JsonRpcErrorResponse;
use crate::JsonRpcMessage;
use crate::JsonRpcNotification;
use crate::JsonRpcRequest;
use crate::JsonRpcResponse;
use crate::KnowledgeListPacksParams;
use crate::KnowledgeListPacksResponse;
use crate::ModelListParams;
use crate::ModelListResponse;
use crate::ModelPreferencesListResponse;
use crate::ModelProviderAliasListResponse;
use crate::ModelProviderAliasReadParams;
use crate::ModelProviderAliasReadResponse;
use crate::ModelProviderCatalogListResponse;
use crate::ModelProviderListResponse;
use crate::ModelSyncStateReadResponse;
use crate::OpenDeepLinkPayload;
use crate::PlatformInfo;
use crate::ProjectMemoryReadParams;
use crate::ProjectMemoryReadResponse;
use crate::RequestId;
use crate::RuntimeOptions;
use crate::ServerCapabilities;
use crate::ServerInfo;
use crate::SkillListResponse;
use crate::SkillReadParams;
use crate::SkillReadResponse;
use crate::WorkspaceEnsureParams;
use crate::WorkspaceEnsureReadyResponse;
use crate::WorkspaceListResponse;
use crate::WorkspacePathReadParams;
use crate::WorkspaceProjectPathResolveParams;
use crate::WorkspaceProjectPathResolveResponse;
use crate::WorkspaceProjectsRootReadResponse;
use crate::WorkspaceReadParams;
use crate::WorkspaceReadResponse;
use crate::WorkspaceRegisteredSkillsListParams;
use crate::WorkspaceRegisteredSkillsListResponse;
use crate::WorkspaceSkillBindingsListParams;
use crate::WorkspaceSkillBindingsListResponse;
use crate::APP_SERVER_METHODS;
use crate::JSONRPC_VERSION;
use crate::PROTOCOL_VERSION;
use schemars::JsonSchema;
use serde_json::json;
use serde_json::Value;
use std::collections::BTreeMap;
use std::path::PathBuf;

pub const GENERATED_SCHEMA_HEADER: &str = "Generated by app-server-protocol. Do not edit by hand.";
pub const SCHEMA_BUNDLE_FILE_NAME: &str = "app_server_protocol.schemas.json";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SchemaExportOptions {
    pub include_envelopes: bool,
    pub include_method_catalog: bool,
    pub include_protocol_types: bool,
}

impl Default for SchemaExportOptions {
    fn default() -> Self {
        Self {
            include_envelopes: true,
            include_method_catalog: true,
            include_protocol_types: true,
        }
    }
}

pub fn generate_json_schema_bundle(options: SchemaExportOptions) -> Value {
    let mut properties = serde_json::Map::new();
    if options.include_envelopes {
        properties.insert("requestId".to_string(), request_id_schema());
        properties.insert("jsonRpcRequest".to_string(), json_rpc_request_schema());
        properties.insert(
            "jsonRpcNotification".to_string(),
            json_rpc_notification_schema(),
        );
        properties.insert("jsonRpcResponse".to_string(), json_rpc_response_schema());
        properties.insert("jsonRpcError".to_string(), json_rpc_error_schema());
    }
    if options.include_method_catalog {
        properties.insert("methods".to_string(), method_catalog_schema());
    }
    if options.include_envelopes {
        for schema in jsonrpc_schemas() {
            properties.insert(schema.name.to_string(), schema.value.clone());
        }
    }
    if options.include_protocol_types {
        for schema in v0_schemas() {
            properties.insert(schema.name.to_string(), schema.value.clone());
        }
    }

    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "app-server-protocol",
        "title": "App Server Protocol",
        "description": GENERATED_SCHEMA_HEADER,
        "protocolVersion": PROTOCOL_VERSION,
        "jsonRpcVersion": JSONRPC_VERSION,
        "type": "object",
        "$defs": properties,
    })
}

pub fn generated_schema_tree() -> BTreeMap<PathBuf, Vec<u8>> {
    generated_schema_tree_with_options(SchemaExportOptions::default())
}

pub fn generated_schema_tree_with_options(
    options: SchemaExportOptions,
) -> BTreeMap<PathBuf, Vec<u8>> {
    let mut files = BTreeMap::new();
    files.insert(
        PathBuf::from("json").join(SCHEMA_BUNDLE_FILE_NAME),
        pretty_json_bytes(&generate_json_schema_bundle(options)),
    );
    if options.include_envelopes {
        for schema in jsonrpc_schemas() {
            files.insert(
                PathBuf::from("json")
                    .join("jsonrpc")
                    .join(format!("{}.json", schema.name)),
                pretty_json_bytes(&schema.value),
            );
        }
    }
    if options.include_protocol_types {
        for schema in v0_schemas() {
            files.insert(
                PathBuf::from("json")
                    .join("v0")
                    .join(format!("{}.json", schema.name)),
                pretty_json_bytes(&schema.value),
            );
        }
    }
    files
}

#[derive(Debug, Clone)]
struct GeneratedJsonSchema {
    name: &'static str,
    value: Value,
}

fn typed_schema<T: JsonSchema>(name: &'static str) -> GeneratedJsonSchema {
    GeneratedJsonSchema {
        name,
        value: serde_json::to_value(schemars::schema_for!(T)).expect("serialize JSON schema"),
    }
}

fn jsonrpc_schemas() -> Vec<GeneratedJsonSchema> {
    vec![
        typed_schema::<RequestId>("RequestId"),
        typed_schema::<JsonRpcMessage>("JsonRpcMessage"),
        typed_schema::<JsonRpcRequest>("JsonRpcRequest"),
        typed_schema::<JsonRpcNotification>("JsonRpcNotification"),
        typed_schema::<JsonRpcResponse>("JsonRpcResponse"),
        typed_schema::<JsonRpcErrorResponse>("JsonRpcErrorResponse"),
        typed_schema::<JsonRpcError>("JsonRpcError"),
    ]
}

fn v0_schemas() -> Vec<GeneratedJsonSchema> {
    vec![
        typed_schema::<ClientInfo>("ClientInfo"),
        typed_schema::<ClientCapabilities>("ClientCapabilities"),
        typed_schema::<InitializeParams>("InitializeParams"),
        typed_schema::<InitializeResponse>("InitializeResponse"),
        typed_schema::<ServerInfo>("ServerInfo"),
        typed_schema::<PlatformInfo>("PlatformInfo"),
        typed_schema::<ServerCapabilities>("ServerCapabilities"),
        typed_schema::<CapabilityListParams>("CapabilityListParams"),
        typed_schema::<CapabilityListResponse>("CapabilityListResponse"),
        typed_schema::<CapabilityDescriptor>("CapabilityDescriptor"),
        typed_schema::<ArtifactReadParams>("ArtifactReadParams"),
        typed_schema::<ArtifactContentStatus>("ArtifactContentStatus"),
        typed_schema::<ArtifactSummary>("ArtifactSummary"),
        typed_schema::<ArtifactReadResponse>("ArtifactReadResponse"),
        typed_schema::<FileSystemListDirectoryParams>("FileSystemListDirectoryParams"),
        typed_schema::<FileSystemReadFilePreviewParams>("FileSystemReadFilePreviewParams"),
        typed_schema::<FileSystemDirectoryListing>("FileSystemDirectoryListing"),
        typed_schema::<FileSystemFileEntry>("FileSystemFileEntry"),
        typed_schema::<FileSystemFilePreview>("FileSystemFilePreview"),
        typed_schema::<EvidenceExportParams>("EvidenceExportParams"),
        typed_schema::<EvidenceExportResponse>("EvidenceExportResponse"),
        typed_schema::<EvidencePackSummary>("EvidencePackSummary"),
        typed_schema::<EvidencePackArtifact>("EvidencePackArtifact"),
        typed_schema::<AgentSessionListParams>("AgentSessionListParams"),
        typed_schema::<AgentSessionOverview>("AgentSessionOverview"),
        typed_schema::<AgentSessionListResponse>("AgentSessionListResponse"),
        typed_schema::<AgentSessionUpdateParams>("AgentSessionUpdateParams"),
        typed_schema::<AgentSessionUpdateResponse>("AgentSessionUpdateResponse"),
        typed_schema::<WorkspaceReadParams>("WorkspaceReadParams"),
        typed_schema::<WorkspacePathReadParams>("WorkspacePathReadParams"),
        typed_schema::<WorkspaceProjectPathResolveParams>("WorkspaceProjectPathResolveParams"),
        typed_schema::<WorkspaceEnsureParams>("WorkspaceEnsureParams"),
        typed_schema::<WorkspaceListResponse>("WorkspaceListResponse"),
        typed_schema::<WorkspaceReadResponse>("WorkspaceReadResponse"),
        typed_schema::<WorkspaceProjectsRootReadResponse>("WorkspaceProjectsRootReadResponse"),
        typed_schema::<WorkspaceProjectPathResolveResponse>("WorkspaceProjectPathResolveResponse"),
        typed_schema::<WorkspaceEnsureReadyResponse>("WorkspaceEnsureReadyResponse"),
        typed_schema::<SkillReadParams>("SkillReadParams"),
        typed_schema::<SkillListResponse>("SkillListResponse"),
        typed_schema::<SkillReadResponse>("SkillReadResponse"),
        typed_schema::<WorkspaceSkillBindingsListParams>("WorkspaceSkillBindingsListParams"),
        typed_schema::<WorkspaceSkillBindingsListResponse>("WorkspaceSkillBindingsListResponse"),
        typed_schema::<WorkspaceRegisteredSkillsListParams>("WorkspaceRegisteredSkillsListParams"),
        typed_schema::<WorkspaceRegisteredSkillsListResponse>(
            "WorkspaceRegisteredSkillsListResponse",
        ),
        typed_schema::<AgentAppInstalledListResponse>("AgentAppInstalledListResponse"),
        typed_schema::<AgentAppUiRuntimeStartParams>("AgentAppUiRuntimeStartParams"),
        typed_schema::<AgentAppUiRuntimeStatusParams>("AgentAppUiRuntimeStatusParams"),
        typed_schema::<AgentAppUiRuntimeStopParams>("AgentAppUiRuntimeStopParams"),
        typed_schema::<AgentAppUiRuntimeStatusResponse>("AgentAppUiRuntimeStatusResponse"),
        typed_schema::<KnowledgeListPacksParams>("KnowledgeListPacksParams"),
        typed_schema::<KnowledgeListPacksResponse>("KnowledgeListPacksResponse"),
        typed_schema::<AutomationJobListResponse>("AutomationJobListResponse"),
        typed_schema::<ProjectMemoryReadParams>("ProjectMemoryReadParams"),
        typed_schema::<ProjectMemoryReadResponse>("ProjectMemoryReadResponse"),
        typed_schema::<ModelListParams>("ModelListParams"),
        typed_schema::<ModelListResponse>("ModelListResponse"),
        typed_schema::<ModelPreferencesListResponse>("ModelPreferencesListResponse"),
        typed_schema::<ModelSyncStateReadResponse>("ModelSyncStateReadResponse"),
        typed_schema::<ModelProviderListResponse>("ModelProviderListResponse"),
        typed_schema::<ModelProviderCatalogListResponse>("ModelProviderCatalogListResponse"),
        typed_schema::<ModelProviderAliasReadParams>("ModelProviderAliasReadParams"),
        typed_schema::<ModelProviderAliasReadResponse>("ModelProviderAliasReadResponse"),
        typed_schema::<ModelProviderAliasListResponse>("ModelProviderAliasListResponse"),
        typed_schema::<ConnectDeepLinkResolveParams>("ConnectDeepLinkResolveParams"),
        typed_schema::<ConnectPayload>("ConnectPayload"),
        typed_schema::<ConnectDeepLinkResolveResponse>("ConnectDeepLinkResolveResponse"),
        typed_schema::<ConnectOpenDeepLinkResolveParams>("ConnectOpenDeepLinkResolveParams"),
        typed_schema::<OpenDeepLinkPayload>("OpenDeepLinkPayload"),
        typed_schema::<ConnectOpenDeepLinkResolveResponse>("ConnectOpenDeepLinkResolveResponse"),
        typed_schema::<ConnectRelayApiKeySaveParams>("ConnectRelayApiKeySaveParams"),
        typed_schema::<ConnectRelayApiKeySaveResponse>("ConnectRelayApiKeySaveResponse"),
        typed_schema::<ConnectCallbackStatus>("ConnectCallbackStatus"),
        typed_schema::<ConnectCallbackSendParams>("ConnectCallbackSendParams"),
        typed_schema::<ConnectCallbackSendResponse>("ConnectCallbackSendResponse"),
        typed_schema::<AgentSessionStartParams>("AgentSessionStartParams"),
        typed_schema::<AgentSessionStartResponse>("AgentSessionStartResponse"),
        typed_schema::<AgentSessionReadParams>("AgentSessionReadParams"),
        typed_schema::<AgentSessionReadResponse>("AgentSessionReadResponse"),
        typed_schema::<AgentSessionTurnStartParams>("AgentSessionTurnStartParams"),
        typed_schema::<AgentSessionTurnStartResponse>("AgentSessionTurnStartResponse"),
        typed_schema::<AgentSessionTurnCancelParams>("AgentSessionTurnCancelParams"),
        typed_schema::<AgentSessionTurnCancelResponse>("AgentSessionTurnCancelResponse"),
        typed_schema::<AgentSessionActionType>("AgentSessionActionType"),
        typed_schema::<AgentSessionActionScope>("AgentSessionActionScope"),
        typed_schema::<AgentSessionActionRespondParams>("AgentSessionActionRespondParams"),
        typed_schema::<AgentSessionActionRespondResponse>("AgentSessionActionRespondResponse"),
        typed_schema::<AgentSessionEventParams>("AgentSessionEventParams"),
        typed_schema::<BusinessObjectRef>("BusinessObjectRef"),
        typed_schema::<AgentSessionStatus>("AgentSessionStatus"),
        typed_schema::<AgentSession>("AgentSession"),
        typed_schema::<AgentTurnStatus>("AgentTurnStatus"),
        typed_schema::<AgentTurn>("AgentTurn"),
        typed_schema::<AgentInput>("AgentInput"),
        typed_schema::<AgentAttachment>("AgentAttachment"),
        typed_schema::<RuntimeOptions>("RuntimeOptions"),
        typed_schema::<AgentEvent>("AgentEvent"),
    ]
}

fn request_id_schema() -> Value {
    json!({
        "oneOf": [
            { "type": "integer" },
            { "type": "string" }
        ]
    })
}

fn json_rpc_request_schema() -> Value {
    json!({
        "type": "object",
        "required": ["id", "method"],
        "additionalProperties": false,
        "properties": {
            "id": { "$ref": "#/$defs/requestId" },
            "method": { "type": "string" },
            "params": true
        }
    })
}

fn json_rpc_notification_schema() -> Value {
    json!({
        "type": "object",
        "required": ["method"],
        "additionalProperties": false,
        "properties": {
            "method": { "type": "string" },
            "params": true
        }
    })
}

fn json_rpc_response_schema() -> Value {
    json!({
        "type": "object",
        "required": ["id", "result"],
        "additionalProperties": false,
        "properties": {
            "id": { "$ref": "#/$defs/requestId" },
            "result": true
        }
    })
}

fn json_rpc_error_schema() -> Value {
    json!({
        "type": "object",
        "required": ["id", "error"],
        "additionalProperties": false,
        "properties": {
            "id": { "$ref": "#/$defs/requestId" },
            "error": {
                "type": "object",
                "required": ["code", "message"],
                "additionalProperties": false,
                "properties": {
                    "code": { "type": "integer" },
                    "message": { "type": "string" },
                    "data": true
                }
            }
        }
    })
}

fn method_catalog_schema() -> Value {
    let requests = APP_SERVER_METHODS
        .iter()
        .filter(|method| method.kind == AppServerMethodKind::Request)
        .map(|method| method.method)
        .collect::<Vec<_>>();
    let notifications = APP_SERVER_METHODS
        .iter()
        .filter(|method| method.kind == AppServerMethodKind::Notification)
        .map(|method| method.method)
        .collect::<Vec<_>>();

    json!({
        "type": "object",
        "required": ["requests", "notifications"],
        "additionalProperties": false,
        "properties": {
            "requests": {
                "type": "array",
                "items": { "enum": requests }
            },
            "notifications": {
                "type": "array",
                "items": { "enum": notifications }
            }
        }
    })
}

fn pretty_json_bytes(value: &Value) -> Vec<u8> {
    let mut bytes = serde_json::to_vec_pretty(value).expect("serialize schema JSON");
    bytes.push(b'\n');
    bytes
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn schema_bundle_exports_json_rpc_envelopes_and_method_catalog() {
        let bundle = generate_json_schema_bundle(SchemaExportOptions::default());

        assert_eq!(bundle["protocolVersion"], PROTOCOL_VERSION);
        assert_eq!(bundle["$defs"]["jsonRpcRequest"]["required"][0], "id");
        assert_eq!(
            bundle["$defs"]["methods"]["properties"]["requests"]["items"]["enum"]
                .as_array()
                .expect("requests")
                .len(),
            APP_SERVER_METHODS
                .iter()
                .filter(|method| method.kind == AppServerMethodKind::Request)
                .count()
        );
    }

    #[test]
    fn schema_tree_uses_stable_bundle_path() {
        let tree = generated_schema_tree();

        assert!(tree.contains_key(&PathBuf::from("json").join(SCHEMA_BUNDLE_FILE_NAME)));
        assert!(tree.contains_key(&PathBuf::from("json/v0/AgentSessionTurnStartParams.json")));
        assert!(tree.contains_key(&PathBuf::from("json/jsonrpc/JsonRpcRequest.json")));
        assert_eq!(
            tree.len(),
            1 + crate::JSONRPC_SCHEMA_TYPE_NAMES.len() + crate::V0_SCHEMA_TYPE_NAMES.len()
        );
    }

    #[test]
    fn schema_registry_matches_declared_type_names() {
        let jsonrpc_schema_names = jsonrpc_schemas()
            .iter()
            .map(|schema| schema.name)
            .collect::<Vec<_>>();
        let v0_schema_names = v0_schemas()
            .iter()
            .map(|schema| schema.name)
            .collect::<Vec<_>>();

        assert_eq!(jsonrpc_schema_names, crate::JSONRPC_SCHEMA_TYPE_NAMES);
        assert_eq!(v0_schema_names, crate::V0_SCHEMA_TYPE_NAMES);
    }
}
