mod registry;

use crate::AppServerMethodKind;
use crate::APP_SERVER_METHODS;
use crate::JSONRPC_VERSION;
use crate::PROTOCOL_VERSION;
use registry::jsonrpc_schemas;
use registry::v0_schemas;
use serde_json::json;
use serde_json::Value;
use std::collections::BTreeMap;
use std::path::PathBuf;

pub const GENERATED_SCHEMA_HEADER: &str = "Generated by app-server-protocol. Do not edit by hand.";
pub const SCHEMA_BUNDLE_FILE_NAME: &str = "app_server_protocol.schemas.json";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SchemaExportOptions {
    pub include_envelopes: bool,
    pub include_method_catalog: bool,
    pub include_protocol_types: bool,
}

impl Default for SchemaExportOptions {
    fn default() -> Self {
        Self {
            include_envelopes: true,
            include_method_catalog: true,
            include_protocol_types: true,
        }
    }
}

pub fn generate_json_schema_bundle(options: SchemaExportOptions) -> Value {
    let mut properties = serde_json::Map::new();
    if options.include_envelopes {
        properties.insert("requestId".to_string(), request_id_schema());
        properties.insert("jsonRpcRequest".to_string(), json_rpc_request_schema());
        properties.insert(
            "jsonRpcNotification".to_string(),
            json_rpc_notification_schema(),
        );
        properties.insert("jsonRpcResponse".to_string(), json_rpc_response_schema());
        properties.insert("jsonRpcError".to_string(), json_rpc_error_schema());
    }
    if options.include_method_catalog {
        properties.insert("methods".to_string(), method_catalog_schema());
    }
    if options.include_envelopes {
        for schema in jsonrpc_schemas() {
            properties.insert(schema.name.to_string(), schema.value.clone());
        }
    }
    if options.include_protocol_types {
        for schema in v0_schemas() {
            properties.insert(schema.name.to_string(), schema.value.clone());
        }
    }

    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "app-server-protocol",
        "title": "App Server Protocol",
        "description": GENERATED_SCHEMA_HEADER,
        "protocolVersion": PROTOCOL_VERSION,
        "jsonRpcVersion": JSONRPC_VERSION,
        "type": "object",
        "$defs": properties,
    })
}

pub fn generated_schema_tree() -> BTreeMap<PathBuf, Vec<u8>> {
    generated_schema_tree_with_options(SchemaExportOptions::default())
}

pub fn generated_schema_tree_with_options(
    options: SchemaExportOptions,
) -> BTreeMap<PathBuf, Vec<u8>> {
    let mut files = BTreeMap::new();
    files.insert(
        PathBuf::from("json").join(SCHEMA_BUNDLE_FILE_NAME),
        pretty_json_bytes(&generate_json_schema_bundle(options)),
    );
    if options.include_envelopes {
        for schema in jsonrpc_schemas() {
            files.insert(
                PathBuf::from("json")
                    .join("jsonrpc")
                    .join(format!("{}.json", schema.name)),
                pretty_json_bytes(&schema.value),
            );
        }
    }
    if options.include_protocol_types {
        for schema in v0_schemas() {
            files.insert(
                PathBuf::from("json")
                    .join("v0")
                    .join(format!("{}.json", schema.name)),
                pretty_json_bytes(&schema.value),
            );
        }
    }
    files
}

fn request_id_schema() -> Value {
    json!({
        "oneOf": [
            { "type": "integer" },
            { "type": "string" }
        ]
    })
}

fn json_rpc_request_schema() -> Value {
    json!({
        "type": "object",
        "required": ["id", "method"],
        "additionalProperties": false,
        "properties": {
            "id": { "$ref": "#/$defs/requestId" },
            "method": { "type": "string" },
            "params": true
        }
    })
}

fn json_rpc_notification_schema() -> Value {
    json!({
        "type": "object",
        "required": ["method"],
        "additionalProperties": false,
        "properties": {
            "method": { "type": "string" },
            "params": true
        }
    })
}

fn json_rpc_response_schema() -> Value {
    json!({
        "type": "object",
        "required": ["id", "result"],
        "additionalProperties": false,
        "properties": {
            "id": { "$ref": "#/$defs/requestId" },
            "result": true
        }
    })
}

fn json_rpc_error_schema() -> Value {
    json!({
        "type": "object",
        "required": ["id", "error"],
        "additionalProperties": false,
        "properties": {
            "id": { "$ref": "#/$defs/requestId" },
            "error": {
                "type": "object",
                "required": ["code", "message"],
                "additionalProperties": false,
                "properties": {
                    "code": { "type": "integer" },
                    "message": { "type": "string" },
                    "data": true
                }
            }
        }
    })
}

fn method_catalog_schema() -> Value {
    let requests = APP_SERVER_METHODS
        .iter()
        .filter(|method| method.kind == AppServerMethodKind::Request)
        .map(|method| method.method)
        .collect::<Vec<_>>();
    let notifications = APP_SERVER_METHODS
        .iter()
        .filter(|method| method.kind == AppServerMethodKind::Notification)
        .map(|method| method.method)
        .collect::<Vec<_>>();
    let server_requests = APP_SERVER_METHODS
        .iter()
        .filter(|method| method.kind == AppServerMethodKind::ServerRequest)
        .map(|method| method.method)
        .collect::<Vec<_>>();

    json!({
        "type": "object",
        "required": ["requests", "notifications", "serverRequests"],
        "additionalProperties": false,
        "properties": {
            "requests": {
                "type": "array",
                "items": { "enum": requests }
            },
            "notifications": {
                "type": "array",
                "items": { "enum": notifications }
            },
            "serverRequests": {
                "type": "array",
                "items": { "enum": server_requests }
            }
        }
    })
}

fn pretty_json_bytes(value: &Value) -> Vec<u8> {
    let mut bytes = serde_json::to_vec_pretty(value).expect("serialize schema JSON");
    bytes.push(b'\n');
    bytes
}

#[cfg(test)]
pub(super) mod tests {
    use super::*;
    use crate::{METHOD_MCP_SERVER_ELICITATION_REQUEST, METHOD_SERVER_REQUEST_RESOLVED};

    #[test]
    fn schema_bundle_exports_json_rpc_envelopes_and_method_catalog() {
        let bundle = generate_json_schema_bundle(SchemaExportOptions::default());

        assert_eq!(bundle["protocolVersion"], PROTOCOL_VERSION);
        assert_eq!(bundle["$defs"]["jsonRpcRequest"]["required"][0], "id");
        assert_eq!(
            bundle["$defs"]["methods"]["properties"]["requests"]["items"]["enum"]
                .as_array()
                .expect("requests")
                .len(),
            APP_SERVER_METHODS
                .iter()
                .filter(|method| method.kind == AppServerMethodKind::Request)
                .count()
        );
        assert!(
            bundle["$defs"]["methods"]["properties"]["notifications"]["items"]["enum"]
                .as_array()
                .expect("notifications")
                .contains(&serde_json::Value::String(
                    METHOD_SERVER_REQUEST_RESOLVED.to_string()
                ))
        );
        assert_eq!(
            bundle["$defs"]["methods"]["properties"]["serverRequests"]["items"]["enum"]
                .as_array()
                .expect("server requests"),
            &vec![serde_json::Value::String(
                METHOD_MCP_SERVER_ELICITATION_REQUEST.to_string()
            )]
        );
    }

    #[test]
    fn schema_tree_uses_stable_bundle_path() {
        let tree = generated_schema_tree();

        assert!(tree.contains_key(&PathBuf::from("json").join(SCHEMA_BUNDLE_FILE_NAME)));
        assert!(tree.contains_key(&PathBuf::from("json/v0/AgentSessionTurnStartParams.json")));
        assert!(tree.contains_key(&PathBuf::from("json/jsonrpc/JsonRpcRequest.json")));
        assert_eq!(
            tree.len(),
            1 + crate::JSONRPC_SCHEMA_TYPE_NAMES.len() + crate::V0_SCHEMA_TYPE_NAMES.len()
        );
    }

    #[test]
    fn schema_registry_matches_declared_type_names() {
        let jsonrpc_schema_names = jsonrpc_schemas()
            .iter()
            .map(|schema| schema.name)
            .collect::<Vec<_>>();
        let v0_schema_names = v0_schemas()
            .iter()
            .map(|schema| schema.name)
            .collect::<Vec<_>>();

        assert_eq!(jsonrpc_schema_names, crate::JSONRPC_SCHEMA_TYPE_NAMES);
        assert_eq!(v0_schema_names, crate::V0_SCHEMA_TYPE_NAMES);
    }
}
