import { createAgentStreamSubmissionLifecycle } from "./agentStreamSubmissionLifecycle";
import { executeAgentStreamSubmit } from "./agentStreamSubmitExecution";
import { handleAgentStreamSubmitFailure } from "./agentStreamSubmitFailure";
import type { PreparedAgentStreamUserInputSend } from "./agentStreamUserInputSendPreparation";
import type { AgentStreamPreparedSendEnv } from "./agentStreamPreparedSendEnv";

interface SubmitAgentStreamUserInputOptions {
  preparedSend: PreparedAgentStreamUserInputSend;
  env: AgentStreamPreparedSendEnv;
}

export async function submitAgentStreamUserInput(
  options: SubmitAgentStreamUserInputOptions,
) {
  const { preparedSend, env } = options;
  const {
    assistantMsg,
    runtimeStatusPresentation,
    assistantMsgId,
    userMsgId,
    userMsg,
    content,
    images,
    skipUserMessage,
    expectingQueue,
    effectiveProviderType,
    effectiveModel,
    effectiveExecutionStrategy,
    modelOverride,
    reasoningEffort,
    webSearch,
    searchMode,
    thinking,
    explicitToolPreferences,
    autoContinue,
    systemPrompt,
    requestMetadata,
    assistantDraft,
    targetSessionId,
    submittedDraft,
    skipSessionRestore,
    skipSessionStartHooks,
    skipPreSubmitResume,
    observer,
    syncedSessionModelPreference,
  } = preparedSend;

  const lifecycle = createAgentStreamSubmissionLifecycle({
    assistantMsg,
    assistantMsgId,
    userMsgId,
    userMsg,
    content,
    expectingQueue,
    runtimeStatusPresentation,
    submittedDraft,
    initialThreadId:
      targetSessionId ||
      env.sessionIdRef.current ||
      `local-thread:${assistantMsgId}`,
    listenerMapRef: env.listenerMapRef,
    setActiveStream: env.setActiveStream,
    setMessages: env.setMessages,
    setQueuedTurns: env.setQueuedTurns,
    setThreadItems: env.setThreadItems,
    setThreadTurns: env.setThreadTurns,
    setCurrentTurnId: env.setCurrentTurnId,
  });

  const {
    eventName,
    requestTurnId,
    requestState,
    pendingTurnKey,
    pendingItemKey,
    toolLogIdByToolId,
    toolStartedAtByToolId,
    toolNameByToolId,
    actionLoggedKeys,
    activateStream,
    clearOptimisticItem,
    clearOptimisticTurn,
    disposeListener,
    upsertQueuedTurn,
    removeQueuedTurnsFromProjection,
    removeQueuedDraftMessages,
    markOptimisticFailure,
    registerListener,
    isStreamActivated,
  } = lifecycle;

  try {
    await executeAgentStreamSubmit({
      runtime: env.runtime,
      ensureSession: env.ensureSession,
      attemptSilentTurnRecovery: env.attemptSilentTurnRecovery,
      refreshSessionReadModel: env.refreshSessionReadModel,
      sessionIdRef: env.sessionIdRef,
      getWorkspaceIdForSubmit: env.getWorkspaceIdForSubmit,
      getSyncedSessionExecutionStrategy: env.getSyncedSessionExecutionStrategy,
      getSyncedSessionRecentPreferences: env.getSyncedSessionRecentPreferences,
      effectiveAccessMode: env.accessMode,
      content,
      images,
      skipUserMessage,
      expectingQueue,
      effectiveProviderType,
      effectiveModel,
      effectiveExecutionStrategy,
      modelOverride,
      reasoningEffort,
      webSearch,
      searchMode,
      thinking,
      explicitToolPreferences,
      autoContinue,
      systemPrompt,
      requestMetadata,
      assistantDraft,
      targetSessionId,
      skipSessionRestore,
      skipSessionStartHooks,
      skipPreSubmitResume,
      executionRuntime: env.executionRuntime,
      syncedSessionModelPreference,
      eventName,
      requestTurnId,
      requestState,
      assistantMsgId,
      pendingTurnKey,
      pendingItemKey,
      warnedKeysRef: env.warnedKeysRef,
      actionLoggedKeys,
      toolLogIdByToolId,
      toolStartedAtByToolId,
      toolNameByToolId,
      observer,
      onWriteFile: env.onWriteFile,
      callbacks: {
        activateStream,
        isStreamActivated,
        clearOptimisticItem,
        clearOptimisticTurn,
        disposeListener,
        removeQueuedDraftMessages,
        clearActiveStreamIfMatch: env.clearActiveStreamIfMatch,
        upsertQueuedTurn,
        removeQueuedTurnsFromProjection,
        registerListener,
      },
      appendThinkingToParts: env.appendThinkingToParts,
      setMessages: env.setMessages,
      setIsSending: env.setIsSending,
      setPendingActions: env.setPendingActions,
      getThreadItems: env.getThreadItems,
      setThreadItems: env.setThreadItems,
      setThreadTurns: env.setThreadTurns,
      setCurrentTurnId: env.setCurrentTurnId,
      setExecutionRuntime: env.setExecutionRuntime,
      soulCopy: env.soulCopy,
    });
  } catch (error) {
    handleAgentStreamSubmitFailure({
      error,
      requestState,
      observer,
      content,
      images,
      assistantMsgId,
      expectingQueue,
      eventName,
      activeStreamRef: env.activeStreamRef,
      setMessages: env.setMessages,
      setWorkspacePathMissing: env.setWorkspacePathMissing,
      setIsSending: env.setIsSending,
      clearActiveStreamIfMatch: env.clearActiveStreamIfMatch,
      disposeListener,
      markOptimisticFailure,
      soulCopy: env.soulCopy,
    });
  }
}
