export const mcpMocks: Record<string, (args?: any) => any> = {
  get_mcp_servers: () => [],
  add_mcp_server: () => ({ success: true }),
  update_mcp_server: () => ({ success: true }),
  delete_mcp_server: () => ({ success: true }),
  toggle_mcp_server: () => ({ success: true }),
  import_mcp_from_app: () => ({ success: true }),
  sync_all_mcp_to_live: () => ({ success: true }),
  mcp_list_servers_with_status: () => [],
  mcp_start_server: () => ({ success: true }),
  mcp_stop_server: () => ({ success: true }),
  mcp_list_tools: () => [],
  mcp_list_tools_for_context: () => [],
  mcp_search_tools: () => [],
  mcp_call_tool: () => ({ content: [], is_error: false }),
  mcp_call_tool_with_caller: () => ({ content: [], is_error: false }),
  mcp_list_prompts: () => [],
  mcp_get_prompt: () => ({ description: "", messages: [] }),
  mcp_list_resources: () => [],
  mcp_read_resource: () => ({}),
};
