export const providerMocks: Record<string, (args?: any) => any> = {
  get_relay_providers: () => [],
  list_relay_providers: () => [],
  get_system_provider_catalog: () => [],
  get_api_key_providers: () => [],
  get_api_key_provider: () => null,
  add_custom_api_key_provider: () => ({ success: true }),
  update_api_key_provider: () => ({ success: true }),
  delete_custom_api_key_provider: () => ({ success: true }),
  add_api_key: () => ({ success: true }),
  delete_api_key: () => ({ success: true }),
  toggle_api_key: () => ({ success: true }),
  update_api_key_alias: () => ({ success: true }),
  get_next_api_key: () => null,
  record_api_key_usage: () => ({}),
  record_api_key_error: () => ({}),
  get_provider_ui_state: () => null,
  set_provider_ui_state: () => ({}),
  update_provider_sort_orders: () => ({ success: true }),
  export_api_key_providers: () => ({ config: "{}" }),
  import_api_key_providers: () => ({ success: true }),
};
