export const updateMocks: Record<string, (args?: any) => any> = {
  check_update: () => ({
    current_version: "1.26.0",
    latest_version: null,
    has_update: false,
    download_url: "https://github.com/limecloud/lime/releases",
    release_notes_url: "https://github.com/limecloud/lime/releases",
    release_notes: null,
    pub_date: null,
    checked_at: Math.floor(Date.now() / 1000),
    error: null,
  }),
  check_for_updates: () => ({
    current: "1.26.0",
    latest: null,
    hasUpdate: false,
    downloadUrl: "https://github.com/limecloud/lime/releases",
    releaseNotesUrl: "https://github.com/limecloud/lime/releases",
    releaseNotes: null,
    pubDate: null,
    error: null,
  }),
  get_update_check_settings: () => ({
    enabled: true,
    check_interval_hours: 24,
    show_notification: true,
    last_check_timestamp: 0,
    skipped_version: null,
    remind_later_until: null,
  }),
  get_update_notification_metrics: () => ({
    shown_count: 0,
    update_now_count: 0,
    remind_later_count: 0,
    skip_version_count: 0,
    dismiss_count: 0,
    update_now_rate: 0,
    remind_later_rate: 0,
    skip_version_rate: 0,
    dismiss_rate: 0,
  }),
  record_update_notification_action: () => ({}),
  download_update: () => ({
    success: false,
    message: "当前已是最新版本",
    filePath: null,
  }),
  skip_update_version: () => ({}),
  remind_update_later: () => Math.floor(Date.now() / 1000) + 24 * 3600,
  dismiss_update_notification: () => Math.floor(Date.now() / 1000) + 24 * 3600,
  close_update_window: () => ({}),
  set_update_check_settings: () => ({ success: true }),
  test_update_window: () => ({}),
};
