export const voiceMocks: Record<string, (args?: any) => any> = {
  get_voice_input_config: () => ({
    enabled: false,
    shortcut: "CommandOrControl+Shift+V",
    processor: {
      polish_enabled: true,
      polish_provider: "openai",
      polish_model: "gpt-4.1-mini",
      default_instruction_id: "default",
    },
    output: {
      mode: "type",
      type_delay_ms: 10,
    },
    instructions: [
      {
        id: "default",
        name: "默认润色",
        prompt: "{{text}}",
        is_preset: true,
      },
      {
        id: "translate_en",
        name: "翻译为英文",
        prompt: "{{text}}",
        is_preset: true,
      },
      {
        id: "raw",
        name: "原始输出",
        prompt: "{{text}}",
        is_preset: true,
      },
    ],
    selected_device_id: undefined,
    sound_enabled: true,
    translate_instruction_id: "translate_en",
  }),
  get_asr_credentials: () => [
    {
      id: "openai-default",
      provider: "openai",
      name: "OpenAI Whisper 默认凭证",
      is_default: true,
      disabled: false,
      language: "zh-CN",
    },
  ],
  voice_models_list_catalog: () => [
    {
      id: "sensevoice-small-int8-2024-07-17",
      name: "SenseVoice Small INT8",
      provider: "FunAudioLLM / sherpa-onnx",
      description:
        "本地离线 ASR，支持中文、英文、日文、韩文和粤语；模型按需下载到用户数据目录。",
      version: "2024-07-17",
      languages: ["zh", "en", "ja", "ko", "yue"],
      size_bytes: 262144000,
      download_url:
        "https://models.example.com/voice/sensevoice-small-int8-2024-07-17/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17.tar.bz2",
      vad_model_id: "silero-vad-onnx",
      vad_download_url:
        "https://models.example.com/voice/silero-vad-onnx/silero_vad.onnx",
      runtime: "sherpa-onnx",
      bundled: false,
      checksum_sha256: null,
    },
  ],
  voice_models_get_install_state: () => ({
    model_id: "sensevoice-small-int8-2024-07-17",
    installed: false,
    installing: false,
    install_dir: "/mock/lime/models/voice/sensevoice-small-int8-2024-07-17",
    model_file: null,
    tokens_file: null,
    vad_file: null,
    installed_bytes: 0,
    last_verified_at: Math.floor(Date.now() / 1000),
    missing_files: ["model.int8.onnx", "tokens.txt", "silero_vad.onnx"],
    default_credential_id: null,
  }),
  voice_models_download: () => ({
    state: {
      model_id: "sensevoice-small-int8-2024-07-17",
      installed: true,
      installing: false,
      install_dir: "/mock/lime/models/voice/sensevoice-small-int8-2024-07-17",
      model_file:
        "/mock/lime/models/voice/sensevoice-small-int8-2024-07-17/model.int8.onnx",
      tokens_file:
        "/mock/lime/models/voice/sensevoice-small-int8-2024-07-17/tokens.txt",
      vad_file:
        "/mock/lime/models/voice/sensevoice-small-int8-2024-07-17/silero_vad.onnx",
      installed_bytes: 262144000,
      last_verified_at: Math.floor(Date.now() / 1000),
      missing_files: [],
      default_credential_id: null,
    },
  }),
  voice_models_delete: () => ({
    model_id: "sensevoice-small-int8-2024-07-17",
    installed: false,
    installing: false,
    install_dir: "/mock/lime/models/voice/sensevoice-small-int8-2024-07-17",
    model_file: null,
    tokens_file: null,
    vad_file: null,
    installed_bytes: 0,
    last_verified_at: Math.floor(Date.now() / 1000),
    missing_files: ["model.int8.onnx", "tokens.txt", "silero_vad.onnx"],
    default_credential_id: null,
  }),
  voice_models_set_default: () => ({
    id: "sensevoice-local-sensevoice-small-int8-2024-07-17",
    provider: "sensevoice_local",
    name: "SenseVoice Small 本地",
    is_default: true,
    disabled: false,
    language: "auto",
    sensevoice_config: {
      model_id: "sensevoice-small-int8-2024-07-17",
      model_dir: "/mock/lime/models/voice/sensevoice-small-int8-2024-07-17",
      use_itn: true,
      num_threads: 4,
      vad_model_id: "silero-vad-onnx",
    },
  }),
  voice_models_test_transcribe_file: () => ({
    text: "这是一段 SenseVoice Small 本地测试转写结果。",
    duration_secs: 3.2,
    sample_rate: 16000,
    language: "auto",
  }),
  get_voice_instructions: () => [
    {
      id: "default",
      name: "默认润色",
      prompt: "{{text}}",
      is_preset: true,
    },
    {
      id: "translate_en",
      name: "翻译为英文",
      prompt: "{{text}}",
      is_preset: true,
    },
    {
      id: "raw",
      name: "原始输出",
      prompt: "{{text}}",
      is_preset: true,
    },
  ],
  get_voice_shortcut_runtime_status: () => ({
    shortcut_registered: false,
    registered_shortcut: null,
    fn_supported: false,
    fn_registered: false,
    fn_fallback_shortcut: "CommandOrControl+Shift+V",
    fn_note: "Fn 按住录音当前仅支持 macOS；已使用普通语音快捷键回退。",
  }),
  save_voice_input_config: () => ({}),
  save_voice_instruction: () => ({}),
  delete_voice_instruction: () => ({}),
  list_audio_devices: () => [
    {
      id: "builtin-mic",
      name: "MacBook Pro 麦克风",
      is_default: true,
    },
  ],
  start_recording: () => ({}),
  get_recording_snapshot: () => ({
    audio_data: [1, 2, 3, 4],
    sample_rate: 16000,
    duration: 1.2,
  }),
  get_recording_segment: () => ({
    audio_data: [1, 2, 3, 4],
    sample_rate: 16000,
    duration: 0.8,
    start_sample: 0,
    end_sample: 12800,
    total_samples: 12800,
  }),
  cancel_recording: () => ({}),
  get_recording_status: () => ({
    is_recording: false,
    volume: 0,
    duration: 0,
  }),
};
